namespace BochiBochiEditor
{
	// Token: 0x0200000A RID: 10
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class BlockEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x0600001B RID: 27 RVA: 0x00002388 File Offset: 0x00000588
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600001C RID: 28 RVA: 0x000023D8 File Offset: 0x000005D8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.BlockEditor));
			this.grpBlock = new global::System.Windows.Forms.GroupBox();
			this.lblBLockInfo = new global::System.Windows.Forms.Label();
			this.vsbBlock = new global::System.Windows.Forms.VScrollBar();
			this.pnlBlock = new global::System.Windows.Forms.Panel();
			this.grpPalette = new global::System.Windows.Forms.GroupBox();
			this.vsrPalette = new global::System.Windows.Forms.VScrollBar();
			this.pnlPalette = new global::System.Windows.Forms.Panel();
			this.chkYFlip = new global::System.Windows.Forms.CheckBox();
			this.chkXFlip = new global::System.Windows.Forms.CheckBox();
			this.pnlPreview = new global::System.Windows.Forms.Panel();
			this.cmbPalette = new global::System.Windows.Forms.ComboBox();
			this.grpData = new global::System.Windows.Forms.GroupBox();
			this.lblBlockIndex = new global::System.Windows.Forms.Label();
			this.chkWildWater = new global::System.Windows.Forms.CheckBox();
			this.chkWildGrass = new global::System.Windows.Forms.CheckBox();
			this.lblWild = new global::System.Windows.Forms.Label();
			this.btnSave = new global::System.Windows.Forms.Button();
			this.cmbLayer = new global::System.Windows.Forms.ComboBox();
			this.cmbUnknown = new global::System.Windows.Forms.ComboBox();
			this.cmbAttribute = new global::System.Windows.Forms.ComboBox();
			this.cmbTileAction = new global::System.Windows.Forms.ComboBox();
			this.lblLayer = new global::System.Windows.Forms.Label();
			this.lblUnknown = new global::System.Windows.Forms.Label();
			this.txtUnknown = new global::System.Windows.Forms.TextBox();
			this.lblAttribute = new global::System.Windows.Forms.Label();
			this.txtAttribute = new global::System.Windows.Forms.TextBox();
			this.nudUnknown = new global::System.Windows.Forms.NumericUpDown();
			this.lbltileAction = new global::System.Windows.Forms.Label();
			this.nudAttribute = new global::System.Windows.Forms.NumericUpDown();
			this.txtTileAction = new global::System.Windows.Forms.TextBox();
			this.nudTileAction = new global::System.Windows.Forms.NumericUpDown();
			this.lblData = new global::System.Windows.Forms.Label();
			this.pnlData = new global::System.Windows.Forms.Panel();
			this.grpBlock.SuspendLayout();
			this.grpPalette.SuspendLayout();
			this.grpData.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknown).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudAttribute).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTileAction).BeginInit();
			base.SuspendLayout();
			this.grpBlock.Controls.Add(this.lblBLockInfo);
			this.grpBlock.Controls.Add(this.vsbBlock);
			this.grpBlock.Controls.Add(this.pnlBlock);
			this.grpBlock.Location = new global::System.Drawing.Point(14, 12);
			this.grpBlock.Name = "grpBlock";
			this.grpBlock.Size = new global::System.Drawing.Size(298, 374);
			this.grpBlock.TabIndex = 0;
			this.grpBlock.TabStop = false;
			this.grpBlock.Text = "ブロック";
			this.lblBLockInfo.AutoSize = true;
			this.lblBLockInfo.Location = new global::System.Drawing.Point(14, 20);
			this.lblBLockInfo.Name = "lblBLockInfo";
			this.lblBLockInfo.Size = new global::System.Drawing.Size(141, 12);
			this.lblBLockInfo.TabIndex = 2;
			this.lblBLockInfo.Text = "タイルセット1, 0000 (0x0000)";
			this.vsbBlock.Location = new global::System.Drawing.Point(272, 22);
			this.vsbBlock.Name = "vsbBlock";
			this.vsbBlock.Size = new global::System.Drawing.Size(16, 336);
			this.vsbBlock.TabIndex = 1;
			this.pnlBlock.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnlBlock.Location = new global::System.Drawing.Point(12, 38);
			this.pnlBlock.Name = "pnlBlock";
			this.pnlBlock.Size = new global::System.Drawing.Size(256, 320);
			this.pnlBlock.TabIndex = 0;
			this.grpPalette.Controls.Add(this.vsrPalette);
			this.grpPalette.Controls.Add(this.pnlPalette);
			this.grpPalette.Controls.Add(this.chkYFlip);
			this.grpPalette.Controls.Add(this.chkXFlip);
			this.grpPalette.Controls.Add(this.pnlPreview);
			this.grpPalette.Controls.Add(this.cmbPalette);
			this.grpPalette.Location = new global::System.Drawing.Point(326, 12);
			this.grpPalette.Name = "grpPalette";
			this.grpPalette.Size = new global::System.Drawing.Size(304, 374);
			this.grpPalette.TabIndex = 1;
			this.grpPalette.TabStop = false;
			this.grpPalette.Text = "パレット";
			this.vsrPalette.Location = new global::System.Drawing.Point(274, 62);
			this.vsrPalette.Name = "vsrPalette";
			this.vsrPalette.Size = new global::System.Drawing.Size(16, 296);
			this.vsrPalette.TabIndex = 4;
			this.pnlPalette.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnlPalette.Location = new global::System.Drawing.Point(14, 62);
			this.pnlPalette.Name = "pnlPalette";
			this.pnlPalette.Size = new global::System.Drawing.Size(256, 296);
			this.pnlPalette.TabIndex = 3;
			this.chkYFlip.AutoSize = true;
			this.chkYFlip.Location = new global::System.Drawing.Point(218, 40);
			this.chkYFlip.Name = "chkYFlip";
			this.chkYFlip.Size = new global::System.Drawing.Size(72, 16);
			this.chkYFlip.TabIndex = 2;
			this.chkYFlip.Text = "上下反転";
			this.chkYFlip.UseVisualStyleBackColor = true;
			this.chkXFlip.AutoSize = true;
			this.chkXFlip.Location = new global::System.Drawing.Point(218, 22);
			this.chkXFlip.Name = "chkXFlip";
			this.chkXFlip.Size = new global::System.Drawing.Size(72, 16);
			this.chkXFlip.TabIndex = 2;
			this.chkXFlip.Text = "左右反転";
			this.chkXFlip.UseVisualStyleBackColor = true;
			this.pnlPreview.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnlPreview.Location = new global::System.Drawing.Point(146, 22);
			this.pnlPreview.Name = "pnlPreview";
			this.pnlPreview.Size = new global::System.Drawing.Size(64, 32);
			this.pnlPreview.TabIndex = 1;
			this.cmbPalette.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbPalette.FormattingEnabled = true;
			this.cmbPalette.Location = new global::System.Drawing.Point(14, 22);
			this.cmbPalette.Name = "cmbPalette";
			this.cmbPalette.Size = new global::System.Drawing.Size(120, 20);
			this.cmbPalette.TabIndex = 0;
			this.grpData.Controls.Add(this.lblBlockIndex);
			this.grpData.Controls.Add(this.chkWildWater);
			this.grpData.Controls.Add(this.chkWildGrass);
			this.grpData.Controls.Add(this.lblWild);
			this.grpData.Controls.Add(this.btnSave);
			this.grpData.Controls.Add(this.cmbLayer);
			this.grpData.Controls.Add(this.cmbUnknown);
			this.grpData.Controls.Add(this.cmbAttribute);
			this.grpData.Controls.Add(this.cmbTileAction);
			this.grpData.Controls.Add(this.lblLayer);
			this.grpData.Controls.Add(this.lblUnknown);
			this.grpData.Controls.Add(this.txtUnknown);
			this.grpData.Controls.Add(this.lblAttribute);
			this.grpData.Controls.Add(this.txtAttribute);
			this.grpData.Controls.Add(this.nudUnknown);
			this.grpData.Controls.Add(this.lbltileAction);
			this.grpData.Controls.Add(this.nudAttribute);
			this.grpData.Controls.Add(this.txtTileAction);
			this.grpData.Controls.Add(this.nudTileAction);
			this.grpData.Controls.Add(this.lblData);
			this.grpData.Controls.Add(this.pnlData);
			this.grpData.Location = new global::System.Drawing.Point(644, 12);
			this.grpData.Name = "grpData";
			this.grpData.Size = new global::System.Drawing.Size(206, 374);
			this.grpData.TabIndex = 2;
			this.grpData.TabStop = false;
			this.grpData.Text = "データ";
			this.lblBlockIndex.AutoSize = true;
			this.lblBlockIndex.Location = new global::System.Drawing.Point(89, 20);
			this.lblBlockIndex.Name = "lblBlockIndex";
			this.lblBlockIndex.Size = new global::System.Drawing.Size(35, 12);
			this.lblBlockIndex.TabIndex = 8;
			this.lblBlockIndex.Text = "番号 :";
			this.chkWildWater.AutoSize = true;
			this.chkWildWater.Location = new global::System.Drawing.Point(72, 338);
			this.chkWildWater.Name = "chkWildWater";
			this.chkWildWater.Size = new global::System.Drawing.Size(48, 16);
			this.chkWildWater.TabIndex = 7;
			this.chkWildWater.Text = "水上";
			this.chkWildWater.UseVisualStyleBackColor = true;
			this.chkWildGrass.AutoSize = true;
			this.chkWildGrass.Location = new global::System.Drawing.Point(14, 338);
			this.chkWildGrass.Name = "chkWildGrass";
			this.chkWildGrass.Size = new global::System.Drawing.Size(54, 16);
			this.chkWildGrass.TabIndex = 6;
			this.chkWildGrass.Text = "草むら";
			this.chkWildGrass.UseVisualStyleBackColor = true;
			this.lblWild.AutoSize = true;
			this.lblWild.Location = new global::System.Drawing.Point(14, 320);
			this.lblWild.Name = "lblWild";
			this.lblWild.Size = new global::System.Drawing.Size(59, 12);
			this.lblWild.TabIndex = 5;
			this.lblWild.Text = "野生出現 :";
			this.btnSave.Location = new global::System.Drawing.Point(118, 40);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(72, 28);
			this.btnSave.TabIndex = 4;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			this.cmbLayer.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbLayer.FormattingEnabled = true;
			this.cmbLayer.Location = new global::System.Drawing.Point(14, 292);
			this.cmbLayer.Name = "cmbLayer";
			this.cmbLayer.Size = new global::System.Drawing.Size(176, 20);
			this.cmbLayer.TabIndex = 3;
			this.cmbUnknown.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbUnknown.FormattingEnabled = true;
			this.cmbUnknown.Location = new global::System.Drawing.Point(14, 246);
			this.cmbUnknown.Name = "cmbUnknown";
			this.cmbUnknown.Size = new global::System.Drawing.Size(176, 20);
			this.cmbUnknown.TabIndex = 3;
			this.cmbAttribute.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAttribute.FormattingEnabled = true;
			this.cmbAttribute.Location = new global::System.Drawing.Point(14, 180);
			this.cmbAttribute.Name = "cmbAttribute";
			this.cmbAttribute.Size = new global::System.Drawing.Size(176, 20);
			this.cmbAttribute.TabIndex = 3;
			this.cmbTileAction.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbTileAction.FormattingEnabled = true;
			this.cmbTileAction.Location = new global::System.Drawing.Point(14, 114);
			this.cmbTileAction.Name = "cmbTileAction";
			this.cmbTileAction.Size = new global::System.Drawing.Size(176, 20);
			this.cmbTileAction.TabIndex = 3;
			this.lblLayer.AutoSize = true;
			this.lblLayer.Location = new global::System.Drawing.Point(14, 276);
			this.lblLayer.Name = "lblLayer";
			this.lblLayer.Size = new global::System.Drawing.Size(73, 12);
			this.lblLayer.TabIndex = 2;
			this.lblLayer.Text = "描写レイヤー :";
			this.lblUnknown.AutoSize = true;
			this.lblUnknown.Location = new global::System.Drawing.Point(14, 208);
			this.lblUnknown.Name = "lblUnknown";
			this.lblUnknown.Size = new global::System.Drawing.Size(47, 12);
			this.lblUnknown.TabIndex = 2;
			this.lblUnknown.Text = "不明値 :";
			this.txtUnknown.Location = new global::System.Drawing.Point(67, 224);
			this.txtUnknown.Name = "txtUnknown";
			this.txtUnknown.Size = new global::System.Drawing.Size(48, 19);
			this.txtUnknown.TabIndex = 1;
			this.lblAttribute.AutoSize = true;
			this.lblAttribute.Location = new global::System.Drawing.Point(14, 142);
			this.lblAttribute.Name = "lblAttribute";
			this.lblAttribute.Size = new global::System.Drawing.Size(35, 12);
			this.lblAttribute.TabIndex = 2;
			this.lblAttribute.Text = "属性 :";
			this.txtAttribute.Location = new global::System.Drawing.Point(67, 158);
			this.txtAttribute.Name = "txtAttribute";
			this.txtAttribute.Size = new global::System.Drawing.Size(48, 19);
			this.txtAttribute.TabIndex = 1;
			this.nudUnknown.Location = new global::System.Drawing.Point(14, 224);
			global::System.Windows.Forms.NumericUpDown nudUnknown = this.nudUnknown;
			int[] array = new int[4];
			array[0] = 255;
			nudUnknown.Maximum = new decimal(array);
			this.nudUnknown.Name = "nudUnknown";
			this.nudUnknown.Size = new global::System.Drawing.Size(48, 19);
			this.nudUnknown.TabIndex = 0;
			this.lbltileAction.AutoSize = true;
			this.lbltileAction.Location = new global::System.Drawing.Point(14, 76);
			this.lbltileAction.Name = "lbltileAction";
			this.lbltileAction.Size = new global::System.Drawing.Size(80, 12);
			this.lbltileAction.TabIndex = 2;
			this.lbltileAction.Text = "タイルアクション :";
			this.nudAttribute.Location = new global::System.Drawing.Point(14, 158);
			global::System.Windows.Forms.NumericUpDown nudAttribute = this.nudAttribute;
			int[] array2 = new int[4];
			array2[0] = 255;
			nudAttribute.Maximum = new decimal(array2);
			this.nudAttribute.Name = "nudAttribute";
			this.nudAttribute.Size = new global::System.Drawing.Size(48, 19);
			this.nudAttribute.TabIndex = 0;
			this.txtTileAction.Location = new global::System.Drawing.Point(67, 92);
			this.txtTileAction.Name = "txtTileAction";
			this.txtTileAction.Size = new global::System.Drawing.Size(48, 19);
			this.txtTileAction.TabIndex = 1;
			this.nudTileAction.Location = new global::System.Drawing.Point(14, 92);
			global::System.Windows.Forms.NumericUpDown nudTileAction = this.nudTileAction;
			int[] array3 = new int[4];
			array3[0] = 255;
			nudTileAction.Maximum = new decimal(array3);
			this.nudTileAction.Name = "nudTileAction";
			this.nudTileAction.Size = new global::System.Drawing.Size(48, 19);
			this.nudTileAction.TabIndex = 0;
			this.lblData.AutoSize = true;
			this.lblData.Location = new global::System.Drawing.Point(12, 20);
			this.lblData.Name = "lblData";
			this.lblData.Size = new global::System.Drawing.Size(67, 12);
			this.lblData.TabIndex = 1;
			this.lblData.Text = "下位 / 上位";
			this.pnlData.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnlData.Location = new global::System.Drawing.Point(14, 36);
			this.pnlData.Name = "pnlData";
			this.pnlData.Size = new global::System.Drawing.Size(64, 32);
			this.pnlData.TabIndex = 0;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(866, 399);
			base.Controls.Add(this.grpData);
			base.Controls.Add(this.grpPalette);
			base.Controls.Add(this.grpBlock);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "BlockEditor";
			this.Text = "ブロックエディター";
			this.grpBlock.ResumeLayout(false);
			this.grpBlock.PerformLayout();
			this.grpPalette.ResumeLayout(false);
			this.grpPalette.PerformLayout();
			this.grpData.ResumeLayout(false);
			this.grpData.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknown).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudAttribute).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTileAction).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x0400000D RID: 13
				private VScrollBar _vsbBlock;
		private Panel _pnlBlock;
		private VScrollBar _vsrPalette;
		private Panel _pnlPalette;
		private Panel _pnlPreview;
		private ComboBox _cmbPalette;
		private Panel _pnlData;
		private Button _btnSave;
        private global::System.ComponentModel.IContainer components;
	}
}
