namespace BochiBochiEditor
{
	// Token: 0x0200000F RID: 15
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class HeldItemMailEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x0600012E RID: 302 RVA: 0x0000B1A4 File Offset: 0x000093A4
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600012F RID: 303 RVA: 0x0000B1F4 File Offset: 0x000093F4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.HeldItemMailEditor));
			this.btnSave = new global::System.Windows.Forms.Button();
			this.nudHeldItemMail = new global::System.Windows.Forms.NumericUpDown();
			this.lblHeldItemMail = new global::System.Windows.Forms.Label();
			this.grpEasyChatPreview = new global::System.Windows.Forms.GroupBox();
			this.rbEasyChatPreview1 = new global::System.Windows.Forms.RadioButton();
			this.txtEasyChatPreview1 = new global::System.Windows.Forms.TextBox();
			this.rbEasyChatPreview2 = new global::System.Windows.Forms.RadioButton();
			this.txtEasyChatPreview2 = new global::System.Windows.Forms.TextBox();
			this.rbEasyChatPreview3 = new global::System.Windows.Forms.RadioButton();
			this.txtEasyChatPreview3 = new global::System.Windows.Forms.TextBox();
			this.rbEasyChatPreview4 = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatPreview5 = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatPreview6 = new global::System.Windows.Forms.RadioButton();
			this.txtEasyChatPreview4 = new global::System.Windows.Forms.TextBox();
			this.txtEasyChatPreview5 = new global::System.Windows.Forms.TextBox();
			this.txtEasyChatPreview6 = new global::System.Windows.Forms.TextBox();
			this.rbEasyChatPreview7 = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatPreview8 = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatPreview9 = new global::System.Windows.Forms.RadioButton();
			this.txtEasyChatPreview7 = new global::System.Windows.Forms.TextBox();
			this.txtEasyChatPreview8 = new global::System.Windows.Forms.TextBox();
			this.txtEasyChatPreview9 = new global::System.Windows.Forms.TextBox();
			this.cmbEasyChatListPokemon1 = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListPokemon1 = new global::System.Windows.Forms.RadioButton();
			this.lblEasyChatListPokemon1 = new global::System.Windows.Forms.Label();
			this.grpEasyChatList = new global::System.Windows.Forms.GroupBox();
			this.btnAssign = new global::System.Windows.Forms.Button();
			this.rbEasyChatListPokemon2 = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListPokemon2 = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListPokemon2 = new global::System.Windows.Forms.Label();
			this.rbEasyChatListMove1 = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListMove1 = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListMove2 = new global::System.Windows.Forms.RadioButton();
			this.lblEasyChatListMove1 = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListMove2 = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListMove2 = new global::System.Windows.Forms.Label();
			this.rbEasyChatListStatus = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatListTrainer = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListStatus = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListBattle = new global::System.Windows.Forms.RadioButton();
			this.lblEasyChatListStatus = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListTrainer = new global::System.Windows.Forms.ComboBox();
			this.cmbEasyChatListBattle = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListTrainer = new global::System.Windows.Forms.Label();
			this.lblEasyChatListBattle = new global::System.Windows.Forms.Label();
			this.lblEasyChatListCondition = new global::System.Windows.Forms.Label();
			this.lblEasyChatListSpeech = new global::System.Windows.Forms.Label();
			this.lblEasyChatListEnding = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListCondition = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListPeople = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListEnding = new global::System.Windows.Forms.ComboBox();
			this.cmbEasyChatListSpeech = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListFeeling = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListPeople = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListCondition = new global::System.Windows.Forms.RadioButton();
			this.lblEasyChatListVoice = new global::System.Windows.Forms.Label();
			this.rbEasyChatListSpeech = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListFeeling = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListGreeting = new global::System.Windows.Forms.Label();
			this.rbEasyChatListEnding = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListVoice = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListFeeling = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatListPeople = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatListVoice = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListGreeting = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListGreeting = new global::System.Windows.Forms.RadioButton();
			this.nudEasyChatCount = new global::System.Windows.Forms.NumericUpDown();
			this.lblEasyChatCount = new global::System.Windows.Forms.Label();
			this.rbEasyChatListAction = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListAction = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListAction = new global::System.Windows.Forms.Label();
			this.lblEasyChatListTrendySaying = new global::System.Windows.Forms.Label();
			this.lblEasyChatListMisc = new global::System.Windows.Forms.Label();
			this.lblEasyChatListAdjective = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListTrendySaying = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListHobby = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListAdjective = new global::System.Windows.Forms.ComboBox();
			this.cmbEasyChatListMisc = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListEvent = new global::System.Windows.Forms.Label();
			this.cmbEasyChatListHobby = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListTrendySaying = new global::System.Windows.Forms.RadioButton();
			this.lblEasyChatListTime = new global::System.Windows.Forms.Label();
			this.rbEasyChatListMisc = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListEvent = new global::System.Windows.Forms.ComboBox();
			this.lblEasyChatListLifeStyle = new global::System.Windows.Forms.Label();
			this.rbEasyChatListAdjective = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListTime = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListEvent = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatListHobby = new global::System.Windows.Forms.RadioButton();
			this.rbEasyChatListTime = new global::System.Windows.Forms.RadioButton();
			this.cmbEasyChatListLifeStyle = new global::System.Windows.Forms.ComboBox();
			this.rbEasyChatListLifeStyle = new global::System.Windows.Forms.RadioButton();
			((global::System.ComponentModel.ISupportInitialize)this.nudHeldItemMail).BeginInit();
			this.grpEasyChatPreview.SuspendLayout();
			this.grpEasyChatList.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudEasyChatCount).BeginInit();
			base.SuspendLayout();
			this.btnSave.Location = new global::System.Drawing.Point(16, 16);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(100, 23);
			this.btnSave.TabIndex = 0;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			this.nudHeldItemMail.Location = new global::System.Drawing.Point(204, 19);
			global::System.Windows.Forms.NumericUpDown nudHeldItemMail = this.nudHeldItemMail;
			int[] array = new int[4];
			array[0] = 255;
			nudHeldItemMail.Maximum = new decimal(array);
			this.nudHeldItemMail.Name = "nudHeldItemMail";
			this.nudHeldItemMail.Size = new global::System.Drawing.Size(48, 19);
			this.nudHeldItemMail.TabIndex = 1;
			this.lblHeldItemMail.AutoSize = true;
			this.lblHeldItemMail.Location = new global::System.Drawing.Point(124, 22);
			this.lblHeldItemMail.Name = "lblHeldItemMail";
			this.lblHeldItemMail.Size = new global::System.Drawing.Size(74, 12);
			this.lblHeldItemMail.TabIndex = 2;
			this.lblHeldItemMail.Text = "メール内容ID :";
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview9);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview6);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview3);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview8);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview5);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview2);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview7);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview4);
			this.grpEasyChatPreview.Controls.Add(this.txtEasyChatPreview1);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview9);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview6);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview3);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview8);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview5);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview2);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview7);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview4);
			this.grpEasyChatPreview.Controls.Add(this.rbEasyChatPreview1);
			this.grpEasyChatPreview.Location = new global::System.Drawing.Point(16, 48);
			this.grpEasyChatPreview.Name = "grpEasyChatPreview";
			this.grpEasyChatPreview.Size = new global::System.Drawing.Size(496, 126);
			this.grpEasyChatPreview.TabIndex = 3;
			this.grpEasyChatPreview.TabStop = false;
			this.grpEasyChatPreview.Text = "メール内容";
			this.rbEasyChatPreview1.AutoSize = true;
			this.rbEasyChatPreview1.Location = new global::System.Drawing.Point(16, 26);
			this.rbEasyChatPreview1.Name = "rbEasyChatPreview1";
			this.rbEasyChatPreview1.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview1.TabIndex = 0;
			this.rbEasyChatPreview1.TabStop = true;
			this.rbEasyChatPreview1.UseVisualStyleBackColor = true;
			this.txtEasyChatPreview1.Location = new global::System.Drawing.Point(34, 23);
			this.txtEasyChatPreview1.Name = "txtEasyChatPreview1";
			this.txtEasyChatPreview1.ReadOnly = true;
			this.txtEasyChatPreview1.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview1.TabIndex = 1;
			this.rbEasyChatPreview2.AutoSize = true;
			this.rbEasyChatPreview2.Location = new global::System.Drawing.Point(176, 26);
			this.rbEasyChatPreview2.Name = "rbEasyChatPreview2";
			this.rbEasyChatPreview2.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview2.TabIndex = 0;
			this.rbEasyChatPreview2.TabStop = true;
			this.rbEasyChatPreview2.UseVisualStyleBackColor = true;
			this.txtEasyChatPreview2.Location = new global::System.Drawing.Point(194, 23);
			this.txtEasyChatPreview2.Name = "txtEasyChatPreview2";
			this.txtEasyChatPreview2.ReadOnly = true;
			this.txtEasyChatPreview2.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview2.TabIndex = 1;
			this.rbEasyChatPreview3.AutoSize = true;
			this.rbEasyChatPreview3.Location = new global::System.Drawing.Point(336, 26);
			this.rbEasyChatPreview3.Name = "rbEasyChatPreview3";
			this.rbEasyChatPreview3.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview3.TabIndex = 0;
			this.rbEasyChatPreview3.TabStop = true;
			this.rbEasyChatPreview3.UseVisualStyleBackColor = true;
			this.txtEasyChatPreview3.Location = new global::System.Drawing.Point(354, 23);
			this.txtEasyChatPreview3.Name = "txtEasyChatPreview3";
			this.txtEasyChatPreview3.ReadOnly = true;
			this.txtEasyChatPreview3.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview3.TabIndex = 1;
			this.rbEasyChatPreview4.AutoSize = true;
			this.rbEasyChatPreview4.Location = new global::System.Drawing.Point(16, 60);
			this.rbEasyChatPreview4.Name = "rbEasyChatPreview4";
			this.rbEasyChatPreview4.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview4.TabIndex = 0;
			this.rbEasyChatPreview4.TabStop = true;
			this.rbEasyChatPreview4.UseVisualStyleBackColor = true;
			this.rbEasyChatPreview5.AutoSize = true;
			this.rbEasyChatPreview5.Location = new global::System.Drawing.Point(176, 60);
			this.rbEasyChatPreview5.Name = "rbEasyChatPreview5";
			this.rbEasyChatPreview5.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview5.TabIndex = 0;
			this.rbEasyChatPreview5.TabStop = true;
			this.rbEasyChatPreview5.UseVisualStyleBackColor = true;
			this.rbEasyChatPreview6.AutoSize = true;
			this.rbEasyChatPreview6.Location = new global::System.Drawing.Point(336, 60);
			this.rbEasyChatPreview6.Name = "rbEasyChatPreview6";
			this.rbEasyChatPreview6.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview6.TabIndex = 0;
			this.rbEasyChatPreview6.TabStop = true;
			this.rbEasyChatPreview6.UseVisualStyleBackColor = true;
			this.txtEasyChatPreview4.Location = new global::System.Drawing.Point(34, 57);
			this.txtEasyChatPreview4.Name = "txtEasyChatPreview4";
			this.txtEasyChatPreview4.ReadOnly = true;
			this.txtEasyChatPreview4.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview4.TabIndex = 1;
			this.txtEasyChatPreview5.Location = new global::System.Drawing.Point(194, 57);
			this.txtEasyChatPreview5.Name = "txtEasyChatPreview5";
			this.txtEasyChatPreview5.ReadOnly = true;
			this.txtEasyChatPreview5.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview5.TabIndex = 1;
			this.txtEasyChatPreview6.Location = new global::System.Drawing.Point(354, 57);
			this.txtEasyChatPreview6.Name = "txtEasyChatPreview6";
			this.txtEasyChatPreview6.ReadOnly = true;
			this.txtEasyChatPreview6.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview6.TabIndex = 1;
			this.rbEasyChatPreview7.AutoSize = true;
			this.rbEasyChatPreview7.Location = new global::System.Drawing.Point(16, 94);
			this.rbEasyChatPreview7.Name = "rbEasyChatPreview7";
			this.rbEasyChatPreview7.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview7.TabIndex = 0;
			this.rbEasyChatPreview7.TabStop = true;
			this.rbEasyChatPreview7.UseVisualStyleBackColor = true;
			this.rbEasyChatPreview8.AutoSize = true;
			this.rbEasyChatPreview8.Location = new global::System.Drawing.Point(176, 94);
			this.rbEasyChatPreview8.Name = "rbEasyChatPreview8";
			this.rbEasyChatPreview8.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview8.TabIndex = 0;
			this.rbEasyChatPreview8.TabStop = true;
			this.rbEasyChatPreview8.UseVisualStyleBackColor = true;
			this.rbEasyChatPreview9.AutoSize = true;
			this.rbEasyChatPreview9.Location = new global::System.Drawing.Point(336, 94);
			this.rbEasyChatPreview9.Name = "rbEasyChatPreview9";
			this.rbEasyChatPreview9.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatPreview9.TabIndex = 0;
			this.rbEasyChatPreview9.TabStop = true;
			this.rbEasyChatPreview9.UseVisualStyleBackColor = true;
			this.txtEasyChatPreview7.Location = new global::System.Drawing.Point(34, 91);
			this.txtEasyChatPreview7.Name = "txtEasyChatPreview7";
			this.txtEasyChatPreview7.ReadOnly = true;
			this.txtEasyChatPreview7.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview7.TabIndex = 1;
			this.txtEasyChatPreview8.Location = new global::System.Drawing.Point(194, 91);
			this.txtEasyChatPreview8.Name = "txtEasyChatPreview8";
			this.txtEasyChatPreview8.ReadOnly = true;
			this.txtEasyChatPreview8.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview8.TabIndex = 1;
			this.txtEasyChatPreview9.Location = new global::System.Drawing.Point(354, 91);
			this.txtEasyChatPreview9.Name = "txtEasyChatPreview9";
			this.txtEasyChatPreview9.ReadOnly = true;
			this.txtEasyChatPreview9.Size = new global::System.Drawing.Size(120, 19);
			this.txtEasyChatPreview9.TabIndex = 1;
			this.cmbEasyChatListPokemon1.FormattingEnabled = true;
			this.cmbEasyChatListPokemon1.Location = new global::System.Drawing.Point(103, 24);
			this.cmbEasyChatListPokemon1.Name = "cmbEasyChatListPokemon1";
			this.cmbEasyChatListPokemon1.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListPokemon1.TabIndex = 4;
			this.rbEasyChatListPokemon1.AutoSize = true;
			this.rbEasyChatListPokemon1.Location = new global::System.Drawing.Point(85, 27);
			this.rbEasyChatListPokemon1.Name = "rbEasyChatListPokemon1";
			this.rbEasyChatListPokemon1.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListPokemon1.TabIndex = 5;
			this.rbEasyChatListPokemon1.TabStop = true;
			this.rbEasyChatListPokemon1.UseVisualStyleBackColor = true;
			this.lblEasyChatListPokemon1.AutoSize = true;
			this.lblEasyChatListPokemon1.Location = new global::System.Drawing.Point(16, 28);
			this.lblEasyChatListPokemon1.Name = "lblEasyChatListPokemon1";
			this.lblEasyChatListPokemon1.Size = new global::System.Drawing.Size(54, 12);
			this.lblEasyChatListPokemon1.TabIndex = 6;
			this.lblEasyChatListPokemon1.Text = "ポケモン1 :";
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListTrendySaying);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListMisc);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListAdjective);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListTrendySaying);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListHobby);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListAdjective);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListMisc);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListEvent);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListHobby);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListTrendySaying);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListTime);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListMisc);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListEvent);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListLifeStyle);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListAdjective);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListTime);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListEvent);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListHobby);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListTime);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListLifeStyle);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListLifeStyle);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListAction);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListCondition);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListSpeech);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListAction);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListEnding);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListCondition);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListPeople);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListEnding);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListSpeech);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListFeeling);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListAction);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListPeople);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListCondition);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListVoice);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListSpeech);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListFeeling);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListGreeting);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListEnding);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListVoice);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListFeeling);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListPeople);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListVoice);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListGreeting);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListGreeting);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListBattle);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListMove2);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListTrainer);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListBattle);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListPokemon2);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListTrainer);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListMove2);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListStatus);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListPokemon2);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListBattle);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListMove1);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListMove2);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListStatus);
			this.grpEasyChatList.Controls.Add(this.lblEasyChatListPokemon1);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListTrainer);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListMove1);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListStatus);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListPokemon2);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListMove1);
			this.grpEasyChatList.Controls.Add(this.cmbEasyChatListPokemon1);
			this.grpEasyChatList.Controls.Add(this.rbEasyChatListPokemon1);
			this.grpEasyChatList.Location = new global::System.Drawing.Point(16, 220);
			this.grpEasyChatList.Name = "grpEasyChatList";
			this.grpEasyChatList.Size = new global::System.Drawing.Size(704, 258);
			this.grpEasyChatList.TabIndex = 7;
			this.grpEasyChatList.TabStop = false;
			this.grpEasyChatList.Text = "言葉を選択";
			this.btnAssign.Location = new global::System.Drawing.Point(16, 186);
			this.btnAssign.Name = "btnAssign";
			this.btnAssign.Size = new global::System.Drawing.Size(100, 23);
			this.btnAssign.TabIndex = 0;
			this.btnAssign.Text = "↑代入";
			this.btnAssign.UseVisualStyleBackColor = true;
			this.rbEasyChatListPokemon2.AutoSize = true;
			this.rbEasyChatListPokemon2.Location = new global::System.Drawing.Point(85, 55);
			this.rbEasyChatListPokemon2.Name = "rbEasyChatListPokemon2";
			this.rbEasyChatListPokemon2.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListPokemon2.TabIndex = 5;
			this.rbEasyChatListPokemon2.TabStop = true;
			this.rbEasyChatListPokemon2.UseVisualStyleBackColor = true;
			this.cmbEasyChatListPokemon2.FormattingEnabled = true;
			this.cmbEasyChatListPokemon2.Location = new global::System.Drawing.Point(103, 52);
			this.cmbEasyChatListPokemon2.Name = "cmbEasyChatListPokemon2";
			this.cmbEasyChatListPokemon2.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListPokemon2.TabIndex = 4;
			this.lblEasyChatListPokemon2.AutoSize = true;
			this.lblEasyChatListPokemon2.Location = new global::System.Drawing.Point(16, 56);
			this.lblEasyChatListPokemon2.Name = "lblEasyChatListPokemon2";
			this.lblEasyChatListPokemon2.Size = new global::System.Drawing.Size(54, 12);
			this.lblEasyChatListPokemon2.TabIndex = 6;
			this.lblEasyChatListPokemon2.Text = "ポケモン2 :";
			this.rbEasyChatListMove1.AutoSize = true;
			this.rbEasyChatListMove1.Location = new global::System.Drawing.Point(85, 83);
			this.rbEasyChatListMove1.Name = "rbEasyChatListMove1";
			this.rbEasyChatListMove1.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListMove1.TabIndex = 5;
			this.rbEasyChatListMove1.TabStop = true;
			this.rbEasyChatListMove1.UseVisualStyleBackColor = true;
			this.cmbEasyChatListMove1.FormattingEnabled = true;
			this.cmbEasyChatListMove1.Location = new global::System.Drawing.Point(103, 80);
			this.cmbEasyChatListMove1.Name = "cmbEasyChatListMove1";
			this.cmbEasyChatListMove1.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListMove1.TabIndex = 4;
			this.rbEasyChatListMove2.AutoSize = true;
			this.rbEasyChatListMove2.Location = new global::System.Drawing.Point(85, 111);
			this.rbEasyChatListMove2.Name = "rbEasyChatListMove2";
			this.rbEasyChatListMove2.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListMove2.TabIndex = 5;
			this.rbEasyChatListMove2.TabStop = true;
			this.rbEasyChatListMove2.UseVisualStyleBackColor = true;
			this.lblEasyChatListMove1.AutoSize = true;
			this.lblEasyChatListMove1.Location = new global::System.Drawing.Point(16, 84);
			this.lblEasyChatListMove1.Name = "lblEasyChatListMove1";
			this.lblEasyChatListMove1.Size = new global::System.Drawing.Size(36, 12);
			this.lblEasyChatListMove1.TabIndex = 6;
			this.lblEasyChatListMove1.Text = "わざ1 :";
			this.cmbEasyChatListMove2.FormattingEnabled = true;
			this.cmbEasyChatListMove2.Location = new global::System.Drawing.Point(103, 108);
			this.cmbEasyChatListMove2.Name = "cmbEasyChatListMove2";
			this.cmbEasyChatListMove2.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListMove2.TabIndex = 4;
			this.lblEasyChatListMove2.AutoSize = true;
			this.lblEasyChatListMove2.Location = new global::System.Drawing.Point(16, 112);
			this.lblEasyChatListMove2.Name = "lblEasyChatListMove2";
			this.lblEasyChatListMove2.Size = new global::System.Drawing.Size(36, 12);
			this.lblEasyChatListMove2.TabIndex = 6;
			this.lblEasyChatListMove2.Text = "わざ2 :";
			this.rbEasyChatListStatus.AutoSize = true;
			this.rbEasyChatListStatus.Location = new global::System.Drawing.Point(85, 167);
			this.rbEasyChatListStatus.Name = "rbEasyChatListStatus";
			this.rbEasyChatListStatus.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListStatus.TabIndex = 5;
			this.rbEasyChatListStatus.TabStop = true;
			this.rbEasyChatListStatus.UseVisualStyleBackColor = true;
			this.rbEasyChatListTrainer.AutoSize = true;
			this.rbEasyChatListTrainer.Location = new global::System.Drawing.Point(85, 139);
			this.rbEasyChatListTrainer.Name = "rbEasyChatListTrainer";
			this.rbEasyChatListTrainer.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListTrainer.TabIndex = 5;
			this.rbEasyChatListTrainer.TabStop = true;
			this.rbEasyChatListTrainer.UseVisualStyleBackColor = true;
			this.cmbEasyChatListStatus.FormattingEnabled = true;
			this.cmbEasyChatListStatus.Location = new global::System.Drawing.Point(103, 164);
			this.cmbEasyChatListStatus.Name = "cmbEasyChatListStatus";
			this.cmbEasyChatListStatus.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListStatus.TabIndex = 4;
			this.rbEasyChatListBattle.AutoSize = true;
			this.rbEasyChatListBattle.Location = new global::System.Drawing.Point(85, 195);
			this.rbEasyChatListBattle.Name = "rbEasyChatListBattle";
			this.rbEasyChatListBattle.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListBattle.TabIndex = 5;
			this.rbEasyChatListBattle.TabStop = true;
			this.rbEasyChatListBattle.UseVisualStyleBackColor = true;
			this.lblEasyChatListStatus.AutoSize = true;
			this.lblEasyChatListStatus.Location = new global::System.Drawing.Point(16, 168);
			this.lblEasyChatListStatus.Name = "lblEasyChatListStatus";
			this.lblEasyChatListStatus.Size = new global::System.Drawing.Size(56, 12);
			this.lblEasyChatListStatus.TabIndex = 6;
			this.lblEasyChatListStatus.Text = "ステータス :";
			this.cmbEasyChatListTrainer.FormattingEnabled = true;
			this.cmbEasyChatListTrainer.Location = new global::System.Drawing.Point(103, 136);
			this.cmbEasyChatListTrainer.Name = "cmbEasyChatListTrainer";
			this.cmbEasyChatListTrainer.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListTrainer.TabIndex = 4;
			this.cmbEasyChatListBattle.FormattingEnabled = true;
			this.cmbEasyChatListBattle.Location = new global::System.Drawing.Point(103, 192);
			this.cmbEasyChatListBattle.Name = "cmbEasyChatListBattle";
			this.cmbEasyChatListBattle.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListBattle.TabIndex = 4;
			this.lblEasyChatListTrainer.AutoSize = true;
			this.lblEasyChatListTrainer.Location = new global::System.Drawing.Point(16, 140);
			this.lblEasyChatListTrainer.Name = "lblEasyChatListTrainer";
			this.lblEasyChatListTrainer.Size = new global::System.Drawing.Size(58, 12);
			this.lblEasyChatListTrainer.TabIndex = 6;
			this.lblEasyChatListTrainer.Text = "トレーナー :";
			this.lblEasyChatListBattle.AutoSize = true;
			this.lblEasyChatListBattle.Location = new global::System.Drawing.Point(16, 196);
			this.lblEasyChatListBattle.Name = "lblEasyChatListBattle";
			this.lblEasyChatListBattle.Size = new global::System.Drawing.Size(39, 12);
			this.lblEasyChatListBattle.TabIndex = 6;
			this.lblEasyChatListBattle.Text = "バトル :";
			this.lblEasyChatListCondition.AutoSize = true;
			this.lblEasyChatListCondition.Location = new global::System.Drawing.Point(246, 196);
			this.lblEasyChatListCondition.Name = "lblEasyChatListCondition";
			this.lblEasyChatListCondition.Size = new global::System.Drawing.Size(53, 12);
			this.lblEasyChatListCondition.TabIndex = 27;
			this.lblEasyChatListCondition.Text = "じょうたい :";
			this.lblEasyChatListSpeech.AutoSize = true;
			this.lblEasyChatListSpeech.Location = new global::System.Drawing.Point(246, 112);
			this.lblEasyChatListSpeech.Name = "lblEasyChatListSpeech";
			this.lblEasyChatListSpeech.Size = new global::System.Drawing.Size(41, 12);
			this.lblEasyChatListSpeech.TabIndex = 25;
			this.lblEasyChatListSpeech.Text = "かいわ :";
			this.lblEasyChatListEnding.AutoSize = true;
			this.lblEasyChatListEnding.Location = new global::System.Drawing.Point(246, 140);
			this.lblEasyChatListEnding.Name = "lblEasyChatListEnding";
			this.lblEasyChatListEnding.Size = new global::System.Drawing.Size(41, 12);
			this.lblEasyChatListEnding.TabIndex = 24;
			this.lblEasyChatListEnding.Text = "むすび :";
			this.cmbEasyChatListCondition.FormattingEnabled = true;
			this.cmbEasyChatListCondition.Location = new global::System.Drawing.Point(333, 192);
			this.cmbEasyChatListCondition.Name = "cmbEasyChatListCondition";
			this.cmbEasyChatListCondition.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListCondition.TabIndex = 7;
			this.lblEasyChatListPeople.AutoSize = true;
			this.lblEasyChatListPeople.Location = new global::System.Drawing.Point(246, 56);
			this.lblEasyChatListPeople.Name = "lblEasyChatListPeople";
			this.lblEasyChatListPeople.Size = new global::System.Drawing.Size(29, 12);
			this.lblEasyChatListPeople.TabIndex = 23;
			this.lblEasyChatListPeople.Text = "ひと :";
			this.cmbEasyChatListEnding.FormattingEnabled = true;
			this.cmbEasyChatListEnding.Location = new global::System.Drawing.Point(333, 136);
			this.cmbEasyChatListEnding.Name = "cmbEasyChatListEnding";
			this.cmbEasyChatListEnding.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListEnding.TabIndex = 8;
			this.cmbEasyChatListSpeech.FormattingEnabled = true;
			this.cmbEasyChatListSpeech.Location = new global::System.Drawing.Point(333, 108);
			this.cmbEasyChatListSpeech.Name = "cmbEasyChatListSpeech";
			this.cmbEasyChatListSpeech.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListSpeech.TabIndex = 9;
			this.lblEasyChatListFeeling.AutoSize = true;
			this.lblEasyChatListFeeling.Location = new global::System.Drawing.Point(246, 168);
			this.lblEasyChatListFeeling.Name = "lblEasyChatListFeeling";
			this.lblEasyChatListFeeling.Size = new global::System.Drawing.Size(38, 12);
			this.lblEasyChatListFeeling.TabIndex = 22;
			this.lblEasyChatListFeeling.Text = "きもち :";
			this.cmbEasyChatListPeople.FormattingEnabled = true;
			this.cmbEasyChatListPeople.Location = new global::System.Drawing.Point(333, 52);
			this.cmbEasyChatListPeople.Name = "cmbEasyChatListPeople";
			this.cmbEasyChatListPeople.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListPeople.TabIndex = 11;
			this.rbEasyChatListCondition.AutoSize = true;
			this.rbEasyChatListCondition.Location = new global::System.Drawing.Point(315, 195);
			this.rbEasyChatListCondition.Name = "rbEasyChatListCondition";
			this.rbEasyChatListCondition.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListCondition.TabIndex = 18;
			this.rbEasyChatListCondition.TabStop = true;
			this.rbEasyChatListCondition.UseVisualStyleBackColor = true;
			this.lblEasyChatListVoice.AutoSize = true;
			this.lblEasyChatListVoice.Location = new global::System.Drawing.Point(246, 84);
			this.lblEasyChatListVoice.Name = "lblEasyChatListVoice";
			this.lblEasyChatListVoice.Size = new global::System.Drawing.Size(28, 12);
			this.lblEasyChatListVoice.TabIndex = 21;
			this.lblEasyChatListVoice.Text = "こえ :";
			this.rbEasyChatListSpeech.AutoSize = true;
			this.rbEasyChatListSpeech.Location = new global::System.Drawing.Point(315, 111);
			this.rbEasyChatListSpeech.Name = "rbEasyChatListSpeech";
			this.rbEasyChatListSpeech.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListSpeech.TabIndex = 19;
			this.rbEasyChatListSpeech.TabStop = true;
			this.rbEasyChatListSpeech.UseVisualStyleBackColor = true;
			this.cmbEasyChatListFeeling.FormattingEnabled = true;
			this.cmbEasyChatListFeeling.Location = new global::System.Drawing.Point(333, 164);
			this.cmbEasyChatListFeeling.Name = "cmbEasyChatListFeeling";
			this.cmbEasyChatListFeeling.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListFeeling.TabIndex = 13;
			this.lblEasyChatListGreeting.AutoSize = true;
			this.lblEasyChatListGreeting.Location = new global::System.Drawing.Point(246, 28);
			this.lblEasyChatListGreeting.Name = "lblEasyChatListGreeting";
			this.lblEasyChatListGreeting.Size = new global::System.Drawing.Size(48, 12);
			this.lblEasyChatListGreeting.TabIndex = 26;
			this.lblEasyChatListGreeting.Text = "あいさつ :";
			this.rbEasyChatListEnding.AutoSize = true;
			this.rbEasyChatListEnding.Location = new global::System.Drawing.Point(315, 139);
			this.rbEasyChatListEnding.Name = "rbEasyChatListEnding";
			this.rbEasyChatListEnding.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListEnding.TabIndex = 20;
			this.rbEasyChatListEnding.TabStop = true;
			this.rbEasyChatListEnding.UseVisualStyleBackColor = true;
			this.cmbEasyChatListVoice.FormattingEnabled = true;
			this.cmbEasyChatListVoice.Location = new global::System.Drawing.Point(333, 80);
			this.cmbEasyChatListVoice.Name = "cmbEasyChatListVoice";
			this.cmbEasyChatListVoice.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListVoice.TabIndex = 10;
			this.rbEasyChatListFeeling.AutoSize = true;
			this.rbEasyChatListFeeling.Location = new global::System.Drawing.Point(315, 167);
			this.rbEasyChatListFeeling.Name = "rbEasyChatListFeeling";
			this.rbEasyChatListFeeling.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListFeeling.TabIndex = 17;
			this.rbEasyChatListFeeling.TabStop = true;
			this.rbEasyChatListFeeling.UseVisualStyleBackColor = true;
			this.rbEasyChatListPeople.AutoSize = true;
			this.rbEasyChatListPeople.Location = new global::System.Drawing.Point(315, 55);
			this.rbEasyChatListPeople.Name = "rbEasyChatListPeople";
			this.rbEasyChatListPeople.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListPeople.TabIndex = 16;
			this.rbEasyChatListPeople.TabStop = true;
			this.rbEasyChatListPeople.UseVisualStyleBackColor = true;
			this.rbEasyChatListVoice.AutoSize = true;
			this.rbEasyChatListVoice.Location = new global::System.Drawing.Point(315, 83);
			this.rbEasyChatListVoice.Name = "rbEasyChatListVoice";
			this.rbEasyChatListVoice.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListVoice.TabIndex = 15;
			this.rbEasyChatListVoice.TabStop = true;
			this.rbEasyChatListVoice.UseVisualStyleBackColor = true;
			this.cmbEasyChatListGreeting.FormattingEnabled = true;
			this.cmbEasyChatListGreeting.Location = new global::System.Drawing.Point(333, 24);
			this.cmbEasyChatListGreeting.Name = "cmbEasyChatListGreeting";
			this.cmbEasyChatListGreeting.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListGreeting.TabIndex = 12;
			this.rbEasyChatListGreeting.AutoSize = true;
			this.rbEasyChatListGreeting.Location = new global::System.Drawing.Point(315, 27);
			this.rbEasyChatListGreeting.Name = "rbEasyChatListGreeting";
			this.rbEasyChatListGreeting.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListGreeting.TabIndex = 14;
			this.rbEasyChatListGreeting.TabStop = true;
			this.rbEasyChatListGreeting.UseVisualStyleBackColor = true;
			this.nudEasyChatCount.Location = new global::System.Drawing.Point(316, 19);
			global::System.Windows.Forms.NumericUpDown nudEasyChatCount = this.nudEasyChatCount;
			int[] array2 = new int[4];
			array2[0] = 9;
			nudEasyChatCount.Maximum = new decimal(array2);
			global::System.Windows.Forms.NumericUpDown nudEasyChatCount2 = this.nudEasyChatCount;
			int[] array3 = new int[4];
			array3[0] = 1;
			nudEasyChatCount2.Minimum = new decimal(array3);
			this.nudEasyChatCount.Name = "nudEasyChatCount";
			this.nudEasyChatCount.Size = new global::System.Drawing.Size(48, 19);
			this.nudEasyChatCount.TabIndex = 8;
			global::System.Windows.Forms.NumericUpDown nudEasyChatCount3 = this.nudEasyChatCount;
			int[] array4 = new int[4];
			array4[0] = 1;
			nudEasyChatCount3.Value = new decimal(array4);
			this.lblEasyChatCount.AutoSize = true;
			this.lblEasyChatCount.Location = new global::System.Drawing.Point(262, 22);
			this.lblEasyChatCount.Name = "lblEasyChatCount";
			this.lblEasyChatCount.Size = new global::System.Drawing.Size(47, 12);
			this.lblEasyChatCount.TabIndex = 2;
			this.lblEasyChatCount.Text = "言葉数 :";
			this.rbEasyChatListAction.AutoSize = true;
			this.rbEasyChatListAction.Location = new global::System.Drawing.Point(545, 27);
			this.rbEasyChatListAction.Name = "rbEasyChatListAction";
			this.rbEasyChatListAction.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListAction.TabIndex = 18;
			this.rbEasyChatListAction.TabStop = true;
			this.rbEasyChatListAction.UseVisualStyleBackColor = true;
			this.cmbEasyChatListAction.FormattingEnabled = true;
			this.cmbEasyChatListAction.Location = new global::System.Drawing.Point(563, 24);
			this.cmbEasyChatListAction.Name = "cmbEasyChatListAction";
			this.cmbEasyChatListAction.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListAction.TabIndex = 7;
			this.lblEasyChatListAction.AutoSize = true;
			this.lblEasyChatListAction.Location = new global::System.Drawing.Point(476, 28);
			this.lblEasyChatListAction.Name = "lblEasyChatListAction";
			this.lblEasyChatListAction.Size = new global::System.Drawing.Size(42, 12);
			this.lblEasyChatListAction.TabIndex = 27;
			this.lblEasyChatListAction.Text = "こうどう :";
			this.lblEasyChatListTrendySaying.AutoSize = true;
			this.lblEasyChatListTrendySaying.Location = new global::System.Drawing.Point(476, 224);
			this.lblEasyChatListTrendySaying.Name = "lblEasyChatListTrendySaying";
			this.lblEasyChatListTrendySaying.Size = new global::System.Drawing.Size(65, 12);
			this.lblEasyChatListTrendySaying.TabIndex = 48;
			this.lblEasyChatListTrendySaying.Text = "ナウイことば :";
			this.lblEasyChatListMisc.AutoSize = true;
			this.lblEasyChatListMisc.Location = new global::System.Drawing.Point(476, 140);
			this.lblEasyChatListMisc.Name = "lblEasyChatListMisc";
			this.lblEasyChatListMisc.Size = new global::System.Drawing.Size(51, 12);
			this.lblEasyChatListMisc.TabIndex = 46;
			this.lblEasyChatListMisc.Text = "あれこれ :";
			this.lblEasyChatListAdjective.AutoSize = true;
			this.lblEasyChatListAdjective.Location = new global::System.Drawing.Point(476, 168);
			this.lblEasyChatListAdjective.Name = "lblEasyChatListAdjective";
			this.lblEasyChatListAdjective.Size = new global::System.Drawing.Size(53, 12);
			this.lblEasyChatListAdjective.TabIndex = 45;
			this.lblEasyChatListAdjective.Text = "くりかえし :";
			this.cmbEasyChatListTrendySaying.FormattingEnabled = true;
			this.cmbEasyChatListTrendySaying.Location = new global::System.Drawing.Point(563, 220);
			this.cmbEasyChatListTrendySaying.Name = "cmbEasyChatListTrendySaying";
			this.cmbEasyChatListTrendySaying.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListTrendySaying.TabIndex = 28;
			this.lblEasyChatListHobby.AutoSize = true;
			this.lblEasyChatListHobby.Location = new global::System.Drawing.Point(476, 84);
			this.lblEasyChatListHobby.Name = "lblEasyChatListHobby";
			this.lblEasyChatListHobby.Size = new global::System.Drawing.Size(39, 12);
			this.lblEasyChatListHobby.TabIndex = 44;
			this.lblEasyChatListHobby.Text = "しゅみ :";
			this.cmbEasyChatListAdjective.FormattingEnabled = true;
			this.cmbEasyChatListAdjective.Location = new global::System.Drawing.Point(563, 164);
			this.cmbEasyChatListAdjective.Name = "cmbEasyChatListAdjective";
			this.cmbEasyChatListAdjective.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListAdjective.TabIndex = 29;
			this.cmbEasyChatListMisc.FormattingEnabled = true;
			this.cmbEasyChatListMisc.Location = new global::System.Drawing.Point(563, 136);
			this.cmbEasyChatListMisc.Name = "cmbEasyChatListMisc";
			this.cmbEasyChatListMisc.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListMisc.TabIndex = 30;
			this.lblEasyChatListEvent.AutoSize = true;
			this.lblEasyChatListEvent.Location = new global::System.Drawing.Point(476, 196);
			this.lblEasyChatListEvent.Name = "lblEasyChatListEvent";
			this.lblEasyChatListEvent.Size = new global::System.Drawing.Size(47, 12);
			this.lblEasyChatListEvent.TabIndex = 43;
			this.lblEasyChatListEvent.Text = "イベント :";
			this.cmbEasyChatListHobby.FormattingEnabled = true;
			this.cmbEasyChatListHobby.Location = new global::System.Drawing.Point(563, 80);
			this.cmbEasyChatListHobby.Name = "cmbEasyChatListHobby";
			this.cmbEasyChatListHobby.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListHobby.TabIndex = 32;
			this.rbEasyChatListTrendySaying.AutoSize = true;
			this.rbEasyChatListTrendySaying.Location = new global::System.Drawing.Point(545, 223);
			this.rbEasyChatListTrendySaying.Name = "rbEasyChatListTrendySaying";
			this.rbEasyChatListTrendySaying.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListTrendySaying.TabIndex = 39;
			this.rbEasyChatListTrendySaying.TabStop = true;
			this.rbEasyChatListTrendySaying.UseVisualStyleBackColor = true;
			this.lblEasyChatListTime.AutoSize = true;
			this.lblEasyChatListTime.Location = new global::System.Drawing.Point(476, 112);
			this.lblEasyChatListTime.Name = "lblEasyChatListTime";
			this.lblEasyChatListTime.Size = new global::System.Drawing.Size(40, 12);
			this.lblEasyChatListTime.TabIndex = 42;
			this.lblEasyChatListTime.Text = "じかん :";
			this.rbEasyChatListMisc.AutoSize = true;
			this.rbEasyChatListMisc.Location = new global::System.Drawing.Point(545, 139);
			this.rbEasyChatListMisc.Name = "rbEasyChatListMisc";
			this.rbEasyChatListMisc.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListMisc.TabIndex = 40;
			this.rbEasyChatListMisc.TabStop = true;
			this.rbEasyChatListMisc.UseVisualStyleBackColor = true;
			this.cmbEasyChatListEvent.FormattingEnabled = true;
			this.cmbEasyChatListEvent.Location = new global::System.Drawing.Point(563, 192);
			this.cmbEasyChatListEvent.Name = "cmbEasyChatListEvent";
			this.cmbEasyChatListEvent.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListEvent.TabIndex = 34;
			this.lblEasyChatListLifeStyle.AutoSize = true;
			this.lblEasyChatListLifeStyle.Location = new global::System.Drawing.Point(476, 56);
			this.lblEasyChatListLifeStyle.Name = "lblEasyChatListLifeStyle";
			this.lblEasyChatListLifeStyle.Size = new global::System.Drawing.Size(50, 12);
			this.lblEasyChatListLifeStyle.TabIndex = 47;
			this.lblEasyChatListLifeStyle.Text = "せいかつ :";
			this.rbEasyChatListAdjective.AutoSize = true;
			this.rbEasyChatListAdjective.Location = new global::System.Drawing.Point(545, 167);
			this.rbEasyChatListAdjective.Name = "rbEasyChatListAdjective";
			this.rbEasyChatListAdjective.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListAdjective.TabIndex = 41;
			this.rbEasyChatListAdjective.TabStop = true;
			this.rbEasyChatListAdjective.UseVisualStyleBackColor = true;
			this.cmbEasyChatListTime.FormattingEnabled = true;
			this.cmbEasyChatListTime.Location = new global::System.Drawing.Point(563, 108);
			this.cmbEasyChatListTime.Name = "cmbEasyChatListTime";
			this.cmbEasyChatListTime.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListTime.TabIndex = 31;
			this.rbEasyChatListEvent.AutoSize = true;
			this.rbEasyChatListEvent.Location = new global::System.Drawing.Point(545, 195);
			this.rbEasyChatListEvent.Name = "rbEasyChatListEvent";
			this.rbEasyChatListEvent.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListEvent.TabIndex = 38;
			this.rbEasyChatListEvent.TabStop = true;
			this.rbEasyChatListEvent.UseVisualStyleBackColor = true;
			this.rbEasyChatListHobby.AutoSize = true;
			this.rbEasyChatListHobby.Location = new global::System.Drawing.Point(545, 83);
			this.rbEasyChatListHobby.Name = "rbEasyChatListHobby";
			this.rbEasyChatListHobby.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListHobby.TabIndex = 37;
			this.rbEasyChatListHobby.TabStop = true;
			this.rbEasyChatListHobby.UseVisualStyleBackColor = true;
			this.rbEasyChatListTime.AutoSize = true;
			this.rbEasyChatListTime.Location = new global::System.Drawing.Point(545, 111);
			this.rbEasyChatListTime.Name = "rbEasyChatListTime";
			this.rbEasyChatListTime.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListTime.TabIndex = 36;
			this.rbEasyChatListTime.TabStop = true;
			this.rbEasyChatListTime.UseVisualStyleBackColor = true;
			this.cmbEasyChatListLifeStyle.FormattingEnabled = true;
			this.cmbEasyChatListLifeStyle.Location = new global::System.Drawing.Point(563, 52);
			this.cmbEasyChatListLifeStyle.Name = "cmbEasyChatListLifeStyle";
			this.cmbEasyChatListLifeStyle.Size = new global::System.Drawing.Size(120, 20);
			this.cmbEasyChatListLifeStyle.TabIndex = 33;
			this.rbEasyChatListLifeStyle.AutoSize = true;
			this.rbEasyChatListLifeStyle.Location = new global::System.Drawing.Point(545, 55);
			this.rbEasyChatListLifeStyle.Name = "rbEasyChatListLifeStyle";
			this.rbEasyChatListLifeStyle.Size = new global::System.Drawing.Size(14, 13);
			this.rbEasyChatListLifeStyle.TabIndex = 35;
			this.rbEasyChatListLifeStyle.TabStop = true;
			this.rbEasyChatListLifeStyle.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(738, 493);
			base.Controls.Add(this.nudEasyChatCount);
			base.Controls.Add(this.grpEasyChatList);
			base.Controls.Add(this.grpEasyChatPreview);
			base.Controls.Add(this.lblEasyChatCount);
			base.Controls.Add(this.lblHeldItemMail);
			base.Controls.Add(this.nudHeldItemMail);
			base.Controls.Add(this.btnAssign);
			base.Controls.Add(this.btnSave);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "HeldItemMailEditor";
			this.Text = "メール内容";
			((global::System.ComponentModel.ISupportInitialize)this.nudHeldItemMail).EndInit();
			this.grpEasyChatPreview.ResumeLayout(false);
			this.grpEasyChatPreview.PerformLayout();
			this.grpEasyChatList.ResumeLayout(false);
			this.grpEasyChatList.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudEasyChatCount).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x0400009D RID: 157
				private Button _btnSave;
		private NumericUpDown _nudHeldItemMail;
		private TextBox _txtEasyChatPreview9;
		private TextBox _txtEasyChatPreview6;
		private TextBox _txtEasyChatPreview3;
		private TextBox _txtEasyChatPreview8;
		private TextBox _txtEasyChatPreview5;
		private TextBox _txtEasyChatPreview2;
		private TextBox _txtEasyChatPreview7;
		private TextBox _txtEasyChatPreview4;
		private TextBox _txtEasyChatPreview1;
		private ComboBox _cmbEasyChatListPokemon1;
		private Button _btnAssign;
		private ComboBox _cmbEasyChatListPokemon2;
		private ComboBox _cmbEasyChatListMove2;
		private ComboBox _cmbEasyChatListMove1;
		private ComboBox _cmbEasyChatListBattle;
		private ComboBox _cmbEasyChatListTrainer;
		private ComboBox _cmbEasyChatListStatus;
		private ComboBox _cmbEasyChatListAction;
		private ComboBox _cmbEasyChatListCondition;
		private ComboBox _cmbEasyChatListEnding;
		private ComboBox _cmbEasyChatListSpeech;
		private ComboBox _cmbEasyChatListPeople;
		private ComboBox _cmbEasyChatListFeeling;
		private ComboBox _cmbEasyChatListVoice;
		private ComboBox _cmbEasyChatListGreeting;
		private NumericUpDown _nudEasyChatCount;
		private ComboBox _cmbEasyChatListTrendySaying;
		private ComboBox _cmbEasyChatListAdjective;
		private ComboBox _cmbEasyChatListMisc;
		private ComboBox _cmbEasyChatListHobby;
		private ComboBox _cmbEasyChatListEvent;
		private ComboBox _cmbEasyChatListTime;
		private ComboBox _cmbEasyChatListLifeStyle;
        private global::System.ComponentModel.IContainer components;
	}
}
