namespace BochiBochiEditor
{
	// Token: 0x02000012 RID: 18
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class InGameTradeEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x06000217 RID: 535 RVA: 0x00011514 File Offset: 0x0000F714
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000218 RID: 536 RVA: 0x00011564 File Offset: 0x0000F764
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.InGameTradeEditor));
			this.btnSave = new global::System.Windows.Forms.Button();
			this.lstInGameTradeList = new global::System.Windows.Forms.ListBox();
			this.cmbPokemonToGive = new global::System.Windows.Forms.ComboBox();
			this.grpPokemonToGive = new global::System.Windows.Forms.GroupBox();
			this.picPokemonToGive = new global::System.Windows.Forms.PictureBox();
			this.grpPokemonToReceive = new global::System.Windows.Forms.GroupBox();
			this.picPokemonToReceive = new global::System.Windows.Forms.PictureBox();
			this.cmbPokemonToReceive = new global::System.Windows.Forms.ComboBox();
			this.grpPokemonToReceiveDetail = new global::System.Windows.Forms.GroupBox();
			this.grpConditionsSheen = new global::System.Windows.Forms.GroupBox();
			this.nudConditionsCool = new global::System.Windows.Forms.NumericUpDown();
			this.lblConditionsCool = new global::System.Windows.Forms.Label();
			this.nudSheen = new global::System.Windows.Forms.NumericUpDown();
			this.lblConditionsBeauty = new global::System.Windows.Forms.Label();
			this.nudConditionsTough = new global::System.Windows.Forms.NumericUpDown();
			this.lblConditionsCute = new global::System.Windows.Forms.Label();
			this.nudConditionsSmart = new global::System.Windows.Forms.NumericUpDown();
			this.lblConditionsSmart = new global::System.Windows.Forms.Label();
			this.nudConditionsCute = new global::System.Windows.Forms.NumericUpDown();
			this.lblConditionsTough = new global::System.Windows.Forms.Label();
			this.nudConditionsBeauty = new global::System.Windows.Forms.NumericUpDown();
			this.lblSheen = new global::System.Windows.Forms.Label();
			this.nudHeldItemMail = new global::System.Windows.Forms.NumericUpDown();
			this.grpIndividualValue = new global::System.Windows.Forms.GroupBox();
			this.nudIndividualValueHp = new global::System.Windows.Forms.NumericUpDown();
			this.nudIndividualValueSpeed = new global::System.Windows.Forms.NumericUpDown();
			this.nudIndividualValueSpDefense = new global::System.Windows.Forms.NumericUpDown();
			this.nudIndividualValueSpAttack = new global::System.Windows.Forms.NumericUpDown();
			this.nudIndividualValueDefense = new global::System.Windows.Forms.NumericUpDown();
			this.nudIndividualValueAttack = new global::System.Windows.Forms.NumericUpDown();
			this.lblIndividualValueSpeed = new global::System.Windows.Forms.Label();
			this.lblIndividualValueSpDefense = new global::System.Windows.Forms.Label();
			this.lblIndividualValueSpAttack = new global::System.Windows.Forms.Label();
			this.lblIndividualValueDefense = new global::System.Windows.Forms.Label();
			this.lblIndividualValueAttack = new global::System.Windows.Forms.Label();
			this.lblIndividualValueHp = new global::System.Windows.Forms.Label();
			this.grpPersonalityValue = new global::System.Windows.Forms.GroupBox();
			this.grpPersonalityValueCalc = new global::System.Windows.Forms.GroupBox();
			this.rbPersonalityValueGenderUnknown = new global::System.Windows.Forms.RadioButton();
			this.rbPersonalityValueGenderFemale = new global::System.Windows.Forms.RadioButton();
			this.rbPersonalityValueGenderMale = new global::System.Windows.Forms.RadioButton();
			this.cmbPersonalityValueAbility = new global::System.Windows.Forms.ComboBox();
			this.cmbPersonalityValuePersonality = new global::System.Windows.Forms.ComboBox();
			this.lblPersonalityValuePersonality = new global::System.Windows.Forms.Label();
			this.lblPersonalityValueGender = new global::System.Windows.Forms.Label();
			this.lblPersonalityValueAbility = new global::System.Windows.Forms.Label();
			this.txtPersonalityValueDecimal = new global::System.Windows.Forms.TextBox();
			this.lblPersonalityValueHexa = new global::System.Windows.Forms.Label();
			this.btnChangePersonalityValue = new global::System.Windows.Forms.Button();
			this.txtPersonalityValueHexa = new global::System.Windows.Forms.TextBox();
			this.lblPersonalityValueDecimal = new global::System.Windows.Forms.Label();
			this.txtNickNameReadOnly = new global::System.Windows.Forms.TextBox();
			this.btnChangeNickName = new global::System.Windows.Forms.Button();
			this.txtNickNameInput = new global::System.Windows.Forms.TextBox();
			this.lblNickName = new global::System.Windows.Forms.Label();
			this.lblHeldItemMail = new global::System.Windows.Forms.Label();
			this.lblHeldItem = new global::System.Windows.Forms.Label();
			this.cmbHeldItem = new global::System.Windows.Forms.ComboBox();
			this.picHeldItem = new global::System.Windows.Forms.PictureBox();
			this.grpTrainerInfomation = new global::System.Windows.Forms.GroupBox();
			this.rbTrainerGenderFemale = new global::System.Windows.Forms.RadioButton();
			this.nudTrainerId2 = new global::System.Windows.Forms.NumericUpDown();
			this.rbTrainerGenderMale = new global::System.Windows.Forms.RadioButton();
			this.nudTrainerId1 = new global::System.Windows.Forms.NumericUpDown();
			this.txtTrainerNameReadOnly = new global::System.Windows.Forms.TextBox();
			this.btnChangeTrainerName = new global::System.Windows.Forms.Button();
			this.txtTrainerNameInput = new global::System.Windows.Forms.TextBox();
			this.lblTrainerGender = new global::System.Windows.Forms.Label();
			this.lblTrainerId2 = new global::System.Windows.Forms.Label();
			this.lblTrainerId1 = new global::System.Windows.Forms.Label();
			this.lblTrainerName = new global::System.Windows.Forms.Label();
			this.grpUnknownValue = new global::System.Windows.Forms.GroupBox();
			this.nudUnknownValue2 = new global::System.Windows.Forms.NumericUpDown();
			this.nudUnknownValue1 = new global::System.Windows.Forms.NumericUpDown();
			this.lblUnknownValue2 = new global::System.Windows.Forms.Label();
			this.lblUnknownValue1 = new global::System.Windows.Forms.Label();
			this.grpPokemonToGive.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonToGive).BeginInit();
			this.grpPokemonToReceive.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonToReceive).BeginInit();
			this.grpPokemonToReceiveDetail.SuspendLayout();
			this.grpConditionsSheen.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsCool).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudSheen).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsTough).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsSmart).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsCute).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsBeauty).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudHeldItemMail).BeginInit();
			this.grpIndividualValue.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueHp).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpeed).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpDefense).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpAttack).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueDefense).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueAttack).BeginInit();
			this.grpPersonalityValue.SuspendLayout();
			this.grpPersonalityValueCalc.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picHeldItem).BeginInit();
			this.grpTrainerInfomation.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerId2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerId1).BeginInit();
			this.grpUnknownValue.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue1).BeginInit();
			base.SuspendLayout();
			this.btnSave.Location = new global::System.Drawing.Point(12, 12);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(120, 23);
			this.btnSave.TabIndex = 0;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			this.lstInGameTradeList.FormattingEnabled = true;
			this.lstInGameTradeList.ItemHeight = 12;
			this.lstInGameTradeList.Location = new global::System.Drawing.Point(12, 42);
			this.lstInGameTradeList.Name = "lstInGameTradeList";
			this.lstInGameTradeList.Size = new global::System.Drawing.Size(120, 136);
			this.lstInGameTradeList.TabIndex = 1;
			this.cmbPokemonToGive.FormattingEnabled = true;
			this.cmbPokemonToGive.Location = new global::System.Drawing.Point(62, 28);
			this.cmbPokemonToGive.Name = "cmbPokemonToGive";
			this.cmbPokemonToGive.Size = new global::System.Drawing.Size(120, 20);
			this.cmbPokemonToGive.TabIndex = 2;
			this.grpPokemonToGive.Controls.Add(this.picPokemonToGive);
			this.grpPokemonToGive.Controls.Add(this.cmbPokemonToGive);
			this.grpPokemonToGive.Location = new global::System.Drawing.Point(246, 32);
			this.grpPokemonToGive.Name = "grpPokemonToGive";
			this.grpPokemonToGive.Size = new global::System.Drawing.Size(198, 60);
			this.grpPokemonToGive.TabIndex = 3;
			this.grpPokemonToGive.TabStop = false;
			this.grpPokemonToGive.Text = "ポケモン（自分）";
			this.picPokemonToGive.Location = new global::System.Drawing.Point(16, 18);
			this.picPokemonToGive.Name = "picPokemonToGive";
			this.picPokemonToGive.Size = new global::System.Drawing.Size(32, 32);
			this.picPokemonToGive.TabIndex = 0;
			this.picPokemonToGive.TabStop = false;
			this.grpPokemonToReceive.Controls.Add(this.picPokemonToReceive);
			this.grpPokemonToReceive.Controls.Add(this.cmbPokemonToReceive);
			this.grpPokemonToReceive.Location = new global::System.Drawing.Point(458, 32);
			this.grpPokemonToReceive.Name = "grpPokemonToReceive";
			this.grpPokemonToReceive.Size = new global::System.Drawing.Size(198, 60);
			this.grpPokemonToReceive.TabIndex = 4;
			this.grpPokemonToReceive.TabStop = false;
			this.grpPokemonToReceive.Text = "ポケモン（相手）";
			this.picPokemonToReceive.Location = new global::System.Drawing.Point(16, 18);
			this.picPokemonToReceive.Name = "picPokemonToReceive";
			this.picPokemonToReceive.Size = new global::System.Drawing.Size(32, 32);
			this.picPokemonToReceive.TabIndex = 0;
			this.picPokemonToReceive.TabStop = false;
			this.cmbPokemonToReceive.FormattingEnabled = true;
			this.cmbPokemonToReceive.Location = new global::System.Drawing.Point(62, 28);
			this.cmbPokemonToReceive.Name = "cmbPokemonToReceive";
			this.cmbPokemonToReceive.Size = new global::System.Drawing.Size(120, 20);
			this.cmbPokemonToReceive.TabIndex = 2;
			this.grpPokemonToReceiveDetail.Controls.Add(this.grpConditionsSheen);
			this.grpPokemonToReceiveDetail.Controls.Add(this.nudHeldItemMail);
			this.grpPokemonToReceiveDetail.Controls.Add(this.grpIndividualValue);
			this.grpPokemonToReceiveDetail.Controls.Add(this.grpPersonalityValue);
			this.grpPokemonToReceiveDetail.Controls.Add(this.txtNickNameReadOnly);
			this.grpPokemonToReceiveDetail.Controls.Add(this.btnChangeNickName);
			this.grpPokemonToReceiveDetail.Controls.Add(this.txtNickNameInput);
			this.grpPokemonToReceiveDetail.Controls.Add(this.lblNickName);
			this.grpPokemonToReceiveDetail.Controls.Add(this.lblHeldItemMail);
			this.grpPokemonToReceiveDetail.Controls.Add(this.lblHeldItem);
			this.grpPokemonToReceiveDetail.Controls.Add(this.cmbHeldItem);
			this.grpPokemonToReceiveDetail.Controls.Add(this.picHeldItem);
			this.grpPokemonToReceiveDetail.Location = new global::System.Drawing.Point(246, 106);
			this.grpPokemonToReceiveDetail.Name = "grpPokemonToReceiveDetail";
			this.grpPokemonToReceiveDetail.Size = new global::System.Drawing.Size(410, 354);
			this.grpPokemonToReceiveDetail.TabIndex = 5;
			this.grpPokemonToReceiveDetail.TabStop = false;
			this.grpPokemonToReceiveDetail.Text = "ポケモン（相手）詳細設定";
			this.grpConditionsSheen.Controls.Add(this.nudConditionsCool);
			this.grpConditionsSheen.Controls.Add(this.lblConditionsCool);
			this.grpConditionsSheen.Controls.Add(this.nudSheen);
			this.grpConditionsSheen.Controls.Add(this.lblConditionsBeauty);
			this.grpConditionsSheen.Controls.Add(this.nudConditionsTough);
			this.grpConditionsSheen.Controls.Add(this.lblConditionsCute);
			this.grpConditionsSheen.Controls.Add(this.nudConditionsSmart);
			this.grpConditionsSheen.Controls.Add(this.lblConditionsSmart);
			this.grpConditionsSheen.Controls.Add(this.nudConditionsCute);
			this.grpConditionsSheen.Controls.Add(this.lblConditionsTough);
			this.grpConditionsSheen.Controls.Add(this.nudConditionsBeauty);
			this.grpConditionsSheen.Controls.Add(this.lblSheen);
			this.grpConditionsSheen.Location = new global::System.Drawing.Point(260, 182);
			this.grpConditionsSheen.Name = "grpConditionsSheen";
			this.grpConditionsSheen.Size = new global::System.Drawing.Size(138, 160);
			this.grpConditionsSheen.TabIndex = 10;
			this.grpConditionsSheen.TabStop = false;
			this.grpConditionsSheen.Text = "コンディション / けづや";
			this.nudConditionsCool.Location = new global::System.Drawing.Point(74, 17);
			global::System.Windows.Forms.NumericUpDown nudConditionsCool = this.nudConditionsCool;
			int[] array = new int[4];
			array[0] = 31;
			nudConditionsCool.Maximum = new decimal(array);
			this.nudConditionsCool.Name = "nudConditionsCool";
			this.nudConditionsCool.Size = new global::System.Drawing.Size(48, 19);
			this.nudConditionsCool.TabIndex = 8;
			this.lblConditionsCool.AutoSize = true;
			this.lblConditionsCool.Font = new global::System.Drawing.Font("MS UI Gothic", 9f);
			this.lblConditionsCool.Location = new global::System.Drawing.Point(14, 21);
			this.lblConditionsCool.Name = "lblConditionsCool";
			this.lblConditionsCool.Size = new global::System.Drawing.Size(54, 12);
			this.lblConditionsCool.TabIndex = 7;
			this.lblConditionsCool.Text = "かっこよさ :";
			this.nudSheen.Location = new global::System.Drawing.Point(74, 132);
			global::System.Windows.Forms.NumericUpDown nudSheen = this.nudSheen;
			int[] array2 = new int[4];
			array2[0] = 31;
			nudSheen.Maximum = new decimal(array2);
			this.nudSheen.Name = "nudSheen";
			this.nudSheen.Size = new global::System.Drawing.Size(48, 19);
			this.nudSheen.TabIndex = 9;
			this.lblConditionsBeauty.AutoSize = true;
			this.lblConditionsBeauty.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblConditionsBeauty.Location = new global::System.Drawing.Point(14, 43);
			this.lblConditionsBeauty.Name = "lblConditionsBeauty";
			this.lblConditionsBeauty.Size = new global::System.Drawing.Size(50, 12);
			this.lblConditionsBeauty.TabIndex = 6;
			this.lblConditionsBeauty.Text = "うつくしさ :";
			this.nudConditionsTough.Location = new global::System.Drawing.Point(74, 109);
			global::System.Windows.Forms.NumericUpDown nudConditionsTough = this.nudConditionsTough;
			int[] array3 = new int[4];
			array3[0] = 31;
			nudConditionsTough.Maximum = new decimal(array3);
			this.nudConditionsTough.Name = "nudConditionsTough";
			this.nudConditionsTough.Size = new global::System.Drawing.Size(48, 19);
			this.nudConditionsTough.TabIndex = 10;
			this.lblConditionsCute.AutoSize = true;
			this.lblConditionsCute.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblConditionsCute.Location = new global::System.Drawing.Point(14, 66);
			this.lblConditionsCute.Name = "lblConditionsCute";
			this.lblConditionsCute.Size = new global::System.Drawing.Size(49, 12);
			this.lblConditionsCute.TabIndex = 5;
			this.lblConditionsCute.Text = "かわいさ :";
			this.nudConditionsSmart.Location = new global::System.Drawing.Point(74, 86);
			global::System.Windows.Forms.NumericUpDown nudConditionsSmart = this.nudConditionsSmart;
			int[] array4 = new int[4];
			array4[0] = 31;
			nudConditionsSmart.Maximum = new decimal(array4);
			this.nudConditionsSmart.Name = "nudConditionsSmart";
			this.nudConditionsSmart.Size = new global::System.Drawing.Size(48, 19);
			this.nudConditionsSmart.TabIndex = 11;
			this.lblConditionsSmart.AutoSize = true;
			this.lblConditionsSmart.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblConditionsSmart.Location = new global::System.Drawing.Point(14, 89);
			this.lblConditionsSmart.Name = "lblConditionsSmart";
			this.lblConditionsSmart.Size = new global::System.Drawing.Size(46, 12);
			this.lblConditionsSmart.TabIndex = 4;
			this.lblConditionsSmart.Text = "かしこさ :";
			this.nudConditionsCute.Location = new global::System.Drawing.Point(74, 63);
			global::System.Windows.Forms.NumericUpDown nudConditionsCute = this.nudConditionsCute;
			int[] array5 = new int[4];
			array5[0] = 31;
			nudConditionsCute.Maximum = new decimal(array5);
			this.nudConditionsCute.Name = "nudConditionsCute";
			this.nudConditionsCute.Size = new global::System.Drawing.Size(48, 19);
			this.nudConditionsCute.TabIndex = 12;
			this.lblConditionsTough.AutoSize = true;
			this.lblConditionsTough.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblConditionsTough.Location = new global::System.Drawing.Point(14, 112);
			this.lblConditionsTough.Name = "lblConditionsTough";
			this.lblConditionsTough.Size = new global::System.Drawing.Size(52, 12);
			this.lblConditionsTough.TabIndex = 3;
			this.lblConditionsTough.Text = "たくましさ :";
			this.nudConditionsBeauty.Location = new global::System.Drawing.Point(74, 40);
			global::System.Windows.Forms.NumericUpDown nudConditionsBeauty = this.nudConditionsBeauty;
			int[] array6 = new int[4];
			array6[0] = 31;
			nudConditionsBeauty.Maximum = new decimal(array6);
			this.nudConditionsBeauty.Name = "nudConditionsBeauty";
			this.nudConditionsBeauty.Size = new global::System.Drawing.Size(48, 19);
			this.nudConditionsBeauty.TabIndex = 13;
			this.lblSheen.AutoSize = true;
			this.lblSheen.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblSheen.Location = new global::System.Drawing.Point(14, 135);
			this.lblSheen.Name = "lblSheen";
			this.lblSheen.Size = new global::System.Drawing.Size(41, 12);
			this.lblSheen.TabIndex = 2;
			this.lblSheen.Text = "けづや :";
			this.nudHeldItemMail.Location = new global::System.Drawing.Point(102, 120);
			global::System.Windows.Forms.NumericUpDown nudHeldItemMail = this.nudHeldItemMail;
			int[] array7 = new int[4];
			array7[0] = 255;
			nudHeldItemMail.Maximum = new decimal(array7);
			this.nudHeldItemMail.Name = "nudHeldItemMail";
			this.nudHeldItemMail.Size = new global::System.Drawing.Size(48, 19);
			this.nudHeldItemMail.TabIndex = 9;
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueHp);
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueSpeed);
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueSpDefense);
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueSpAttack);
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueDefense);
			this.grpIndividualValue.Controls.Add(this.nudIndividualValueAttack);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueSpeed);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueSpDefense);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueSpAttack);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueDefense);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueAttack);
			this.grpIndividualValue.Controls.Add(this.lblIndividualValueHp);
			this.grpIndividualValue.Location = new global::System.Drawing.Point(260, 16);
			this.grpIndividualValue.Name = "grpIndividualValue";
			this.grpIndividualValue.Size = new global::System.Drawing.Size(138, 160);
			this.grpIndividualValue.TabIndex = 8;
			this.grpIndividualValue.TabStop = false;
			this.grpIndividualValue.Text = "個体値";
			this.nudIndividualValueHp.Location = new global::System.Drawing.Point(74, 16);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueHp = this.nudIndividualValueHp;
			int[] array8 = new int[4];
			array8[0] = 31;
			nudIndividualValueHp.Maximum = new decimal(array8);
			this.nudIndividualValueHp.Name = "nudIndividualValueHp";
			this.nudIndividualValueHp.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueHp.TabIndex = 8;
			this.nudIndividualValueSpeed.Location = new global::System.Drawing.Point(74, 131);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueSpeed = this.nudIndividualValueSpeed;
			int[] array9 = new int[4];
			array9[0] = 31;
			nudIndividualValueSpeed.Maximum = new decimal(array9);
			this.nudIndividualValueSpeed.Name = "nudIndividualValueSpeed";
			this.nudIndividualValueSpeed.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueSpeed.TabIndex = 9;
			this.nudIndividualValueSpDefense.Location = new global::System.Drawing.Point(74, 108);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueSpDefense = this.nudIndividualValueSpDefense;
			int[] array10 = new int[4];
			array10[0] = 31;
			nudIndividualValueSpDefense.Maximum = new decimal(array10);
			this.nudIndividualValueSpDefense.Name = "nudIndividualValueSpDefense";
			this.nudIndividualValueSpDefense.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueSpDefense.TabIndex = 10;
			this.nudIndividualValueSpAttack.Location = new global::System.Drawing.Point(74, 85);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueSpAttack = this.nudIndividualValueSpAttack;
			int[] array11 = new int[4];
			array11[0] = 31;
			nudIndividualValueSpAttack.Maximum = new decimal(array11);
			this.nudIndividualValueSpAttack.Name = "nudIndividualValueSpAttack";
			this.nudIndividualValueSpAttack.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueSpAttack.TabIndex = 11;
			this.nudIndividualValueDefense.Location = new global::System.Drawing.Point(74, 62);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueDefense = this.nudIndividualValueDefense;
			int[] array12 = new int[4];
			array12[0] = 31;
			nudIndividualValueDefense.Maximum = new decimal(array12);
			this.nudIndividualValueDefense.Name = "nudIndividualValueDefense";
			this.nudIndividualValueDefense.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueDefense.TabIndex = 12;
			this.nudIndividualValueAttack.Location = new global::System.Drawing.Point(74, 39);
			global::System.Windows.Forms.NumericUpDown nudIndividualValueAttack = this.nudIndividualValueAttack;
			int[] array13 = new int[4];
			array13[0] = 31;
			nudIndividualValueAttack.Maximum = new decimal(array13);
			this.nudIndividualValueAttack.Name = "nudIndividualValueAttack";
			this.nudIndividualValueAttack.Size = new global::System.Drawing.Size(48, 19);
			this.nudIndividualValueAttack.TabIndex = 13;
			this.lblIndividualValueSpeed.AutoSize = true;
			this.lblIndividualValueSpeed.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblIndividualValueSpeed.Location = new global::System.Drawing.Point(14, 134);
			this.lblIndividualValueSpeed.Name = "lblIndividualValueSpeed";
			this.lblIndividualValueSpeed.Size = new global::System.Drawing.Size(49, 12);
			this.lblIndividualValueSpeed.TabIndex = 2;
			this.lblIndividualValueSpeed.Text = "すばやさ :";
			this.lblIndividualValueSpDefense.AutoSize = true;
			this.lblIndividualValueSpDefense.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblIndividualValueSpDefense.Location = new global::System.Drawing.Point(14, 111);
			this.lblIndividualValueSpDefense.Name = "lblIndividualValueSpDefense";
			this.lblIndividualValueSpDefense.Size = new global::System.Drawing.Size(42, 12);
			this.lblIndividualValueSpDefense.TabIndex = 3;
			this.lblIndividualValueSpDefense.Text = "とくぼう :";
			this.lblIndividualValueSpAttack.AutoSize = true;
			this.lblIndividualValueSpAttack.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblIndividualValueSpAttack.Location = new global::System.Drawing.Point(14, 88);
			this.lblIndividualValueSpAttack.Name = "lblIndividualValueSpAttack";
			this.lblIndividualValueSpAttack.Size = new global::System.Drawing.Size(40, 12);
			this.lblIndividualValueSpAttack.TabIndex = 4;
			this.lblIndividualValueSpAttack.Text = "とくこう :";
			this.lblIndividualValueDefense.AutoSize = true;
			this.lblIndividualValueDefense.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblIndividualValueDefense.Location = new global::System.Drawing.Point(14, 65);
			this.lblIndividualValueDefense.Name = "lblIndividualValueDefense";
			this.lblIndividualValueDefense.Size = new global::System.Drawing.Size(45, 12);
			this.lblIndividualValueDefense.TabIndex = 5;
			this.lblIndividualValueDefense.Text = "ぼうぎょ :";
			this.lblIndividualValueAttack.AutoSize = true;
			this.lblIndividualValueAttack.Font = new global::System.Drawing.Font("MS UI Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 128);
			this.lblIndividualValueAttack.Location = new global::System.Drawing.Point(14, 42);
			this.lblIndividualValueAttack.Name = "lblIndividualValueAttack";
			this.lblIndividualValueAttack.Size = new global::System.Drawing.Size(45, 12);
			this.lblIndividualValueAttack.TabIndex = 6;
			this.lblIndividualValueAttack.Text = "こうげき :";
			this.lblIndividualValueHp.AutoSize = true;
			this.lblIndividualValueHp.Font = new global::System.Drawing.Font("MS UI Gothic", 9f);
			this.lblIndividualValueHp.Location = new global::System.Drawing.Point(14, 20);
			this.lblIndividualValueHp.Name = "lblIndividualValueHp";
			this.lblIndividualValueHp.Size = new global::System.Drawing.Size(26, 12);
			this.lblIndividualValueHp.TabIndex = 7;
			this.lblIndividualValueHp.Text = "HP :";
			this.grpPersonalityValue.Controls.Add(this.grpPersonalityValueCalc);
			this.grpPersonalityValue.Controls.Add(this.txtPersonalityValueDecimal);
			this.grpPersonalityValue.Controls.Add(this.lblPersonalityValueHexa);
			this.grpPersonalityValue.Controls.Add(this.btnChangePersonalityValue);
			this.grpPersonalityValue.Controls.Add(this.txtPersonalityValueHexa);
			this.grpPersonalityValue.Controls.Add(this.lblPersonalityValueDecimal);
			this.grpPersonalityValue.Location = new global::System.Drawing.Point(12, 148);
			this.grpPersonalityValue.Name = "grpPersonalityValue";
			this.grpPersonalityValue.Size = new global::System.Drawing.Size(238, 194);
			this.grpPersonalityValue.TabIndex = 7;
			this.grpPersonalityValue.TabStop = false;
			this.grpPersonalityValue.Text = "性格値";
			this.grpPersonalityValueCalc.Controls.Add(this.rbPersonalityValueGenderUnknown);
			this.grpPersonalityValueCalc.Controls.Add(this.rbPersonalityValueGenderFemale);
			this.grpPersonalityValueCalc.Controls.Add(this.rbPersonalityValueGenderMale);
			this.grpPersonalityValueCalc.Controls.Add(this.cmbPersonalityValueAbility);
			this.grpPersonalityValueCalc.Controls.Add(this.cmbPersonalityValuePersonality);
			this.grpPersonalityValueCalc.Controls.Add(this.lblPersonalityValuePersonality);
			this.grpPersonalityValueCalc.Controls.Add(this.lblPersonalityValueGender);
			this.grpPersonalityValueCalc.Controls.Add(this.lblPersonalityValueAbility);
			this.grpPersonalityValueCalc.Location = new global::System.Drawing.Point(12, 90);
			this.grpPersonalityValueCalc.Name = "grpPersonalityValueCalc";
			this.grpPersonalityValueCalc.Size = new global::System.Drawing.Size(214, 92);
			this.grpPersonalityValueCalc.TabIndex = 7;
			this.grpPersonalityValueCalc.TabStop = false;
			this.grpPersonalityValueCalc.Text = "計算結果";
			this.rbPersonalityValueGenderUnknown.AutoSize = true;
			this.rbPersonalityValueGenderUnknown.Enabled = false;
			this.rbPersonalityValueGenderUnknown.Location = new global::System.Drawing.Point(160, 42);
			this.rbPersonalityValueGenderUnknown.Name = "rbPersonalityValueGenderUnknown";
			this.rbPersonalityValueGenderUnknown.Size = new global::System.Drawing.Size(35, 16);
			this.rbPersonalityValueGenderUnknown.TabIndex = 9;
			this.rbPersonalityValueGenderUnknown.TabStop = true;
			this.rbPersonalityValueGenderUnknown.Text = "？";
			this.rbPersonalityValueGenderUnknown.UseVisualStyleBackColor = true;
			this.rbPersonalityValueGenderFemale.AutoSize = true;
			this.rbPersonalityValueGenderFemale.Enabled = false;
			this.rbPersonalityValueGenderFemale.Location = new global::System.Drawing.Point(120, 42);
			this.rbPersonalityValueGenderFemale.Name = "rbPersonalityValueGenderFemale";
			this.rbPersonalityValueGenderFemale.Size = new global::System.Drawing.Size(35, 16);
			this.rbPersonalityValueGenderFemale.TabIndex = 8;
			this.rbPersonalityValueGenderFemale.TabStop = true;
			this.rbPersonalityValueGenderFemale.Text = "♀";
			this.rbPersonalityValueGenderFemale.UseVisualStyleBackColor = true;
			this.rbPersonalityValueGenderMale.AutoSize = true;
			this.rbPersonalityValueGenderMale.Enabled = false;
			this.rbPersonalityValueGenderMale.Location = new global::System.Drawing.Point(80, 42);
			this.rbPersonalityValueGenderMale.Name = "rbPersonalityValueGenderMale";
			this.rbPersonalityValueGenderMale.Size = new global::System.Drawing.Size(35, 16);
			this.rbPersonalityValueGenderMale.TabIndex = 8;
			this.rbPersonalityValueGenderMale.TabStop = true;
			this.rbPersonalityValueGenderMale.Text = "♂";
			this.rbPersonalityValueGenderMale.UseVisualStyleBackColor = true;
			this.cmbPersonalityValueAbility.Enabled = false;
			this.cmbPersonalityValueAbility.FormattingEnabled = true;
			this.cmbPersonalityValueAbility.Location = new global::System.Drawing.Point(78, 62);
			this.cmbPersonalityValueAbility.Name = "cmbPersonalityValueAbility";
			this.cmbPersonalityValueAbility.Size = new global::System.Drawing.Size(120, 20);
			this.cmbPersonalityValueAbility.TabIndex = 7;
			this.cmbPersonalityValuePersonality.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbPersonalityValuePersonality.Enabled = false;
			this.cmbPersonalityValuePersonality.FormattingEnabled = true;
			this.cmbPersonalityValuePersonality.Location = new global::System.Drawing.Point(78, 17);
			this.cmbPersonalityValuePersonality.Name = "cmbPersonalityValuePersonality";
			this.cmbPersonalityValuePersonality.Size = new global::System.Drawing.Size(120, 20);
			this.cmbPersonalityValuePersonality.TabIndex = 7;
			this.lblPersonalityValuePersonality.AutoSize = true;
			this.lblPersonalityValuePersonality.Location = new global::System.Drawing.Point(12, 21);
			this.lblPersonalityValuePersonality.Name = "lblPersonalityValuePersonality";
			this.lblPersonalityValuePersonality.Size = new global::System.Drawing.Size(35, 12);
			this.lblPersonalityValuePersonality.TabIndex = 6;
			this.lblPersonalityValuePersonality.Text = "性格 :";
			this.lblPersonalityValueGender.AutoSize = true;
			this.lblPersonalityValueGender.Location = new global::System.Drawing.Point(12, 44);
			this.lblPersonalityValueGender.Name = "lblPersonalityValueGender";
			this.lblPersonalityValueGender.Size = new global::System.Drawing.Size(35, 12);
			this.lblPersonalityValueGender.TabIndex = 6;
			this.lblPersonalityValueGender.Text = "性別 :";
			this.lblPersonalityValueAbility.AutoSize = true;
			this.lblPersonalityValueAbility.Location = new global::System.Drawing.Point(12, 66);
			this.lblPersonalityValueAbility.Name = "lblPersonalityValueAbility";
			this.lblPersonalityValueAbility.Size = new global::System.Drawing.Size(35, 12);
			this.lblPersonalityValueAbility.TabIndex = 6;
			this.lblPersonalityValueAbility.Text = "特性 :";
			this.txtPersonalityValueDecimal.Location = new global::System.Drawing.Point(90, 43);
			this.txtPersonalityValueDecimal.Name = "txtPersonalityValueDecimal";
			this.txtPersonalityValueDecimal.Size = new global::System.Drawing.Size(120, 19);
			this.txtPersonalityValueDecimal.TabIndex = 5;
			this.lblPersonalityValueHexa.AutoSize = true;
			this.lblPersonalityValueHexa.Location = new global::System.Drawing.Point(14, 24);
			this.lblPersonalityValueHexa.Name = "lblPersonalityValueHexa";
			this.lblPersonalityValueHexa.Size = new global::System.Drawing.Size(47, 12);
			this.lblPersonalityValueHexa.TabIndex = 6;
			this.lblPersonalityValueHexa.Text = "16進数 :";
			this.btnChangePersonalityValue.Location = new global::System.Drawing.Point(90, 66);
			this.btnChangePersonalityValue.Name = "btnChangePersonalityValue";
			this.btnChangePersonalityValue.Size = new global::System.Drawing.Size(120, 23);
			this.btnChangePersonalityValue.TabIndex = 4;
			this.btnChangePersonalityValue.Text = "変更を反映";
			this.btnChangePersonalityValue.UseVisualStyleBackColor = true;
			this.txtPersonalityValueHexa.Location = new global::System.Drawing.Point(90, 20);
			this.txtPersonalityValueHexa.Name = "txtPersonalityValueHexa";
			this.txtPersonalityValueHexa.ReadOnly = true;
			this.txtPersonalityValueHexa.Size = new global::System.Drawing.Size(120, 19);
			this.txtPersonalityValueHexa.TabIndex = 5;
			this.lblPersonalityValueDecimal.AutoSize = true;
			this.lblPersonalityValueDecimal.Location = new global::System.Drawing.Point(14, 47);
			this.lblPersonalityValueDecimal.Name = "lblPersonalityValueDecimal";
			this.lblPersonalityValueDecimal.Size = new global::System.Drawing.Size(47, 12);
			this.lblPersonalityValueDecimal.TabIndex = 6;
			this.lblPersonalityValueDecimal.Text = "10進数 :";
			this.txtNickNameReadOnly.Location = new global::System.Drawing.Point(102, 22);
			this.txtNickNameReadOnly.Name = "txtNickNameReadOnly";
			this.txtNickNameReadOnly.ReadOnly = true;
			this.txtNickNameReadOnly.Size = new global::System.Drawing.Size(120, 19);
			this.txtNickNameReadOnly.TabIndex = 5;
			this.btnChangeNickName.Location = new global::System.Drawing.Point(102, 68);
			this.btnChangeNickName.Name = "btnChangeNickName";
			this.btnChangeNickName.Size = new global::System.Drawing.Size(120, 23);
			this.btnChangeNickName.TabIndex = 4;
			this.btnChangeNickName.Text = "名前を変更";
			this.btnChangeNickName.UseVisualStyleBackColor = true;
			this.txtNickNameInput.Location = new global::System.Drawing.Point(102, 45);
			this.txtNickNameInput.Name = "txtNickNameInput";
			this.txtNickNameInput.Size = new global::System.Drawing.Size(120, 19);
			this.txtNickNameInput.TabIndex = 3;
			this.lblNickName.AutoSize = true;
			this.lblNickName.Location = new global::System.Drawing.Point(18, 26);
			this.lblNickName.Name = "lblNickName";
			this.lblNickName.Size = new global::System.Drawing.Size(65, 12);
			this.lblNickName.TabIndex = 2;
			this.lblNickName.Text = "ニックネーム :";
			this.lblHeldItemMail.AutoSize = true;
			this.lblHeldItemMail.Location = new global::System.Drawing.Point(18, 124);
			this.lblHeldItemMail.Name = "lblHeldItemMail";
			this.lblHeldItemMail.Size = new global::System.Drawing.Size(74, 12);
			this.lblHeldItemMail.TabIndex = 2;
			this.lblHeldItemMail.Text = "メール内容ID :";
			this.lblHeldItem.AutoSize = true;
			this.lblHeldItem.Location = new global::System.Drawing.Point(18, 100);
			this.lblHeldItem.Name = "lblHeldItem";
			this.lblHeldItem.Size = new global::System.Drawing.Size(48, 12);
			this.lblHeldItem.TabIndex = 2;
			this.lblHeldItem.Text = "アイテム :";
			this.cmbHeldItem.FormattingEnabled = true;
			this.cmbHeldItem.Location = new global::System.Drawing.Point(102, 95);
			this.cmbHeldItem.Name = "cmbHeldItem";
			this.cmbHeldItem.Size = new global::System.Drawing.Size(120, 20);
			this.cmbHeldItem.TabIndex = 1;
			this.picHeldItem.Location = new global::System.Drawing.Point(71, 93);
			this.picHeldItem.Name = "picHeldItem";
			this.picHeldItem.Size = new global::System.Drawing.Size(24, 24);
			this.picHeldItem.TabIndex = 0;
			this.picHeldItem.TabStop = false;
			this.grpTrainerInfomation.Controls.Add(this.rbTrainerGenderFemale);
			this.grpTrainerInfomation.Controls.Add(this.nudTrainerId2);
			this.grpTrainerInfomation.Controls.Add(this.rbTrainerGenderMale);
			this.grpTrainerInfomation.Controls.Add(this.nudTrainerId1);
			this.grpTrainerInfomation.Controls.Add(this.txtTrainerNameReadOnly);
			this.grpTrainerInfomation.Controls.Add(this.btnChangeTrainerName);
			this.grpTrainerInfomation.Controls.Add(this.txtTrainerNameInput);
			this.grpTrainerInfomation.Controls.Add(this.lblTrainerGender);
			this.grpTrainerInfomation.Controls.Add(this.lblTrainerId2);
			this.grpTrainerInfomation.Controls.Add(this.lblTrainerId1);
			this.grpTrainerInfomation.Controls.Add(this.lblTrainerName);
			this.grpTrainerInfomation.Location = new global::System.Drawing.Point(12, 192);
			this.grpTrainerInfomation.Name = "grpTrainerInfomation";
			this.grpTrainerInfomation.Size = new global::System.Drawing.Size(222, 168);
			this.grpTrainerInfomation.TabIndex = 11;
			this.grpTrainerInfomation.TabStop = false;
			this.grpTrainerInfomation.Text = "トレーナー情報";
			this.rbTrainerGenderFemale.AutoSize = true;
			this.rbTrainerGenderFemale.Location = new global::System.Drawing.Point(138, 142);
			this.rbTrainerGenderFemale.Name = "rbTrainerGenderFemale";
			this.rbTrainerGenderFemale.Size = new global::System.Drawing.Size(35, 16);
			this.rbTrainerGenderFemale.TabIndex = 8;
			this.rbTrainerGenderFemale.TabStop = true;
			this.rbTrainerGenderFemale.Text = "♀";
			this.rbTrainerGenderFemale.UseVisualStyleBackColor = true;
			this.nudTrainerId2.Location = new global::System.Drawing.Point(90, 116);
			global::System.Windows.Forms.NumericUpDown nudTrainerId = this.nudTrainerId2;
			int[] array14 = new int[4];
			array14[0] = 65535;
			nudTrainerId.Maximum = new decimal(array14);
			this.nudTrainerId2.Name = "nudTrainerId2";
			this.nudTrainerId2.Size = new global::System.Drawing.Size(84, 19);
			this.nudTrainerId2.TabIndex = 9;
			this.rbTrainerGenderMale.AutoSize = true;
			this.rbTrainerGenderMale.Location = new global::System.Drawing.Point(94, 142);
			this.rbTrainerGenderMale.Name = "rbTrainerGenderMale";
			this.rbTrainerGenderMale.Size = new global::System.Drawing.Size(35, 16);
			this.rbTrainerGenderMale.TabIndex = 8;
			this.rbTrainerGenderMale.TabStop = true;
			this.rbTrainerGenderMale.Text = "♂";
			this.rbTrainerGenderMale.UseVisualStyleBackColor = true;
			this.nudTrainerId1.Location = new global::System.Drawing.Point(90, 93);
			global::System.Windows.Forms.NumericUpDown nudTrainerId2 = this.nudTrainerId1;
			int[] array15 = new int[4];
			array15[0] = 65535;
			nudTrainerId2.Maximum = new decimal(array15);
			this.nudTrainerId1.Name = "nudTrainerId1";
			this.nudTrainerId1.Size = new global::System.Drawing.Size(84, 19);
			this.nudTrainerId1.TabIndex = 9;
			this.txtTrainerNameReadOnly.Location = new global::System.Drawing.Point(90, 20);
			this.txtTrainerNameReadOnly.Name = "txtTrainerNameReadOnly";
			this.txtTrainerNameReadOnly.ReadOnly = true;
			this.txtTrainerNameReadOnly.Size = new global::System.Drawing.Size(120, 19);
			this.txtTrainerNameReadOnly.TabIndex = 8;
			this.btnChangeTrainerName.Location = new global::System.Drawing.Point(90, 66);
			this.btnChangeTrainerName.Name = "btnChangeTrainerName";
			this.btnChangeTrainerName.Size = new global::System.Drawing.Size(120, 23);
			this.btnChangeTrainerName.TabIndex = 7;
			this.btnChangeTrainerName.Text = "名前を変更";
			this.btnChangeTrainerName.UseVisualStyleBackColor = true;
			this.txtTrainerNameInput.Location = new global::System.Drawing.Point(90, 43);
			this.txtTrainerNameInput.Name = "txtTrainerNameInput";
			this.txtTrainerNameInput.Size = new global::System.Drawing.Size(120, 19);
			this.txtTrainerNameInput.TabIndex = 6;
			this.lblTrainerGender.AutoSize = true;
			this.lblTrainerGender.Location = new global::System.Drawing.Point(14, 143);
			this.lblTrainerGender.Name = "lblTrainerGender";
			this.lblTrainerGender.Size = new global::System.Drawing.Size(35, 12);
			this.lblTrainerGender.TabIndex = 3;
			this.lblTrainerGender.Text = "性別 :";
			this.lblTrainerId2.AutoSize = true;
			this.lblTrainerId2.Location = new global::System.Drawing.Point(14, 120);
			this.lblTrainerId2.Name = "lblTrainerId2";
			this.lblTrainerId2.Size = new global::System.Drawing.Size(34, 12);
			this.lblTrainerId2.TabIndex = 3;
			this.lblTrainerId2.Text = "裏ID :";
			this.lblTrainerId1.AutoSize = true;
			this.lblTrainerId1.Location = new global::System.Drawing.Point(14, 97);
			this.lblTrainerId1.Name = "lblTrainerId1";
			this.lblTrainerId1.Size = new global::System.Drawing.Size(34, 12);
			this.lblTrainerId1.TabIndex = 3;
			this.lblTrainerId1.Text = "表ID :";
			this.lblTrainerName.AutoSize = true;
			this.lblTrainerName.Location = new global::System.Drawing.Point(14, 24);
			this.lblTrainerName.Name = "lblTrainerName";
			this.lblTrainerName.Size = new global::System.Drawing.Size(70, 12);
			this.lblTrainerName.TabIndex = 3;
			this.lblTrainerName.Text = "トレーナー名 :";
			this.grpUnknownValue.Controls.Add(this.nudUnknownValue2);
			this.grpUnknownValue.Controls.Add(this.nudUnknownValue1);
			this.grpUnknownValue.Controls.Add(this.lblUnknownValue2);
			this.grpUnknownValue.Controls.Add(this.lblUnknownValue1);
			this.grpUnknownValue.Location = new global::System.Drawing.Point(12, 370);
			this.grpUnknownValue.Name = "grpUnknownValue";
			this.grpUnknownValue.Size = new global::System.Drawing.Size(158, 78);
			this.grpUnknownValue.TabIndex = 12;
			this.grpUnknownValue.TabStop = false;
			this.grpUnknownValue.Text = "不明値";
			this.nudUnknownValue2.Location = new global::System.Drawing.Point(90, 45);
			global::System.Windows.Forms.NumericUpDown nudUnknownValue = this.nudUnknownValue2;
			int[] array16 = new int[4];
			array16[0] = 255;
			nudUnknownValue.Maximum = new decimal(array16);
			this.nudUnknownValue2.Name = "nudUnknownValue2";
			this.nudUnknownValue2.Size = new global::System.Drawing.Size(48, 19);
			this.nudUnknownValue2.TabIndex = 1;
			this.nudUnknownValue1.Location = new global::System.Drawing.Point(90, 22);
			global::System.Windows.Forms.NumericUpDown nudUnknownValue2 = this.nudUnknownValue1;
			int[] array17 = new int[4];
			array17[0] = 255;
			nudUnknownValue2.Maximum = new decimal(array17);
			this.nudUnknownValue1.Name = "nudUnknownValue1";
			this.nudUnknownValue1.Size = new global::System.Drawing.Size(48, 19);
			this.nudUnknownValue1.TabIndex = 1;
			this.lblUnknownValue2.AutoSize = true;
			this.lblUnknownValue2.Location = new global::System.Drawing.Point(14, 48);
			this.lblUnknownValue2.Name = "lblUnknownValue2";
			this.lblUnknownValue2.Size = new global::System.Drawing.Size(73, 12);
			this.lblUnknownValue2.TabIndex = 0;
			this.lblUnknownValue2.Text = "不明値0x3B :";
			this.lblUnknownValue1.AutoSize = true;
			this.lblUnknownValue1.Location = new global::System.Drawing.Point(14, 26);
			this.lblUnknownValue1.Name = "lblUnknownValue1";
			this.lblUnknownValue1.Size = new global::System.Drawing.Size(73, 12);
			this.lblUnknownValue1.TabIndex = 0;
			this.lblUnknownValue1.Text = "不明値0x3A :";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(670, 473);
			base.Controls.Add(this.grpUnknownValue);
			base.Controls.Add(this.grpPokemonToReceiveDetail);
			base.Controls.Add(this.grpTrainerInfomation);
			base.Controls.Add(this.grpPokemonToReceive);
			base.Controls.Add(this.grpPokemonToGive);
			base.Controls.Add(this.lstInGameTradeList);
			base.Controls.Add(this.btnSave);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "InGameTradeEditor";
			this.Text = "NPCポケモン交換";
			this.grpPokemonToGive.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonToGive).EndInit();
			this.grpPokemonToReceive.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonToReceive).EndInit();
			this.grpPokemonToReceiveDetail.ResumeLayout(false);
			this.grpPokemonToReceiveDetail.PerformLayout();
			this.grpConditionsSheen.ResumeLayout(false);
			this.grpConditionsSheen.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsCool).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudSheen).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsTough).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsSmart).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsCute).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudConditionsBeauty).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudHeldItemMail).EndInit();
			this.grpIndividualValue.ResumeLayout(false);
			this.grpIndividualValue.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueHp).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpeed).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpDefense).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueSpAttack).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueDefense).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIndividualValueAttack).EndInit();
			this.grpPersonalityValue.ResumeLayout(false);
			this.grpPersonalityValue.PerformLayout();
			this.grpPersonalityValueCalc.ResumeLayout(false);
			this.grpPersonalityValueCalc.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picHeldItem).EndInit();
			this.grpTrainerInfomation.ResumeLayout(false);
			this.grpTrainerInfomation.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerId2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerId1).EndInit();
			this.grpUnknownValue.ResumeLayout(false);
			this.grpUnknownValue.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue1).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x0400011D RID: 285
				private Button _btnSave;
		private ListBox _lstInGameTradeList;
		private ComboBox _cmbPokemonToGive;
		private ComboBox _cmbPokemonToReceive;
		private Button _btnChangeNickName;
		private ComboBox _cmbHeldItem;
		private Button _btnChangePersonalityValue;
		private NumericUpDown _nudHeldItemMail;
		private NumericUpDown _nudIndividualValueHp;
		private NumericUpDown _nudIndividualValueSpeed;
		private NumericUpDown _nudIndividualValueSpDefense;
		private NumericUpDown _nudIndividualValueSpAttack;
		private NumericUpDown _nudIndividualValueDefense;
		private NumericUpDown _nudIndividualValueAttack;
		private NumericUpDown _nudConditionsCool;
		private NumericUpDown _nudSheen;
		private NumericUpDown _nudConditionsTough;
		private NumericUpDown _nudConditionsSmart;
		private NumericUpDown _nudConditionsCute;
		private NumericUpDown _nudConditionsBeauty;
		private NumericUpDown _nudTrainerId2;
		private NumericUpDown _nudTrainerId1;
		private Button _btnChangeTrainerName;
		private RadioButton _rbTrainerGenderFemale;
		private RadioButton _rbTrainerGenderMale;
		private NumericUpDown _nudUnknownValue2;
		private NumericUpDown _nudUnknownValue1;
        private global::System.ComponentModel.IContainer components;
	}
}
