namespace BochiBochiEditor
{
	// Token: 0x02000018 RID: 24
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class ItemEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x0600032C RID: 812 RVA: 0x00018314 File Offset: 0x00016514
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600032D RID: 813 RVA: 0x00018364 File Offset: 0x00016564
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.ItemEditor));
			this.btnSave = new global::System.Windows.Forms.Button();
			this.grpItemName = new global::System.Windows.Forms.GroupBox();
			this.btnChangeItemName = new global::System.Windows.Forms.Button();
			this.txtItemName = new global::System.Windows.Forms.TextBox();
			this.cmbItemName = new global::System.Windows.Forms.ComboBox();
			this.grpItemSprite = new global::System.Windows.Forms.GroupBox();
			this.rbItemSpritePalleteAddress = new global::System.Windows.Forms.RadioButton();
			this.rbItemSpriteImageAddress = new global::System.Windows.Forms.RadioButton();
			this.txtItemSpriteImportAddress = new global::System.Windows.Forms.TextBox();
			this.btnItemSpriteImport = new global::System.Windows.Forms.Button();
			this.btnItemSpriteExport = new global::System.Windows.Forms.Button();
			this.btnChangeItemSpriteAddress = new global::System.Windows.Forms.Button();
			this.txtItemSpritePalleteAddress = new global::System.Windows.Forms.TextBox();
			this.txtItemSpriteImageAddress = new global::System.Windows.Forms.TextBox();
			this.picItemSprite = new global::System.Windows.Forms.PictureBox();
			this.grpItemDescription = new global::System.Windows.Forms.GroupBox();
			this.txtItemDescription = new global::System.Windows.Forms.TextBox();
			this.btnChangeItemDescription = new global::System.Windows.Forms.Button();
			this.btnChangeItemDescriptionAddress = new global::System.Windows.Forms.Button();
			this.txtItemDescriptionAddress = new global::System.Windows.Forms.TextBox();
			this.grpItemData = new global::System.Windows.Forms.GroupBox();
			this.nudItemEffectParam = new global::System.Windows.Forms.NumericUpDown();
			this.cmbItemHoldEffectId = new global::System.Windows.Forms.ComboBox();
			this.lblItemEffectParam = new global::System.Windows.Forms.Label();
			this.lblItemHoldEffectId = new global::System.Windows.Forms.Label();
			this.nudSpecialValue = new global::System.Windows.Forms.NumericUpDown();
			this.nudUnknownValue = new global::System.Windows.Forms.NumericUpDown();
			this.nudItemPrice = new global::System.Windows.Forms.NumericUpDown();
			this.nudItemId = new global::System.Windows.Forms.NumericUpDown();
			this.lblItemPriceYen = new global::System.Windows.Forms.Label();
			this.lblExtraDescription3 = new global::System.Windows.Forms.Label();
			this.lblSpecialValue = new global::System.Windows.Forms.Label();
			this.grpItemBattle = new global::System.Windows.Forms.GroupBox();
			this.cmbItemBattleType = new global::System.Windows.Forms.ComboBox();
			this.lblItemBattleType = new global::System.Windows.Forms.Label();
			this.txtItemBattleAddress = new global::System.Windows.Forms.TextBox();
			this.lblItemBattleAddress = new global::System.Windows.Forms.Label();
			this.grpItemField = new global::System.Windows.Forms.GroupBox();
			this.nudItemFieldType = new global::System.Windows.Forms.NumericUpDown();
			this.lblExtraDescription2 = new global::System.Windows.Forms.Label();
			this.cmbItemFieldType = new global::System.Windows.Forms.ComboBox();
			this.lblItemFieldType = new global::System.Windows.Forms.Label();
			this.txtItemFieldAddress = new global::System.Windows.Forms.TextBox();
			this.lblItemFieldAddress = new global::System.Windows.Forms.Label();
			this.cmbItemPocket = new global::System.Windows.Forms.ComboBox();
			this.cmbItemHoldableValue = new global::System.Windows.Forms.ComboBox();
			this.lblExtraDescription1 = new global::System.Windows.Forms.Label();
			this.lblUnknownValue = new global::System.Windows.Forms.Label();
			this.lblItemPrice = new global::System.Windows.Forms.Label();
			this.lblItemPocket = new global::System.Windows.Forms.Label();
			this.lblItemHoldableValue = new global::System.Windows.Forms.Label();
			this.lblItemID = new global::System.Windows.Forms.Label();
			this.txtItemId16 = new global::System.Windows.Forms.TextBox();
			this.grpItemEffectAddress = new global::System.Windows.Forms.GroupBox();
			this.txtItemEffectAddress = new global::System.Windows.Forms.TextBox();
			this.lblItemEffectAddress = new global::System.Windows.Forms.Label();
			this.txtItemIndex = new global::System.Windows.Forms.TextBox();
			this.lblItemIndex = new global::System.Windows.Forms.Label();
			this.grpItemSpritePreview = new global::System.Windows.Forms.GroupBox();
			this.grpItemName.SuspendLayout();
			this.grpItemSprite.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picItemSprite).BeginInit();
			this.grpItemDescription.SuspendLayout();
			this.grpItemData.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemEffectParam).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpecialValue).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemPrice).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemId).BeginInit();
			this.grpItemBattle.SuspendLayout();
			this.grpItemField.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemFieldType).BeginInit();
			this.grpItemEffectAddress.SuspendLayout();
			this.grpItemSpritePreview.SuspendLayout();
			base.SuspendLayout();
			this.btnSave.Location = new global::System.Drawing.Point(18, 16);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(84, 23);
			this.btnSave.TabIndex = 0;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			this.grpItemName.Controls.Add(this.btnChangeItemName);
			this.grpItemName.Controls.Add(this.txtItemName);
			this.grpItemName.Controls.Add(this.cmbItemName);
			this.grpItemName.Location = new global::System.Drawing.Point(66, 50);
			this.grpItemName.Name = "grpItemName";
			this.grpItemName.Size = new global::System.Drawing.Size(164, 108);
			this.grpItemName.TabIndex = 1;
			this.grpItemName.TabStop = false;
			this.grpItemName.Text = "アイテム名";
			this.btnChangeItemName.Location = new global::System.Drawing.Point(18, 71);
			this.btnChangeItemName.Name = "btnChangeItemName";
			this.btnChangeItemName.Size = new global::System.Drawing.Size(126, 23);
			this.btnChangeItemName.TabIndex = 2;
			this.btnChangeItemName.Text = "アイテム名を変更";
			this.btnChangeItemName.UseVisualStyleBackColor = true;
			this.txtItemName.Location = new global::System.Drawing.Point(18, 46);
			this.txtItemName.Name = "txtItemName";
			this.txtItemName.Size = new global::System.Drawing.Size(126, 19);
			this.txtItemName.TabIndex = 1;
			this.cmbItemName.FormattingEnabled = true;
			this.cmbItemName.Location = new global::System.Drawing.Point(18, 21);
			this.cmbItemName.Name = "cmbItemName";
			this.cmbItemName.Size = new global::System.Drawing.Size(126, 20);
			this.cmbItemName.TabIndex = 0;
			this.grpItemSprite.Controls.Add(this.rbItemSpritePalleteAddress);
			this.grpItemSprite.Controls.Add(this.rbItemSpriteImageAddress);
			this.grpItemSprite.Controls.Add(this.txtItemSpriteImportAddress);
			this.grpItemSprite.Controls.Add(this.btnItemSpriteImport);
			this.grpItemSprite.Controls.Add(this.btnItemSpriteExport);
			this.grpItemSprite.Controls.Add(this.btnChangeItemSpriteAddress);
			this.grpItemSprite.Controls.Add(this.txtItemSpritePalleteAddress);
			this.grpItemSprite.Controls.Add(this.txtItemSpriteImageAddress);
			this.grpItemSprite.Location = new global::System.Drawing.Point(14, 166);
			this.grpItemSprite.Name = "grpItemSprite";
			this.grpItemSprite.Size = new global::System.Drawing.Size(216, 152);
			this.grpItemSprite.TabIndex = 2;
			this.grpItemSprite.TabStop = false;
			this.grpItemSprite.Text = "アイテム画像";
			this.rbItemSpritePalleteAddress.AutoSize = true;
			this.rbItemSpritePalleteAddress.Location = new global::System.Drawing.Point(30, 43);
			this.rbItemSpritePalleteAddress.Name = "rbItemSpritePalleteAddress";
			this.rbItemSpritePalleteAddress.Size = new global::System.Drawing.Size(63, 16);
			this.rbItemSpritePalleteAddress.TabIndex = 7;
			this.rbItemSpritePalleteAddress.TabStop = true;
			this.rbItemSpritePalleteAddress.Text = "パレット :";
			this.rbItemSpritePalleteAddress.UseVisualStyleBackColor = true;
			this.rbItemSpriteImageAddress.AutoSize = true;
			this.rbItemSpriteImageAddress.Location = new global::System.Drawing.Point(30, 21);
			this.rbItemSpriteImageAddress.Name = "rbItemSpriteImageAddress";
			this.rbItemSpriteImageAddress.Size = new global::System.Drawing.Size(53, 16);
			this.rbItemSpriteImageAddress.TabIndex = 6;
			this.rbItemSpriteImageAddress.TabStop = true;
			this.rbItemSpriteImageAddress.Text = "画像 :";
			this.rbItemSpriteImageAddress.UseVisualStyleBackColor = true;
			this.txtItemSpriteImportAddress.Location = new global::System.Drawing.Point(18, 95);
			this.txtItemSpriteImportAddress.Name = "txtItemSpriteImportAddress";
			this.txtItemSpriteImportAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtItemSpriteImportAddress.TabIndex = 5;
			this.btnItemSpriteImport.Location = new global::System.Drawing.Point(108, 93);
			this.btnItemSpriteImport.Name = "btnItemSpriteImport";
			this.btnItemSpriteImport.Size = new global::System.Drawing.Size(88, 23);
			this.btnItemSpriteImport.TabIndex = 4;
			this.btnItemSpriteImport.Text = "インポート";
			this.btnItemSpriteImport.UseVisualStyleBackColor = true;
			this.btnItemSpriteExport.Location = new global::System.Drawing.Point(108, 121);
			this.btnItemSpriteExport.Name = "btnItemSpriteExport";
			this.btnItemSpriteExport.Size = new global::System.Drawing.Size(88, 23);
			this.btnItemSpriteExport.TabIndex = 4;
			this.btnItemSpriteExport.Text = "エクスポート";
			this.btnItemSpriteExport.UseVisualStyleBackColor = true;
			this.btnChangeItemSpriteAddress.Location = new global::System.Drawing.Point(18, 65);
			this.btnChangeItemSpriteAddress.Name = "btnChangeItemSpriteAddress";
			this.btnChangeItemSpriteAddress.Size = new global::System.Drawing.Size(178, 23);
			this.btnChangeItemSpriteAddress.TabIndex = 2;
			this.btnChangeItemSpriteAddress.Text = "アドレスを反映";
			this.btnChangeItemSpriteAddress.UseVisualStyleBackColor = true;
			this.txtItemSpritePalleteAddress.Location = new global::System.Drawing.Point(108, 41);
			this.txtItemSpritePalleteAddress.Name = "txtItemSpritePalleteAddress";
			this.txtItemSpritePalleteAddress.Size = new global::System.Drawing.Size(88, 19);
			this.txtItemSpritePalleteAddress.TabIndex = 1;
			this.txtItemSpriteImageAddress.Location = new global::System.Drawing.Point(108, 17);
			this.txtItemSpriteImageAddress.Name = "txtItemSpriteImageAddress";
			this.txtItemSpriteImageAddress.Size = new global::System.Drawing.Size(88, 19);
			this.txtItemSpriteImageAddress.TabIndex = 1;
			this.picItemSprite.Location = new global::System.Drawing.Point(8, 13);
			this.picItemSprite.Name = "picItemSprite";
			this.picItemSprite.Size = new global::System.Drawing.Size(24, 24);
			this.picItemSprite.TabIndex = 0;
			this.picItemSprite.TabStop = false;
			this.grpItemDescription.Controls.Add(this.txtItemDescription);
			this.grpItemDescription.Controls.Add(this.btnChangeItemDescription);
			this.grpItemDescription.Controls.Add(this.btnChangeItemDescriptionAddress);
			this.grpItemDescription.Controls.Add(this.txtItemDescriptionAddress);
			this.grpItemDescription.Location = new global::System.Drawing.Point(14, 328);
			this.grpItemDescription.Name = "grpItemDescription";
			this.grpItemDescription.Size = new global::System.Drawing.Size(216, 150);
			this.grpItemDescription.TabIndex = 3;
			this.grpItemDescription.TabStop = false;
			this.grpItemDescription.Text = "アイテム説明文";
			this.txtItemDescription.Location = new global::System.Drawing.Point(10, 50);
			this.txtItemDescription.Multiline = true;
			this.txtItemDescription.Name = "txtItemDescription";
			this.txtItemDescription.ScrollBars = global::System.Windows.Forms.ScrollBars.Vertical;
			this.txtItemDescription.Size = new global::System.Drawing.Size(196, 60);
			this.txtItemDescription.TabIndex = 2;
			this.btnChangeItemDescription.Location = new global::System.Drawing.Point(66, 116);
			this.btnChangeItemDescription.Name = "btnChangeItemDescription";
			this.btnChangeItemDescription.Size = new global::System.Drawing.Size(130, 23);
			this.btnChangeItemDescription.TabIndex = 1;
			this.btnChangeItemDescription.Text = "説明文の変更を反映";
			this.btnChangeItemDescription.UseVisualStyleBackColor = true;
			this.btnChangeItemDescriptionAddress.Location = new global::System.Drawing.Point(108, 20);
			this.btnChangeItemDescriptionAddress.Name = "btnChangeItemDescriptionAddress";
			this.btnChangeItemDescriptionAddress.Size = new global::System.Drawing.Size(88, 23);
			this.btnChangeItemDescriptionAddress.TabIndex = 1;
			this.btnChangeItemDescriptionAddress.Text = "アドレスを変更";
			this.btnChangeItemDescriptionAddress.UseVisualStyleBackColor = true;
			this.txtItemDescriptionAddress.Location = new global::System.Drawing.Point(18, 22);
			this.txtItemDescriptionAddress.Name = "txtItemDescriptionAddress";
			this.txtItemDescriptionAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtItemDescriptionAddress.TabIndex = 0;
			this.grpItemData.Controls.Add(this.nudItemEffectParam);
			this.grpItemData.Controls.Add(this.cmbItemHoldEffectId);
			this.grpItemData.Controls.Add(this.lblItemEffectParam);
			this.grpItemData.Controls.Add(this.lblItemHoldEffectId);
			this.grpItemData.Controls.Add(this.nudSpecialValue);
			this.grpItemData.Controls.Add(this.nudUnknownValue);
			this.grpItemData.Controls.Add(this.nudItemPrice);
			this.grpItemData.Controls.Add(this.nudItemId);
			this.grpItemData.Controls.Add(this.lblItemPriceYen);
			this.grpItemData.Controls.Add(this.lblExtraDescription3);
			this.grpItemData.Controls.Add(this.lblSpecialValue);
			this.grpItemData.Controls.Add(this.grpItemBattle);
			this.grpItemData.Controls.Add(this.grpItemField);
			this.grpItemData.Controls.Add(this.cmbItemPocket);
			this.grpItemData.Controls.Add(this.cmbItemHoldableValue);
			this.grpItemData.Controls.Add(this.lblExtraDescription1);
			this.grpItemData.Controls.Add(this.lblUnknownValue);
			this.grpItemData.Controls.Add(this.lblItemPrice);
			this.grpItemData.Controls.Add(this.lblItemPocket);
			this.grpItemData.Controls.Add(this.lblItemHoldableValue);
			this.grpItemData.Controls.Add(this.lblItemID);
			this.grpItemData.Controls.Add(this.txtItemId16);
			this.grpItemData.Location = new global::System.Drawing.Point(244, 14);
			this.grpItemData.Name = "grpItemData";
			this.grpItemData.Size = new global::System.Drawing.Size(338, 406);
			this.grpItemData.TabIndex = 4;
			this.grpItemData.TabStop = false;
			this.grpItemData.Text = "アイテムデータ";
			this.nudItemEffectParam.Location = new global::System.Drawing.Point(86, 97);
			global::System.Windows.Forms.NumericUpDown nudItemEffectParam = this.nudItemEffectParam;
			int[] array = new int[4];
			array[0] = 255;
			nudItemEffectParam.Maximum = new decimal(array);
			this.nudItemEffectParam.Name = "nudItemEffectParam";
			this.nudItemEffectParam.Size = new global::System.Drawing.Size(58, 19);
			this.nudItemEffectParam.TabIndex = 17;
			this.cmbItemHoldEffectId.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbItemHoldEffectId.FormattingEnabled = true;
			this.cmbItemHoldEffectId.Location = new global::System.Drawing.Point(86, 71);
			this.cmbItemHoldEffectId.Name = "cmbItemHoldEffectId";
			this.cmbItemHoldEffectId.Size = new global::System.Drawing.Size(230, 20);
			this.cmbItemHoldEffectId.TabIndex = 16;
			this.lblItemEffectParam.AutoSize = true;
			this.lblItemEffectParam.Location = new global::System.Drawing.Point(20, 100);
			this.lblItemEffectParam.Name = "lblItemEffectParam";
			this.lblItemEffectParam.Size = new global::System.Drawing.Size(47, 12);
			this.lblItemEffectParam.TabIndex = 14;
			this.lblItemEffectParam.Text = "効果値 :";
			this.lblItemHoldEffectId.AutoSize = true;
			this.lblItemHoldEffectId.Location = new global::System.Drawing.Point(20, 75);
			this.lblItemHoldEffectId.Name = "lblItemHoldEffectId";
			this.lblItemHoldEffectId.Size = new global::System.Drawing.Size(59, 12);
			this.lblItemHoldEffectId.TabIndex = 15;
			this.lblItemHoldEffectId.Text = "所持効果 :";
			this.nudSpecialValue.Location = new global::System.Drawing.Point(86, 374);
			global::System.Windows.Forms.NumericUpDown nudSpecialValue = this.nudSpecialValue;
			int[] array2 = new int[4];
			array2[0] = 255;
			nudSpecialValue.Maximum = new decimal(array2);
			this.nudSpecialValue.Name = "nudSpecialValue";
			this.nudSpecialValue.Size = new global::System.Drawing.Size(58, 19);
			this.nudSpecialValue.TabIndex = 13;
			this.nudUnknownValue.Location = new global::System.Drawing.Point(86, 148);
			global::System.Windows.Forms.NumericUpDown nudUnknownValue = this.nudUnknownValue;
			int[] array3 = new int[4];
			array3[0] = 255;
			nudUnknownValue.Maximum = new decimal(array3);
			this.nudUnknownValue.Name = "nudUnknownValue";
			this.nudUnknownValue.Size = new global::System.Drawing.Size(58, 19);
			this.nudUnknownValue.TabIndex = 12;
			this.nudItemPrice.Location = new global::System.Drawing.Point(86, 46);
			global::System.Windows.Forms.NumericUpDown nudItemPrice = this.nudItemPrice;
			int[] array4 = new int[4];
			array4[0] = 65535;
			nudItemPrice.Maximum = new decimal(array4);
			this.nudItemPrice.Name = "nudItemPrice";
			this.nudItemPrice.Size = new global::System.Drawing.Size(58, 19);
			this.nudItemPrice.TabIndex = 11;
			this.nudItemId.Location = new global::System.Drawing.Point(86, 21);
			global::System.Windows.Forms.NumericUpDown nudItemId = this.nudItemId;
			int[] array5 = new int[4];
			array5[0] = 65535;
			nudItemId.Maximum = new decimal(array5);
			this.nudItemId.Name = "nudItemId";
			this.nudItemId.Size = new global::System.Drawing.Size(58, 19);
			this.nudItemId.TabIndex = 11;
			this.lblItemPriceYen.AutoSize = true;
			this.lblItemPriceYen.Location = new global::System.Drawing.Point(152, 50);
			this.lblItemPriceYen.Name = "lblItemPriceYen";
			this.lblItemPriceYen.Size = new global::System.Drawing.Size(17, 12);
			this.lblItemPriceYen.TabIndex = 10;
			this.lblItemPriceYen.Text = "円";
			this.lblExtraDescription3.AutoSize = true;
			this.lblExtraDescription3.Location = new global::System.Drawing.Point(176, 378);
			this.lblExtraDescription3.Name = "lblExtraDescription3";
			this.lblExtraDescription3.Size = new global::System.Drawing.Size(129, 12);
			this.lblExtraDescription3.TabIndex = 9;
			this.lblExtraDescription3.Text = "※3 ボール/メール/釣り竿";
			this.lblSpecialValue.AutoSize = true;
			this.lblSpecialValue.Location = new global::System.Drawing.Point(20, 378);
			this.lblSpecialValue.Name = "lblSpecialValue";
			this.lblSpecialValue.Size = new global::System.Drawing.Size(46, 12);
			this.lblSpecialValue.TabIndex = 8;
			this.lblSpecialValue.Text = "特殊ID :";
			this.grpItemBattle.Controls.Add(this.cmbItemBattleType);
			this.grpItemBattle.Controls.Add(this.lblItemBattleType);
			this.grpItemBattle.Controls.Add(this.txtItemBattleAddress);
			this.grpItemBattle.Controls.Add(this.lblItemBattleAddress);
			this.grpItemBattle.Location = new global::System.Drawing.Point(10, 288);
			this.grpItemBattle.Name = "grpItemBattle";
			this.grpItemBattle.Size = new global::System.Drawing.Size(318, 78);
			this.grpItemBattle.TabIndex = 6;
			this.grpItemBattle.TabStop = false;
			this.grpItemBattle.Text = "バトル使用";
			this.cmbItemBattleType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbItemBattleType.FormattingEnabled = true;
			this.cmbItemBattleType.Items.AddRange(new object[] { "00 - 使用不可", "01 - 使用可能（対象を選ぶ）", "02 - 使用可能（その他）", "03 - きのみぶくろ" });
			this.cmbItemBattleType.Location = new global::System.Drawing.Point(76, 20);
			this.cmbItemBattleType.Name = "cmbItemBattleType";
			this.cmbItemBattleType.Size = new global::System.Drawing.Size(168, 20);
			this.cmbItemBattleType.TabIndex = 7;
			this.lblItemBattleType.AutoSize = true;
			this.lblItemBattleType.Location = new global::System.Drawing.Point(19, 25);
			this.lblItemBattleType.Name = "lblItemBattleType";
			this.lblItemBattleType.Size = new global::System.Drawing.Size(37, 12);
			this.lblItemBattleType.TabIndex = 5;
			this.lblItemBattleType.Text = "タイプ :";
			this.txtItemBattleAddress.Location = new global::System.Drawing.Point(76, 45);
			this.txtItemBattleAddress.Name = "txtItemBattleAddress";
			this.txtItemBattleAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtItemBattleAddress.TabIndex = 4;
			this.lblItemBattleAddress.AutoSize = true;
			this.lblItemBattleAddress.Location = new global::System.Drawing.Point(19, 49);
			this.lblItemBattleAddress.Name = "lblItemBattleAddress";
			this.lblItemBattleAddress.Size = new global::System.Drawing.Size(47, 12);
			this.lblItemBattleAddress.TabIndex = 6;
			this.lblItemBattleAddress.Text = "アドレス :";
			this.grpItemField.Controls.Add(this.nudItemFieldType);
			this.grpItemField.Controls.Add(this.lblExtraDescription2);
			this.grpItemField.Controls.Add(this.cmbItemFieldType);
			this.grpItemField.Controls.Add(this.lblItemFieldType);
			this.grpItemField.Controls.Add(this.txtItemFieldAddress);
			this.grpItemField.Controls.Add(this.lblItemFieldAddress);
			this.grpItemField.Location = new global::System.Drawing.Point(10, 204);
			this.grpItemField.Name = "grpItemField";
			this.grpItemField.Size = new global::System.Drawing.Size(318, 78);
			this.grpItemField.TabIndex = 5;
			this.grpItemField.TabStop = false;
			this.grpItemField.Text = "フィールド使用";
			this.nudItemFieldType.Location = new global::System.Drawing.Point(76, 20);
			global::System.Windows.Forms.NumericUpDown nudItemFieldType = this.nudItemFieldType;
			int[] array6 = new int[4];
			array6[0] = 255;
			nudItemFieldType.Maximum = new decimal(array6);
			this.nudItemFieldType.Name = "nudItemFieldType";
			this.nudItemFieldType.Size = new global::System.Drawing.Size(58, 19);
			this.nudItemFieldType.TabIndex = 4;
			this.lblExtraDescription2.AutoSize = true;
			this.lblExtraDescription2.Location = new global::System.Drawing.Point(167, 49);
			this.lblExtraDescription2.Name = "lblExtraDescription2";
			this.lblExtraDescription2.Size = new global::System.Drawing.Size(68, 12);
			this.lblExtraDescription2.TabIndex = 3;
			this.lblExtraDescription2.Text = "※2 ボールID";
			this.cmbItemFieldType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbItemFieldType.FormattingEnabled = true;
			this.cmbItemFieldType.Items.AddRange(new object[] { "ボール・メール", "ポケモンに使う道具？", "一部たいせつなもの？", "ポロック（未使用）", "使うとメッセージが出る道具？" });
			this.cmbItemFieldType.Location = new global::System.Drawing.Point(144, 19);
			this.cmbItemFieldType.Name = "cmbItemFieldType";
			this.cmbItemFieldType.Size = new global::System.Drawing.Size(162, 20);
			this.cmbItemFieldType.TabIndex = 2;
			this.lblItemFieldType.AutoSize = true;
			this.lblItemFieldType.Location = new global::System.Drawing.Point(19, 25);
			this.lblItemFieldType.Name = "lblItemFieldType";
			this.lblItemFieldType.Size = new global::System.Drawing.Size(37, 12);
			this.lblItemFieldType.TabIndex = 1;
			this.lblItemFieldType.Text = "タイプ :";
			this.txtItemFieldAddress.Location = new global::System.Drawing.Point(76, 45);
			this.txtItemFieldAddress.Name = "txtItemFieldAddress";
			this.txtItemFieldAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtItemFieldAddress.TabIndex = 0;
			this.lblItemFieldAddress.AutoSize = true;
			this.lblItemFieldAddress.Location = new global::System.Drawing.Point(19, 49);
			this.lblItemFieldAddress.Name = "lblItemFieldAddress";
			this.lblItemFieldAddress.Size = new global::System.Drawing.Size(47, 12);
			this.lblItemFieldAddress.TabIndex = 1;
			this.lblItemFieldAddress.Text = "アドレス :";
			this.cmbItemPocket.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbItemPocket.FormattingEnabled = true;
			this.cmbItemPocket.Items.AddRange(new object[] { "01 - どうぐ", "02 - たいせつなもの", "03 - モンスターボール", "04 - わざマシンケース", "05 - きのみぶくろ" });
			this.cmbItemPocket.Location = new global::System.Drawing.Point(86, 173);
			this.cmbItemPocket.Name = "cmbItemPocket";
			this.cmbItemPocket.Size = new global::System.Drawing.Size(134, 20);
			this.cmbItemPocket.TabIndex = 4;
			this.cmbItemHoldableValue.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbItemHoldableValue.FormattingEnabled = true;
			this.cmbItemHoldableValue.Items.AddRange(new object[] { "00 - 持たせられる", "01 - 持たせられない", "02 - 持たせられない？" });
			this.cmbItemHoldableValue.Location = new global::System.Drawing.Point(86, 122);
			this.cmbItemHoldableValue.Name = "cmbItemHoldableValue";
			this.cmbItemHoldableValue.Size = new global::System.Drawing.Size(134, 20);
			this.cmbItemHoldableValue.TabIndex = 4;
			this.lblExtraDescription1.AutoSize = true;
			this.lblExtraDescription1.Location = new global::System.Drawing.Point(176, 152);
			this.lblExtraDescription1.Name = "lblExtraDescription1";
			this.lblExtraDescription1.Size = new global::System.Drawing.Size(131, 12);
			this.lblExtraDescription1.TabIndex = 3;
			this.lblExtraDescription1.Text = "※1 木の実/技マシン番号";
			this.lblUnknownValue.AutoSize = true;
			this.lblUnknownValue.Location = new global::System.Drawing.Point(20, 153);
			this.lblUnknownValue.Name = "lblUnknownValue";
			this.lblUnknownValue.Size = new global::System.Drawing.Size(47, 12);
			this.lblUnknownValue.TabIndex = 1;
			this.lblUnknownValue.Text = "不明値 :";
			this.lblItemPrice.AutoSize = true;
			this.lblItemPrice.Location = new global::System.Drawing.Point(20, 50);
			this.lblItemPrice.Name = "lblItemPrice";
			this.lblItemPrice.Size = new global::System.Drawing.Size(35, 12);
			this.lblItemPrice.TabIndex = 1;
			this.lblItemPrice.Text = "値段 :";
			this.lblItemPocket.AutoSize = true;
			this.lblItemPocket.Location = new global::System.Drawing.Point(20, 178);
			this.lblItemPocket.Name = "lblItemPocket";
			this.lblItemPocket.Size = new global::System.Drawing.Size(45, 12);
			this.lblItemPocket.TabIndex = 1;
			this.lblItemPocket.Text = "ポケット :";
			this.lblItemHoldableValue.AutoSize = true;
			this.lblItemHoldableValue.Location = new global::System.Drawing.Point(20, 127);
			this.lblItemHoldableValue.Name = "lblItemHoldableValue";
			this.lblItemHoldableValue.Size = new global::System.Drawing.Size(59, 12);
			this.lblItemHoldableValue.TabIndex = 1;
			this.lblItemHoldableValue.Text = "所持可否 :";
			this.lblItemID.AutoSize = true;
			this.lblItemID.Location = new global::System.Drawing.Point(20, 26);
			this.lblItemID.Name = "lblItemID";
			this.lblItemID.Size = new global::System.Drawing.Size(59, 12);
			this.lblItemID.TabIndex = 1;
			this.lblItemID.Text = "アイテムID :";
			this.txtItemId16.Location = new global::System.Drawing.Point(153, 21);
			this.txtItemId16.Name = "txtItemId16";
			this.txtItemId16.ReadOnly = true;
			this.txtItemId16.Size = new global::System.Drawing.Size(58, 19);
			this.txtItemId16.TabIndex = 0;
			this.grpItemEffectAddress.Controls.Add(this.txtItemEffectAddress);
			this.grpItemEffectAddress.Controls.Add(this.lblItemEffectAddress);
			this.grpItemEffectAddress.Location = new global::System.Drawing.Point(244, 426);
			this.grpItemEffectAddress.Name = "grpItemEffectAddress";
			this.grpItemEffectAddress.Size = new global::System.Drawing.Size(338, 52);
			this.grpItemEffectAddress.TabIndex = 5;
			this.grpItemEffectAddress.TabStop = false;
			this.grpItemEffectAddress.Text = "アイテム効果アドレス";
			this.txtItemEffectAddress.Enabled = false;
			this.txtItemEffectAddress.Location = new global::System.Drawing.Point(86, 20);
			this.txtItemEffectAddress.Name = "txtItemEffectAddress";
			this.txtItemEffectAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtItemEffectAddress.TabIndex = 1;
			this.lblItemEffectAddress.AutoSize = true;
			this.lblItemEffectAddress.Location = new global::System.Drawing.Point(20, 24);
			this.lblItemEffectAddress.Name = "lblItemEffectAddress";
			this.lblItemEffectAddress.Size = new global::System.Drawing.Size(47, 12);
			this.lblItemEffectAddress.TabIndex = 0;
			this.lblItemEffectAddress.Text = "アドレス :";
			this.txtItemIndex.Location = new global::System.Drawing.Point(190, 18);
			this.txtItemIndex.Name = "txtItemIndex";
			this.txtItemIndex.ReadOnly = true;
			this.txtItemIndex.Size = new global::System.Drawing.Size(40, 19);
			this.txtItemIndex.TabIndex = 6;
			this.lblItemIndex.AutoSize = true;
			this.lblItemIndex.Location = new global::System.Drawing.Point(112, 22);
			this.lblItemIndex.Name = "lblItemIndex";
			this.lblItemIndex.Size = new global::System.Drawing.Size(75, 12);
			this.lblItemIndex.TabIndex = 7;
			this.lblItemIndex.Text = "アイテムコード :";
			this.grpItemSpritePreview.Controls.Add(this.picItemSprite);
			this.grpItemSpritePreview.Location = new global::System.Drawing.Point(18, 66);
			this.grpItemSpritePreview.Name = "grpItemSpritePreview";
			this.grpItemSpritePreview.Size = new global::System.Drawing.Size(40, 46);
			this.grpItemSpritePreview.TabIndex = 8;
			this.grpItemSpritePreview.TabStop = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(598, 493);
			base.Controls.Add(this.grpItemSpritePreview);
			base.Controls.Add(this.lblItemIndex);
			base.Controls.Add(this.txtItemIndex);
			base.Controls.Add(this.grpItemEffectAddress);
			base.Controls.Add(this.grpItemData);
			base.Controls.Add(this.grpItemDescription);
			base.Controls.Add(this.grpItemSprite);
			base.Controls.Add(this.grpItemName);
			base.Controls.Add(this.btnSave);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "ItemEditor";
			this.Text = "アイテム";
			this.grpItemName.ResumeLayout(false);
			this.grpItemName.PerformLayout();
			this.grpItemSprite.ResumeLayout(false);
			this.grpItemSprite.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picItemSprite).EndInit();
			this.grpItemDescription.ResumeLayout(false);
			this.grpItemDescription.PerformLayout();
			this.grpItemData.ResumeLayout(false);
			this.grpItemData.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemEffectParam).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpecialValue).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnknownValue).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemPrice).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemId).EndInit();
			this.grpItemBattle.ResumeLayout(false);
			this.grpItemBattle.PerformLayout();
			this.grpItemField.ResumeLayout(false);
			this.grpItemField.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudItemFieldType).EndInit();
			this.grpItemEffectAddress.ResumeLayout(false);
			this.grpItemEffectAddress.PerformLayout();
			this.grpItemSpritePreview.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040001BE RID: 446
				private Button _btnSave;
		private ComboBox _cmbItemName;
		private Button _btnChangeItemName;
		private TextBox _txtItemSpritePalleteAddress;
		private TextBox _txtItemSpriteImageAddress;
		private Button _btnChangeItemSpriteAddress;
		private Button _btnChangeItemDescriptionAddress;
		private Button _btnChangeItemDescription;
		private ComboBox _cmbItemHoldableValue;
		private ComboBox _cmbItemFieldType;
		private TextBox _txtItemFieldAddress;
		private ComboBox _cmbItemPocket;
		private ComboBox _cmbItemBattleType;
		private TextBox _txtItemBattleAddress;
		private NumericUpDown _nudItemPrice;
		private NumericUpDown _nudItemId;
		private NumericUpDown _nudSpecialValue;
		private NumericUpDown _nudUnknownValue;
		private NumericUpDown _nudItemFieldType;
		private NumericUpDown _nudItemEffectParam;
		private ComboBox _cmbItemHoldEffectId;
		private TextBox _txtItemEffectAddress;
		private Button _btnItemSpriteExport;
		private Button _btnItemSpriteImport;
        private global::System.ComponentModel.IContainer components;
	}
}
