namespace BochiBochiEditor
{
	// Token: 0x0200001A RID: 26
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class MainForm : global::System.Windows.Forms.Form
	{
		// Token: 0x0600041F RID: 1055 RVA: 0x0001EBF4 File Offset: 0x0001CDF4
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000420 RID: 1056 RVA: 0x0001EC44 File Offset: 0x0001CE44
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.MainForm));
			this.btnLoadRom = new global::System.Windows.Forms.Button();
			this.grpRomInfo = new global::System.Windows.Forms.GroupBox();
			this.lblRomInfo = new global::System.Windows.Forms.Label();
			this.btnMainPokemonEditor = new global::System.Windows.Forms.Button();
			this.grpMainSelect = new global::System.Windows.Forms.GroupBox();
			this.grpFreeSpaceFinder = new global::System.Windows.Forms.GroupBox();
			this.lblFreeSpaceFinderResultAddress = new global::System.Windows.Forms.Label();
			this.btnFreeSpaceFinderSearch = new global::System.Windows.Forms.Button();
			this.txtFreeSpaceFinderResultAddress = new global::System.Windows.Forms.TextBox();
			this.lblFreeSpaceFinderNeededByte = new global::System.Windows.Forms.Label();
			this.nudFreeSpaceFinderNeededByte = new global::System.Windows.Forms.NumericUpDown();
			this.lblFreeSpaceFinderStartAddress = new global::System.Windows.Forms.Label();
			this.txtFreeSpaceFinderStartAddress = new global::System.Windows.Forms.TextBox();
			this.btnMainHeldItemMailEditor = new global::System.Windows.Forms.Button();
			this.lblVersion = new global::System.Windows.Forms.Label();
			this.lblCopyright = new global::System.Windows.Forms.Label();
			this.btnMainWIldPokemonEditor = new global::System.Windows.Forms.Button();
			this.btnMainInGameTradeEditor = new global::System.Windows.Forms.Button();
			this.btnMainRegionEditor = new global::System.Windows.Forms.Button();
			this.btnMainTrainerDataEditor = new global::System.Windows.Forms.Button();
			this.btnMainTrainerSpriteEditor = new global::System.Windows.Forms.Button();
			this.btnMainTileAnimAndDoorEditor = new global::System.Windows.Forms.Button();
			this.btnMainItemUseCoordinate = new global::System.Windows.Forms.Button();
			this.btnMainOverWorldEditor = new global::System.Windows.Forms.Button();
			this.btnMainMapEditor = new global::System.Windows.Forms.Button();
			this.btnMainItemEditor = new global::System.Windows.Forms.Button();
			this.btnMainPokedexListEditor = new global::System.Windows.Forms.Button();
			this.btnMainHabitatEditor = new global::System.Windows.Forms.Button();
			this.btnMainTmHmTutorEditor = new global::System.Windows.Forms.Button();
			this.btnMainEggMoveEditor = new global::System.Windows.Forms.Button();
			this.btnMainPokedexOrderEditor = new global::System.Windows.Forms.Button();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.btnSaveRom = new global::System.Windows.Forms.Button();
			this.grpRomInfo.SuspendLayout();
			this.grpMainSelect.SuspendLayout();
			this.grpFreeSpaceFinder.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudFreeSpaceFinderNeededByte).BeginInit();
			base.SuspendLayout();
			this.btnLoadRom.Location = new global::System.Drawing.Point(14, 12);
			this.btnLoadRom.Name = "btnLoadRom";
			this.btnLoadRom.Size = new global::System.Drawing.Size(80, 36);
			this.btnLoadRom.TabIndex = 0;
			this.btnLoadRom.Text = "ROMを選択";
			this.btnLoadRom.UseVisualStyleBackColor = true;
			this.grpRomInfo.Controls.Add(this.lblRomInfo);
			this.grpRomInfo.Location = new global::System.Drawing.Point(188, 8);
			this.grpRomInfo.Name = "grpRomInfo";
			this.grpRomInfo.Size = new global::System.Drawing.Size(236, 40);
			this.grpRomInfo.TabIndex = 1;
			this.grpRomInfo.TabStop = false;
			this.grpRomInfo.Text = "ROM情報";
			this.lblRomInfo.AutoSize = true;
			this.lblRomInfo.Location = new global::System.Drawing.Point(14, 18);
			this.lblRomInfo.Name = "lblRomInfo";
			this.lblRomInfo.Size = new global::System.Drawing.Size(102, 12);
			this.lblRomInfo.TabIndex = 0;
			this.lblRomInfo.Text = "上書きされるテキスト";
			this.btnMainPokemonEditor.Location = new global::System.Drawing.Point(10, 22);
			this.btnMainPokemonEditor.Name = "btnMainPokemonEditor";
			this.btnMainPokemonEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainPokemonEditor.TabIndex = 2;
			this.btnMainPokemonEditor.Text = "ポケモン";
			this.btnMainPokemonEditor.UseVisualStyleBackColor = true;
			this.grpMainSelect.Controls.Add(this.grpFreeSpaceFinder);
			this.grpMainSelect.Controls.Add(this.btnMainHeldItemMailEditor);
			this.grpMainSelect.Controls.Add(this.lblVersion);
			this.grpMainSelect.Controls.Add(this.lblCopyright);
			this.grpMainSelect.Controls.Add(this.btnMainWIldPokemonEditor);
			this.grpMainSelect.Controls.Add(this.btnMainInGameTradeEditor);
			this.grpMainSelect.Controls.Add(this.btnMainRegionEditor);
			this.grpMainSelect.Controls.Add(this.btnMainTrainerDataEditor);
			this.grpMainSelect.Controls.Add(this.btnMainTrainerSpriteEditor);
			this.grpMainSelect.Controls.Add(this.btnMainTileAnimAndDoorEditor);
			this.grpMainSelect.Controls.Add(this.btnMainItemUseCoordinate);
			this.grpMainSelect.Controls.Add(this.btnMainOverWorldEditor);
			this.grpMainSelect.Controls.Add(this.btnMainMapEditor);
			this.grpMainSelect.Controls.Add(this.btnMainItemEditor);
			this.grpMainSelect.Controls.Add(this.btnMainPokedexListEditor);
			this.grpMainSelect.Controls.Add(this.btnMainHabitatEditor);
			this.grpMainSelect.Controls.Add(this.btnMainTmHmTutorEditor);
			this.grpMainSelect.Controls.Add(this.btnMainEggMoveEditor);
			this.grpMainSelect.Controls.Add(this.btnMainPokedexOrderEditor);
			this.grpMainSelect.Controls.Add(this.btnMainPokemonEditor);
			this.grpMainSelect.Location = new global::System.Drawing.Point(12, 56);
			this.grpMainSelect.Name = "grpMainSelect";
			this.grpMainSelect.Size = new global::System.Drawing.Size(570, 210);
			this.grpMainSelect.TabIndex = 3;
			this.grpMainSelect.TabStop = false;
			this.grpMainSelect.Text = "編集項目を選択";
			this.grpFreeSpaceFinder.Controls.Add(this.lblFreeSpaceFinderResultAddress);
			this.grpFreeSpaceFinder.Controls.Add(this.btnFreeSpaceFinderSearch);
			this.grpFreeSpaceFinder.Controls.Add(this.txtFreeSpaceFinderResultAddress);
			this.grpFreeSpaceFinder.Controls.Add(this.lblFreeSpaceFinderNeededByte);
			this.grpFreeSpaceFinder.Controls.Add(this.nudFreeSpaceFinderNeededByte);
			this.grpFreeSpaceFinder.Controls.Add(this.lblFreeSpaceFinderStartAddress);
			this.grpFreeSpaceFinder.Controls.Add(this.txtFreeSpaceFinderStartAddress);
			this.grpFreeSpaceFinder.Location = new global::System.Drawing.Point(416, 18);
			this.grpFreeSpaceFinder.Name = "grpFreeSpaceFinder";
			this.grpFreeSpaceFinder.Size = new global::System.Drawing.Size(142, 136);
			this.grpFreeSpaceFinder.TabIndex = 6;
			this.grpFreeSpaceFinder.TabStop = false;
			this.grpFreeSpaceFinder.Text = "空き領域検索";
			this.lblFreeSpaceFinderResultAddress.AutoSize = true;
			this.lblFreeSpaceFinderResultAddress.Location = new global::System.Drawing.Point(11, 108);
			this.lblFreeSpaceFinderResultAddress.Name = "lblFreeSpaceFinderResultAddress";
			this.lblFreeSpaceFinderResultAddress.Size = new global::System.Drawing.Size(35, 12);
			this.lblFreeSpaceFinderResultAddress.TabIndex = 6;
			this.lblFreeSpaceFinderResultAddress.Text = "結果 :";
			this.btnFreeSpaceFinderSearch.Location = new global::System.Drawing.Point(13, 74);
			this.btnFreeSpaceFinderSearch.Name = "btnFreeSpaceFinderSearch";
			this.btnFreeSpaceFinderSearch.Size = new global::System.Drawing.Size(117, 23);
			this.btnFreeSpaceFinderSearch.TabIndex = 5;
			this.btnFreeSpaceFinderSearch.Text = "検索";
			this.btnFreeSpaceFinderSearch.UseVisualStyleBackColor = true;
			this.txtFreeSpaceFinderResultAddress.Location = new global::System.Drawing.Point(50, 104);
			this.txtFreeSpaceFinderResultAddress.Name = "txtFreeSpaceFinderResultAddress";
			this.txtFreeSpaceFinderResultAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtFreeSpaceFinderResultAddress.TabIndex = 4;
			this.lblFreeSpaceFinderNeededByte.AutoSize = true;
			this.lblFreeSpaceFinderNeededByte.Location = new global::System.Drawing.Point(11, 52);
			this.lblFreeSpaceFinderNeededByte.Name = "lblFreeSpaceFinderNeededByte";
			this.lblFreeSpaceFinderNeededByte.Size = new global::System.Drawing.Size(50, 12);
			this.lblFreeSpaceFinderNeededByte.TabIndex = 3;
			this.lblFreeSpaceFinderNeededByte.Text = "バイト数 :";
			this.nudFreeSpaceFinderNeededByte.Location = new global::System.Drawing.Point(66, 48);
			global::System.Windows.Forms.NumericUpDown nudFreeSpaceFinderNeededByte = this.nudFreeSpaceFinderNeededByte;
			int[] array = new int[4];
			array[0] = 4096;
			nudFreeSpaceFinderNeededByte.Maximum = new decimal(array);
			global::System.Windows.Forms.NumericUpDown nudFreeSpaceFinderNeededByte2 = this.nudFreeSpaceFinderNeededByte;
			int[] array2 = new int[4];
			array2[0] = 1;
			nudFreeSpaceFinderNeededByte2.Minimum = new decimal(array2);
			this.nudFreeSpaceFinderNeededByte.Name = "nudFreeSpaceFinderNeededByte";
			this.nudFreeSpaceFinderNeededByte.Size = new global::System.Drawing.Size(64, 19);
			this.nudFreeSpaceFinderNeededByte.TabIndex = 2;
			global::System.Windows.Forms.NumericUpDown nudFreeSpaceFinderNeededByte3 = this.nudFreeSpaceFinderNeededByte;
			int[] array3 = new int[4];
			array3[0] = 2048;
			nudFreeSpaceFinderNeededByte3.Value = new decimal(array3);
			this.lblFreeSpaceFinderStartAddress.AutoSize = true;
			this.lblFreeSpaceFinderStartAddress.Location = new global::System.Drawing.Point(11, 26);
			this.lblFreeSpaceFinderStartAddress.Name = "lblFreeSpaceFinderStartAddress";
			this.lblFreeSpaceFinderStartAddress.Size = new global::System.Drawing.Size(35, 12);
			this.lblFreeSpaceFinderStartAddress.TabIndex = 1;
			this.lblFreeSpaceFinderStartAddress.Text = "開始 :";
			this.txtFreeSpaceFinderStartAddress.Location = new global::System.Drawing.Point(50, 22);
			this.txtFreeSpaceFinderStartAddress.Name = "txtFreeSpaceFinderStartAddress";
			this.txtFreeSpaceFinderStartAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtFreeSpaceFinderStartAddress.TabIndex = 0;
			this.btnMainHeldItemMailEditor.Location = new global::System.Drawing.Point(144, 172);
			this.btnMainHeldItemMailEditor.Name = "btnMainHeldItemMailEditor";
			this.btnMainHeldItemMailEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainHeldItemMailEditor.TabIndex = 5;
			this.btnMainHeldItemMailEditor.Text = "メール内容";
			this.btnMainHeldItemMailEditor.UseVisualStyleBackColor = true;
			this.lblVersion.AutoSize = true;
			this.lblVersion.Location = new global::System.Drawing.Point(414, 166);
			this.lblVersion.Name = "lblVersion";
			this.lblVersion.Size = new global::System.Drawing.Size(152, 12);
			this.lblVersion.TabIndex = 4;
			this.lblVersion.Text = "BochiBochiEditor Version 1.4";
			this.lblCopyright.AutoSize = true;
			this.lblCopyright.Location = new global::System.Drawing.Point(414, 182);
			this.lblCopyright.Name = "lblCopyright";
			this.lblCopyright.Size = new global::System.Drawing.Size(140, 12);
			this.lblCopyright.TabIndex = 3;
			this.lblCopyright.Text = "Copyright (C) 2025 - 2026";
			this.btnMainWIldPokemonEditor.Location = new global::System.Drawing.Point(278, 172);
			this.btnMainWIldPokemonEditor.Name = "btnMainWIldPokemonEditor";
			this.btnMainWIldPokemonEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainWIldPokemonEditor.TabIndex = 2;
			this.btnMainWIldPokemonEditor.Text = "野生ポケモン";
			this.btnMainWIldPokemonEditor.UseVisualStyleBackColor = true;
			this.btnMainInGameTradeEditor.Location = new global::System.Drawing.Point(144, 142);
			this.btnMainInGameTradeEditor.Name = "btnMainInGameTradeEditor";
			this.btnMainInGameTradeEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainInGameTradeEditor.TabIndex = 2;
			this.btnMainInGameTradeEditor.Text = "NPCポケモン交換";
			this.btnMainInGameTradeEditor.UseVisualStyleBackColor = true;
			this.btnMainRegionEditor.Location = new global::System.Drawing.Point(278, 82);
			this.btnMainRegionEditor.Name = "btnMainRegionEditor";
			this.btnMainRegionEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainRegionEditor.TabIndex = 2;
			this.btnMainRegionEditor.Text = "タウンマップ";
			this.btnMainRegionEditor.UseVisualStyleBackColor = true;
			this.btnMainTrainerDataEditor.Location = new global::System.Drawing.Point(144, 112);
			this.btnMainTrainerDataEditor.Name = "btnMainTrainerDataEditor";
			this.btnMainTrainerDataEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainTrainerDataEditor.TabIndex = 2;
			this.btnMainTrainerDataEditor.Text = "トレーナーデータ";
			this.btnMainTrainerDataEditor.UseVisualStyleBackColor = true;
			this.btnMainTrainerSpriteEditor.Location = new global::System.Drawing.Point(144, 82);
			this.btnMainTrainerSpriteEditor.Name = "btnMainTrainerSpriteEditor";
			this.btnMainTrainerSpriteEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainTrainerSpriteEditor.TabIndex = 2;
			this.btnMainTrainerSpriteEditor.Text = "トレーナー画像/肩書き";
			this.btnMainTrainerSpriteEditor.UseVisualStyleBackColor = true;
			this.btnMainTileAnimAndDoorEditor.Location = new global::System.Drawing.Point(278, 52);
			this.btnMainTileAnimAndDoorEditor.Name = "btnMainTileAnimAndDoorEditor";
			this.btnMainTileAnimAndDoorEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainTileAnimAndDoorEditor.TabIndex = 2;
			this.btnMainTileAnimAndDoorEditor.Text = "タイルアニメ＆ドア";
			this.btnMainTileAnimAndDoorEditor.UseVisualStyleBackColor = true;
			this.btnMainItemUseCoordinate.Location = new global::System.Drawing.Point(144, 52);
			this.btnMainItemUseCoordinate.Name = "btnMainItemUseCoordinate";
			this.btnMainItemUseCoordinate.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainItemUseCoordinate.TabIndex = 2;
			this.btnMainItemUseCoordinate.Text = "アイテム使用表示位置";
			this.btnMainItemUseCoordinate.UseVisualStyleBackColor = true;
			this.btnMainOverWorldEditor.Location = new global::System.Drawing.Point(278, 142);
			this.btnMainOverWorldEditor.Name = "btnMainOverWorldEditor";
			this.btnMainOverWorldEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainOverWorldEditor.TabIndex = 2;
			this.btnMainOverWorldEditor.Text = "歩行グラフィック";
			this.btnMainOverWorldEditor.UseVisualStyleBackColor = true;
			this.btnMainMapEditor.Location = new global::System.Drawing.Point(278, 22);
			this.btnMainMapEditor.Name = "btnMainMapEditor";
			this.btnMainMapEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainMapEditor.TabIndex = 2;
			this.btnMainMapEditor.Text = "マップ";
			this.btnMainMapEditor.UseVisualStyleBackColor = true;
			this.btnMainItemEditor.Location = new global::System.Drawing.Point(144, 22);
			this.btnMainItemEditor.Name = "btnMainItemEditor";
			this.btnMainItemEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainItemEditor.TabIndex = 2;
			this.btnMainItemEditor.Text = "アイテム";
			this.btnMainItemEditor.UseVisualStyleBackColor = true;
			this.btnMainPokedexListEditor.Location = new global::System.Drawing.Point(10, 172);
			this.btnMainPokedexListEditor.Name = "btnMainPokedexListEditor";
			this.btnMainPokedexListEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainPokedexListEditor.TabIndex = 2;
			this.btnMainPokedexListEditor.Text = "図鑑索引";
			this.btnMainPokedexListEditor.UseVisualStyleBackColor = true;
			this.btnMainHabitatEditor.Location = new global::System.Drawing.Point(10, 142);
			this.btnMainHabitatEditor.Name = "btnMainHabitatEditor";
			this.btnMainHabitatEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainHabitatEditor.TabIndex = 2;
			this.btnMainHabitatEditor.Text = "図鑑の生息地";
			this.btnMainHabitatEditor.UseVisualStyleBackColor = true;
			this.btnMainTmHmTutorEditor.Location = new global::System.Drawing.Point(10, 52);
			this.btnMainTmHmTutorEditor.Name = "btnMainTmHmTutorEditor";
			this.btnMainTmHmTutorEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainTmHmTutorEditor.TabIndex = 2;
			this.btnMainTmHmTutorEditor.Text = "技マシン/教え技";
			this.btnMainTmHmTutorEditor.UseVisualStyleBackColor = true;
			this.btnMainEggMoveEditor.Location = new global::System.Drawing.Point(10, 82);
			this.btnMainEggMoveEditor.Name = "btnMainEggMoveEditor";
			this.btnMainEggMoveEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainEggMoveEditor.TabIndex = 2;
			this.btnMainEggMoveEditor.Text = "タマゴ技";
			this.btnMainEggMoveEditor.UseVisualStyleBackColor = true;
			this.btnMainPokedexOrderEditor.Location = new global::System.Drawing.Point(10, 112);
			this.btnMainPokedexOrderEditor.Name = "btnMainPokedexOrderEditor";
			this.btnMainPokedexOrderEditor.Size = new global::System.Drawing.Size(128, 24);
			this.btnMainPokedexOrderEditor.TabIndex = 2;
			this.btnMainPokedexOrderEditor.Text = "図鑑番号";
			this.btnMainPokedexOrderEditor.UseVisualStyleBackColor = true;
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this.btnSaveRom.Location = new global::System.Drawing.Point(100, 12);
			this.btnSaveRom.Name = "btnSaveRom";
			this.btnSaveRom.Size = new global::System.Drawing.Size(80, 36);
			this.btnSaveRom.TabIndex = 0;
			this.btnSaveRom.Text = "ROMを保存";
			this.btnSaveRom.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(596, 277);
			base.Controls.Add(this.grpMainSelect);
			base.Controls.Add(this.grpRomInfo);
			base.Controls.Add(this.btnSaveRom);
			base.Controls.Add(this.btnLoadRom);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "MainForm";
			this.Text = "メイン画面";
			this.grpRomInfo.ResumeLayout(false);
			this.grpRomInfo.PerformLayout();
			this.grpMainSelect.ResumeLayout(false);
			this.grpMainSelect.PerformLayout();
			this.grpFreeSpaceFinder.ResumeLayout(false);
			this.grpFreeSpaceFinder.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudFreeSpaceFinderNeededByte).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x04000224 RID: 548
				private Button _btnLoadRom;
		private Button _btnMainPokemonEditor;
		private Button _btnMainTrainerSpriteEditor;
		private Button _btnMainItemEditor;
		private Button _btnMainHabitatEditor;
		private Button _btnMainTmHmTutorEditor;
		private Button _btnMainEggMoveEditor;
		private Button _btnMainPokedexOrderEditor;
		private Button _btnSaveRom;
		private Button _btnMainTrainerDataEditor;
		private Button _btnMainPokedexListEditor;
		private Button _btnMainWIldPokemonEditor;
		private Button _btnMainInGameTradeEditor;
		private Button _btnMainOverWorldEditor;
		private Button _btnMainItemUseCoordinate;
		private Button _btnMainHeldItemMailEditor;
		private Button _btnFreeSpaceFinderSearch;
		private Button _btnMainMapEditor;
        private global::System.ComponentModel.IContainer components;
	}
}
