namespace BochiBochiEditor
{
	// Token: 0x0200001D RID: 29
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class OverWorldEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x06000784 RID: 1924 RVA: 0x00039FD0 File Offset: 0x000381D0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000785 RID: 1925 RVA: 0x0003A020 File Offset: 0x00038220
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.OverWorldEditor));
			this.lblDataTableAddress = new global::System.Windows.Forms.Label();
			this.txtDataTableAddress = new global::System.Windows.Forms.TextBox();
			this.lstOverWorldDataList = new global::System.Windows.Forms.ListBox();
			this.lblPaletteTableAddress = new global::System.Windows.Forms.Label();
			this.txtPaletteTableAddress = new global::System.Windows.Forms.TextBox();
			this.grpData = new global::System.Windows.Forms.GroupBox();
			this.lblCreateNewData = new global::System.Windows.Forms.Label();
			this.txtCreateNewData = new global::System.Windows.Forms.TextBox();
			this.cmbDataPaletteId2 = new global::System.Windows.Forms.ComboBox();
			this.cmbDataPaletteId1 = new global::System.Windows.Forms.ComboBox();
			this.btnCreateNewData = new global::System.Windows.Forms.Button();
			this.nudUnUsedValue = new global::System.Windows.Forms.NumericUpDown();
			this.btnReload = new global::System.Windows.Forms.Button();
			this.txtDataMemoryAddress = new global::System.Windows.Forms.TextBox();
			this.txtDataSpriteTable = new global::System.Windows.Forms.TextBox();
			this.txtDataAnimationAddress = new global::System.Windows.Forms.TextBox();
			this.txtDataSizeAddress = new global::System.Windows.Forms.TextBox();
			this.txtDataLoadAddress = new global::System.Windows.Forms.TextBox();
			this.lblDataMemoryAddress = new global::System.Windows.Forms.Label();
			this.lblDataSpriteTable = new global::System.Windows.Forms.Label();
			this.lblDataAnimationAddress = new global::System.Windows.Forms.Label();
			this.lblDataSizeAddress = new global::System.Windows.Forms.Label();
			this.lblDataLoadAddress = new global::System.Windows.Forms.Label();
			this.cmbDataFootPrint = new global::System.Windows.Forms.ComboBox();
			this.lblDataFootPrintUnUsedValue = new global::System.Windows.Forms.Label();
			this.grpDataUnknownValue = new global::System.Windows.Forms.GroupBox();
			this.chkDataUnknownValue3 = new global::System.Windows.Forms.CheckBox();
			this.chkDataUnknownValue2 = new global::System.Windows.Forms.CheckBox();
			this.chkDataUnknownValue1 = new global::System.Windows.Forms.CheckBox();
			this.nudDataPaletteSlot = new global::System.Windows.Forms.NumericUpDown();
			this.nudDataLength = new global::System.Windows.Forms.NumericUpDown();
			this.lblDataLength = new global::System.Windows.Forms.Label();
			this.cmbDataSizeA = new global::System.Windows.Forms.ComboBox();
			this.lblDataPaletteSlot = new global::System.Windows.Forms.Label();
			this.lblDataSizeA = new global::System.Windows.Forms.Label();
			this.txtDataPadding = new global::System.Windows.Forms.TextBox();
			this.lblDataPadding = new global::System.Windows.Forms.Label();
			this.lblDataPaletteId = new global::System.Windows.Forms.Label();
			this.lblFontTableAddress = new global::System.Windows.Forms.Label();
			this.txtFontTableAddress = new global::System.Windows.Forms.TextBox();
			this.lblDataNum = new global::System.Windows.Forms.Label();
			this.nudDataMaxCount = new global::System.Windows.Forms.NumericUpDown();
			this.btnSave = new global::System.Windows.Forms.Button();
			this.grpSpritePreview = new global::System.Windows.Forms.GroupBox();
			this.nudSpriteFramePage = new global::System.Windows.Forms.NumericUpDown();
			this.picSpriteFramePreview = new global::System.Windows.Forms.PictureBox();
			this.btnSpriteFrameRight = new global::System.Windows.Forms.Button();
			this.btnSpriteFrameLeft = new global::System.Windows.Forms.Button();
			this.btnSpriteSheetImport = new global::System.Windows.Forms.Button();
			this.btnSpriteSheetExport = new global::System.Windows.Forms.Button();
			this.txtSpriteFrameAddress = new global::System.Windows.Forms.TextBox();
			this.grpCreateNewSpriteTable = new global::System.Windows.Forms.GroupBox();
			this.lblDataSizeB = new global::System.Windows.Forms.Label();
			this.cmbDataSizeB = new global::System.Windows.Forms.ComboBox();
			this.nudSpriteFrameLimit = new global::System.Windows.Forms.NumericUpDown();
			this.lblCreateNewSpriteSheetAddress = new global::System.Windows.Forms.Label();
			this.txtCreateNewSpriteSheetAddress = new global::System.Windows.Forms.TextBox();
			this.btnCreateNewSpriteTable = new global::System.Windows.Forms.Button();
			this.lblSpriteFrameLimit = new global::System.Windows.Forms.Label();
			this.grpFont = new global::System.Windows.Forms.GroupBox();
			this.lblFontId = new global::System.Windows.Forms.Label();
			this.cmbFontId = new global::System.Windows.Forms.ComboBox();
			this.grpPaletteIdList = new global::System.Windows.Forms.GroupBox();
			this.picPaletteIdPreview = new global::System.Windows.Forms.PictureBox();
			this.grpCreateNewPaletteId = new global::System.Windows.Forms.GroupBox();
			this.lblCreatePaletteId = new global::System.Windows.Forms.Label();
			this.lblCreatePaletteAddress = new global::System.Windows.Forms.Label();
			this.txtCreatePaletteAddress = new global::System.Windows.Forms.TextBox();
			this.btnCreateNewPalette = new global::System.Windows.Forms.Button();
			this.txtCreatePaletteId = new global::System.Windows.Forms.TextBox();
			this.txtPaletteIdAddress = new global::System.Windows.Forms.TextBox();
			this.cmbPaletteId = new global::System.Windows.Forms.ComboBox();
			this.lblPaletteId = new global::System.Windows.Forms.Label();
			this.grpData.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnUsedValue).BeginInit();
			this.grpDataUnknownValue.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataPaletteSlot).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataLength).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataMaxCount).BeginInit();
			this.grpSpritePreview.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpriteFramePage).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picSpriteFramePreview).BeginInit();
			this.grpCreateNewSpriteTable.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpriteFrameLimit).BeginInit();
			this.grpFont.SuspendLayout();
			this.grpPaletteIdList.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPaletteIdPreview).BeginInit();
			this.grpCreateNewPaletteId.SuspendLayout();
			base.SuspendLayout();
			this.lblDataTableAddress.AutoSize = true;
			this.lblDataTableAddress.Location = new global::System.Drawing.Point(16, 18);
			this.lblDataTableAddress.Name = "lblDataTableAddress";
			this.lblDataTableAddress.Size = new global::System.Drawing.Size(113, 12);
			this.lblDataTableAddress.TabIndex = 0;
			this.lblDataTableAddress.Text = "データテーブルアドレス :";
			this.txtDataTableAddress.Location = new global::System.Drawing.Point(142, 14);
			this.txtDataTableAddress.Name = "txtDataTableAddress";
			this.txtDataTableAddress.ReadOnly = true;
			this.txtDataTableAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataTableAddress.TabIndex = 1;
			this.lstOverWorldDataList.FormattingEnabled = true;
			this.lstOverWorldDataList.ItemHeight = 12;
			this.lstOverWorldDataList.Location = new global::System.Drawing.Point(16, 145);
			this.lstOverWorldDataList.Name = "lstOverWorldDataList";
			this.lstOverWorldDataList.Size = new global::System.Drawing.Size(120, 352);
			this.lstOverWorldDataList.TabIndex = 4;
			this.lblPaletteTableAddress.AutoSize = true;
			this.lblPaletteTableAddress.Location = new global::System.Drawing.Point(16, 42);
			this.lblPaletteTableAddress.Name = "lblPaletteTableAddress";
			this.lblPaletteTableAddress.Size = new global::System.Drawing.Size(119, 12);
			this.lblPaletteTableAddress.TabIndex = 0;
			this.lblPaletteTableAddress.Text = "パレットテーブルアドレス :";
			this.txtPaletteTableAddress.Location = new global::System.Drawing.Point(142, 38);
			this.txtPaletteTableAddress.Name = "txtPaletteTableAddress";
			this.txtPaletteTableAddress.ReadOnly = true;
			this.txtPaletteTableAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtPaletteTableAddress.TabIndex = 1;
			this.grpData.Controls.Add(this.lblCreateNewData);
			this.grpData.Controls.Add(this.txtCreateNewData);
			this.grpData.Controls.Add(this.cmbDataPaletteId2);
			this.grpData.Controls.Add(this.cmbDataPaletteId1);
			this.grpData.Controls.Add(this.btnCreateNewData);
			this.grpData.Controls.Add(this.nudUnUsedValue);
			this.grpData.Controls.Add(this.btnReload);
			this.grpData.Controls.Add(this.txtDataMemoryAddress);
			this.grpData.Controls.Add(this.txtDataSpriteTable);
			this.grpData.Controls.Add(this.txtDataAnimationAddress);
			this.grpData.Controls.Add(this.txtDataSizeAddress);
			this.grpData.Controls.Add(this.txtDataLoadAddress);
			this.grpData.Controls.Add(this.lblDataMemoryAddress);
			this.grpData.Controls.Add(this.lblDataSpriteTable);
			this.grpData.Controls.Add(this.lblDataAnimationAddress);
			this.grpData.Controls.Add(this.lblDataSizeAddress);
			this.grpData.Controls.Add(this.lblDataLoadAddress);
			this.grpData.Controls.Add(this.cmbDataFootPrint);
			this.grpData.Controls.Add(this.lblDataFootPrintUnUsedValue);
			this.grpData.Controls.Add(this.grpDataUnknownValue);
			this.grpData.Controls.Add(this.nudDataPaletteSlot);
			this.grpData.Controls.Add(this.nudDataLength);
			this.grpData.Controls.Add(this.lblDataLength);
			this.grpData.Controls.Add(this.cmbDataSizeA);
			this.grpData.Controls.Add(this.lblDataPaletteSlot);
			this.grpData.Controls.Add(this.lblDataSizeA);
			this.grpData.Controls.Add(this.txtDataPadding);
			this.grpData.Controls.Add(this.lblDataPadding);
			this.grpData.Controls.Add(this.lblDataPaletteId);
			this.grpData.Location = new global::System.Drawing.Point(148, 112);
			this.grpData.Name = "grpData";
			this.grpData.Size = new global::System.Drawing.Size(261, 386);
			this.grpData.TabIndex = 5;
			this.grpData.TabStop = false;
			this.grpData.Text = "データ";
			this.lblCreateNewData.AutoSize = true;
			this.lblCreateNewData.Location = new global::System.Drawing.Point(16, 333);
			this.lblCreateNewData.Name = "lblCreateNewData";
			this.lblCreateNewData.Size = new global::System.Drawing.Size(121, 12);
			this.lblCreateNewData.TabIndex = 19;
			this.lblCreateNewData.Text = "データの生成先アドレス :";
			this.txtCreateNewData.Location = new global::System.Drawing.Point(162, 329);
			this.txtCreateNewData.Name = "txtCreateNewData";
			this.txtCreateNewData.Size = new global::System.Drawing.Size(84, 19);
			this.txtCreateNewData.TabIndex = 18;
			this.cmbDataPaletteId2.FormattingEnabled = true;
			this.cmbDataPaletteId2.Location = new global::System.Drawing.Point(176, 41);
			this.cmbDataPaletteId2.Name = "cmbDataPaletteId2";
			this.cmbDataPaletteId2.Size = new global::System.Drawing.Size(68, 20);
			this.cmbDataPaletteId2.TabIndex = 16;
			this.cmbDataPaletteId1.FormattingEnabled = true;
			this.cmbDataPaletteId1.Location = new global::System.Drawing.Point(104, 41);
			this.cmbDataPaletteId1.Name = "cmbDataPaletteId1";
			this.cmbDataPaletteId1.Size = new global::System.Drawing.Size(68, 20);
			this.cmbDataPaletteId1.TabIndex = 15;
			this.btnCreateNewData.Location = new global::System.Drawing.Point(16, 351);
			this.btnCreateNewData.Name = "btnCreateNewData";
			this.btnCreateNewData.Size = new global::System.Drawing.Size(230, 23);
			this.btnCreateNewData.TabIndex = 17;
			this.btnCreateNewData.Text = "新しいデータを生成";
			this.btnCreateNewData.UseVisualStyleBackColor = true;
			this.nudUnUsedValue.Location = new global::System.Drawing.Point(176, 192);
			global::System.Windows.Forms.NumericUpDown nudUnUsedValue = this.nudUnUsedValue;
			int[] array = new int[4];
			array[0] = 65535;
			nudUnUsedValue.Maximum = new decimal(array);
			this.nudUnUsedValue.Name = "nudUnUsedValue";
			this.nudUnUsedValue.Size = new global::System.Drawing.Size(68, 19);
			this.nudUnUsedValue.TabIndex = 14;
			this.btnReload.Location = new global::System.Drawing.Point(174, 16);
			this.btnReload.Name = "btnReload";
			this.btnReload.Size = new global::System.Drawing.Size(72, 23);
			this.btnReload.TabIndex = 13;
			this.btnReload.Text = "変更を反映";
			this.btnReload.UseVisualStyleBackColor = true;
			this.txtDataMemoryAddress.Location = new global::System.Drawing.Point(104, 302);
			this.txtDataMemoryAddress.Name = "txtDataMemoryAddress";
			this.txtDataMemoryAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataMemoryAddress.TabIndex = 12;
			this.txtDataSpriteTable.Location = new global::System.Drawing.Point(104, 280);
			this.txtDataSpriteTable.Name = "txtDataSpriteTable";
			this.txtDataSpriteTable.ReadOnly = true;
			this.txtDataSpriteTable.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataSpriteTable.TabIndex = 12;
			this.txtDataAnimationAddress.Location = new global::System.Drawing.Point(104, 258);
			this.txtDataAnimationAddress.Name = "txtDataAnimationAddress";
			this.txtDataAnimationAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataAnimationAddress.TabIndex = 12;
			this.txtDataSizeAddress.Location = new global::System.Drawing.Point(104, 236);
			this.txtDataSizeAddress.Name = "txtDataSizeAddress";
			this.txtDataSizeAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataSizeAddress.TabIndex = 12;
			this.txtDataLoadAddress.Location = new global::System.Drawing.Point(104, 214);
			this.txtDataLoadAddress.Name = "txtDataLoadAddress";
			this.txtDataLoadAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtDataLoadAddress.TabIndex = 12;
			this.lblDataMemoryAddress.AutoSize = true;
			this.lblDataMemoryAddress.Location = new global::System.Drawing.Point(16, 307);
			this.lblDataMemoryAddress.Name = "lblDataMemoryAddress";
			this.lblDataMemoryAddress.Size = new global::System.Drawing.Size(71, 12);
			this.lblDataMemoryAddress.TabIndex = 11;
			this.lblDataMemoryAddress.Text = "メモリアドレス :";
			this.lblDataSpriteTable.AutoSize = true;
			this.lblDataSpriteTable.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.lblDataSpriteTable.Location = new global::System.Drawing.Point(16, 284);
			this.lblDataSpriteTable.Name = "lblDataSpriteTable";
			this.lblDataSpriteTable.Size = new global::System.Drawing.Size(73, 12);
			this.lblDataSpriteTable.TabIndex = 11;
			this.lblDataSpriteTable.Text = "画像テーブル :";
			this.lblDataAnimationAddress.AutoSize = true;
			this.lblDataAnimationAddress.Location = new global::System.Drawing.Point(16, 262);
			this.lblDataAnimationAddress.Name = "lblDataAnimationAddress";
			this.lblDataAnimationAddress.Size = new global::System.Drawing.Size(73, 12);
			this.lblDataAnimationAddress.TabIndex = 11;
			this.lblDataAnimationAddress.Text = "アニメアドレス :";
			this.lblDataSizeAddress.AutoSize = true;
			this.lblDataSizeAddress.Location = new global::System.Drawing.Point(16, 240);
			this.lblDataSizeAddress.Name = "lblDataSizeAddress";
			this.lblDataSizeAddress.Size = new global::System.Drawing.Size(76, 12);
			this.lblDataSizeAddress.TabIndex = 11;
			this.lblDataSizeAddress.Text = "サイズアドレス :";
			this.lblDataLoadAddress.AutoSize = true;
			this.lblDataLoadAddress.Location = new global::System.Drawing.Point(16, 218);
			this.lblDataLoadAddress.Name = "lblDataLoadAddress";
			this.lblDataLoadAddress.Size = new global::System.Drawing.Size(75, 12);
			this.lblDataLoadAddress.TabIndex = 11;
			this.lblDataLoadAddress.Text = "ロードアドレス :";
			this.cmbDataFootPrint.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbDataFootPrint.FormattingEnabled = true;
			this.cmbDataFootPrint.Location = new global::System.Drawing.Point(104, 191);
			this.cmbDataFootPrint.Name = "cmbDataFootPrint";
			this.cmbDataFootPrint.Size = new global::System.Drawing.Size(68, 20);
			this.cmbDataFootPrint.TabIndex = 10;
			this.lblDataFootPrintUnUsedValue.AutoSize = true;
			this.lblDataFootPrintUnUsedValue.Location = new global::System.Drawing.Point(16, 196);
			this.lblDataFootPrintUnUsedValue.Name = "lblDataFootPrintUnUsedValue";
			this.lblDataFootPrintUnUsedValue.Size = new global::System.Drawing.Size(82, 12);
			this.lblDataFootPrintUnUsedValue.TabIndex = 9;
			this.lblDataFootPrintUnUsedValue.Text = "足跡/未使用? :";
			this.grpDataUnknownValue.Controls.Add(this.chkDataUnknownValue3);
			this.grpDataUnknownValue.Controls.Add(this.chkDataUnknownValue2);
			this.grpDataUnknownValue.Controls.Add(this.chkDataUnknownValue1);
			this.grpDataUnknownValue.Location = new global::System.Drawing.Point(10, 138);
			this.grpDataUnknownValue.Name = "grpDataUnknownValue";
			this.grpDataUnknownValue.Size = new global::System.Drawing.Size(240, 47);
			this.grpDataUnknownValue.TabIndex = 8;
			this.grpDataUnknownValue.TabStop = false;
			this.grpDataUnknownValue.Text = "不明値";
			this.chkDataUnknownValue3.AutoSize = true;
			this.chkDataUnknownValue3.Location = new global::System.Drawing.Point(164, 20);
			this.chkDataUnknownValue3.Name = "chkDataUnknownValue3";
			this.chkDataUnknownValue3.Size = new global::System.Drawing.Size(66, 16);
			this.chkDataUnknownValue3.TabIndex = 7;
			this.chkDataUnknownValue3.Text = "不明値3";
			this.chkDataUnknownValue3.UseVisualStyleBackColor = true;
			this.chkDataUnknownValue2.AutoSize = true;
			this.chkDataUnknownValue2.Location = new global::System.Drawing.Point(90, 20);
			this.chkDataUnknownValue2.Name = "chkDataUnknownValue2";
			this.chkDataUnknownValue2.Size = new global::System.Drawing.Size(66, 16);
			this.chkDataUnknownValue2.TabIndex = 7;
			this.chkDataUnknownValue2.Text = "不明値2";
			this.chkDataUnknownValue2.UseVisualStyleBackColor = true;
			this.chkDataUnknownValue1.AutoSize = true;
			this.chkDataUnknownValue1.Location = new global::System.Drawing.Point(16, 20);
			this.chkDataUnknownValue1.Name = "chkDataUnknownValue1";
			this.chkDataUnknownValue1.Size = new global::System.Drawing.Size(66, 16);
			this.chkDataUnknownValue1.TabIndex = 7;
			this.chkDataUnknownValue1.Text = "不明値1";
			this.chkDataUnknownValue1.UseVisualStyleBackColor = true;
			this.nudDataPaletteSlot.Location = new global::System.Drawing.Point(104, 109);
			global::System.Windows.Forms.NumericUpDown nudDataPaletteSlot = this.nudDataPaletteSlot;
			int[] array2 = new int[4];
			array2[0] = 15;
			nudDataPaletteSlot.Maximum = new decimal(array2);
			this.nudDataPaletteSlot.Name = "nudDataPaletteSlot";
			this.nudDataPaletteSlot.Size = new global::System.Drawing.Size(68, 19);
			this.nudDataPaletteSlot.TabIndex = 6;
			this.nudDataLength.Location = new global::System.Drawing.Point(104, 64);
			global::System.Windows.Forms.NumericUpDown nudDataLength = this.nudDataLength;
			int[] array3 = new int[4];
			array3[0] = 65535;
			nudDataLength.Maximum = new decimal(array3);
			this.nudDataLength.Name = "nudDataLength";
			this.nudDataLength.Size = new global::System.Drawing.Size(68, 19);
			this.nudDataLength.TabIndex = 5;
			this.lblDataLength.AutoSize = true;
			this.lblDataLength.Location = new global::System.Drawing.Point(16, 68);
			this.lblDataLength.Name = "lblDataLength";
			this.lblDataLength.Size = new global::System.Drawing.Size(56, 12);
			this.lblDataLength.TabIndex = 4;
			this.lblDataLength.Text = "データ長? :";
			this.cmbDataSizeA.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbDataSizeA.Enabled = false;
			this.cmbDataSizeA.FormattingEnabled = true;
			this.cmbDataSizeA.Location = new global::System.Drawing.Point(104, 86);
			this.cmbDataSizeA.Name = "cmbDataSizeA";
			this.cmbDataSizeA.Size = new global::System.Drawing.Size(140, 20);
			this.cmbDataSizeA.TabIndex = 3;
			this.lblDataPaletteSlot.AutoSize = true;
			this.lblDataPaletteSlot.Location = new global::System.Drawing.Point(16, 113);
			this.lblDataPaletteSlot.Name = "lblDataPaletteSlot";
			this.lblDataPaletteSlot.Size = new global::System.Drawing.Size(78, 12);
			this.lblDataPaletteSlot.TabIndex = 2;
			this.lblDataPaletteSlot.Text = "パレットスロット :";
			this.lblDataSizeA.AutoSize = true;
			this.lblDataSizeA.Location = new global::System.Drawing.Point(16, 90);
			this.lblDataSizeA.Name = "lblDataSizeA";
			this.lblDataSizeA.Size = new global::System.Drawing.Size(64, 12);
			this.lblDataSizeA.TabIndex = 2;
			this.lblDataSizeA.Text = "画像サイズ :";
			this.txtDataPadding.Location = new global::System.Drawing.Point(104, 19);
			this.txtDataPadding.Name = "txtDataPadding";
			this.txtDataPadding.ReadOnly = true;
			this.txtDataPadding.Size = new global::System.Drawing.Size(68, 19);
			this.txtDataPadding.TabIndex = 1;
			this.lblDataPadding.AutoSize = true;
			this.lblDataPadding.Location = new global::System.Drawing.Point(16, 23);
			this.lblDataPadding.Name = "lblDataPadding";
			this.lblDataPadding.Size = new global::System.Drawing.Size(56, 12);
			this.lblDataPadding.TabIndex = 0;
			this.lblDataPadding.Text = "パディング :";
			this.lblDataPaletteId.AutoSize = true;
			this.lblDataPaletteId.Location = new global::System.Drawing.Point(16, 45);
			this.lblDataPaletteId.Name = "lblDataPaletteId";
			this.lblDataPaletteId.Size = new global::System.Drawing.Size(56, 12);
			this.lblDataPaletteId.TabIndex = 0;
			this.lblDataPaletteId.Text = "パレットID :";
			this.lblFontTableAddress.AutoSize = true;
			this.lblFontTableAddress.Location = new global::System.Drawing.Point(16, 66);
			this.lblFontTableAddress.Name = "lblFontTableAddress";
			this.lblFontTableAddress.Size = new global::System.Drawing.Size(118, 12);
			this.lblFontTableAddress.TabIndex = 0;
			this.lblFontTableAddress.Text = "フォントテーブルアドレス :";
			this.txtFontTableAddress.Location = new global::System.Drawing.Point(142, 62);
			this.txtFontTableAddress.Name = "txtFontTableAddress";
			this.txtFontTableAddress.ReadOnly = true;
			this.txtFontTableAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtFontTableAddress.TabIndex = 1;
			this.lblDataNum.AutoSize = true;
			this.lblDataNum.Location = new global::System.Drawing.Point(16, 90);
			this.lblDataNum.Name = "lblDataNum";
			this.lblDataNum.Size = new global::System.Drawing.Size(152, 12);
			this.lblDataNum.TabIndex = 6;
			this.lblDataNum.Text = "最大読み込み数（0x5EBA0） :";
			this.nudDataMaxCount.Enabled = false;
			this.nudDataMaxCount.Location = new global::System.Drawing.Point(178, 86);
			global::System.Windows.Forms.NumericUpDown nudDataMaxCount = this.nudDataMaxCount;
			int[] array4 = new int[4];
			array4[0] = 255;
			nudDataMaxCount.Maximum = new decimal(array4);
			this.nudDataMaxCount.Name = "nudDataMaxCount";
			this.nudDataMaxCount.Size = new global::System.Drawing.Size(48, 19);
			this.nudDataMaxCount.TabIndex = 7;
			this.btnSave.Location = new global::System.Drawing.Point(16, 112);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(120, 23);
			this.btnSave.TabIndex = 13;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			this.grpSpritePreview.Controls.Add(this.nudSpriteFramePage);
			this.grpSpritePreview.Controls.Add(this.picSpriteFramePreview);
			this.grpSpritePreview.Controls.Add(this.btnSpriteFrameRight);
			this.grpSpritePreview.Controls.Add(this.btnSpriteFrameLeft);
			this.grpSpritePreview.Controls.Add(this.btnSpriteSheetImport);
			this.grpSpritePreview.Controls.Add(this.btnSpriteSheetExport);
			this.grpSpritePreview.Controls.Add(this.txtSpriteFrameAddress);
			this.grpSpritePreview.Location = new global::System.Drawing.Point(420, 52);
			this.grpSpritePreview.Name = "grpSpritePreview";
			this.grpSpritePreview.Size = new global::System.Drawing.Size(376, 170);
			this.grpSpritePreview.TabIndex = 8;
			this.grpSpritePreview.TabStop = false;
			this.grpSpritePreview.Text = "プレビュー";
			this.nudSpriteFramePage.Enabled = false;
			this.nudSpriteFramePage.Location = new global::System.Drawing.Point(278, 134);
			global::System.Windows.Forms.NumericUpDown nudSpriteFramePage = this.nudSpriteFramePage;
			int[] array5 = new int[4];
			array5[0] = 255;
			nudSpriteFramePage.Maximum = new decimal(array5);
			this.nudSpriteFramePage.Name = "nudSpriteFramePage";
			this.nudSpriteFramePage.Size = new global::System.Drawing.Size(85, 19);
			this.nudSpriteFramePage.TabIndex = 4;
			this.picSpriteFramePreview.Location = new global::System.Drawing.Point(14, 24);
			this.picSpriteFramePreview.Name = "picSpriteFramePreview";
			this.picSpriteFramePreview.Size = new global::System.Drawing.Size(256, 128);
			this.picSpriteFramePreview.TabIndex = 15;
			this.picSpriteFramePreview.TabStop = false;
			this.btnSpriteFrameRight.Location = new global::System.Drawing.Point(322, 106);
			this.btnSpriteFrameRight.Name = "btnSpriteFrameRight";
			this.btnSpriteFrameRight.Size = new global::System.Drawing.Size(40, 23);
			this.btnSpriteFrameRight.TabIndex = 14;
			this.btnSpriteFrameRight.Text = ">";
			this.btnSpriteFrameRight.UseVisualStyleBackColor = true;
			this.btnSpriteFrameLeft.Location = new global::System.Drawing.Point(278, 106);
			this.btnSpriteFrameLeft.Name = "btnSpriteFrameLeft";
			this.btnSpriteFrameLeft.Size = new global::System.Drawing.Size(40, 23);
			this.btnSpriteFrameLeft.TabIndex = 14;
			this.btnSpriteFrameLeft.Text = "<";
			this.btnSpriteFrameLeft.UseVisualStyleBackColor = true;
			this.btnSpriteSheetImport.Location = new global::System.Drawing.Point(278, 23);
			this.btnSpriteSheetImport.Name = "btnSpriteSheetImport";
			this.btnSpriteSheetImport.Size = new global::System.Drawing.Size(84, 23);
			this.btnSpriteSheetImport.TabIndex = 4;
			this.btnSpriteSheetImport.Text = "インポート";
			this.btnSpriteSheetImport.UseVisualStyleBackColor = true;
			this.btnSpriteSheetExport.Location = new global::System.Drawing.Point(278, 50);
			this.btnSpriteSheetExport.Name = "btnSpriteSheetExport";
			this.btnSpriteSheetExport.Size = new global::System.Drawing.Size(84, 23);
			this.btnSpriteSheetExport.TabIndex = 4;
			this.btnSpriteSheetExport.Text = "エクスポート";
			this.btnSpriteSheetExport.UseVisualStyleBackColor = true;
			this.txtSpriteFrameAddress.Location = new global::System.Drawing.Point(278, 82);
			this.txtSpriteFrameAddress.Name = "txtSpriteFrameAddress";
			this.txtSpriteFrameAddress.ReadOnly = true;
			this.txtSpriteFrameAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtSpriteFrameAddress.TabIndex = 2;
			this.grpCreateNewSpriteTable.Controls.Add(this.lblDataSizeB);
			this.grpCreateNewSpriteTable.Controls.Add(this.cmbDataSizeB);
			this.grpCreateNewSpriteTable.Controls.Add(this.nudSpriteFrameLimit);
			this.grpCreateNewSpriteTable.Controls.Add(this.lblCreateNewSpriteSheetAddress);
			this.grpCreateNewSpriteTable.Controls.Add(this.txtCreateNewSpriteSheetAddress);
			this.grpCreateNewSpriteTable.Controls.Add(this.btnCreateNewSpriteTable);
			this.grpCreateNewSpriteTable.Controls.Add(this.lblSpriteFrameLimit);
			this.grpCreateNewSpriteTable.Location = new global::System.Drawing.Point(420, 228);
			this.grpCreateNewSpriteTable.Name = "grpCreateNewSpriteTable";
			this.grpCreateNewSpriteTable.Size = new global::System.Drawing.Size(298, 126);
			this.grpCreateNewSpriteTable.TabIndex = 16;
			this.grpCreateNewSpriteTable.TabStop = false;
			this.grpCreateNewSpriteTable.Text = "新しい画像テーブルを生成";
			this.lblDataSizeB.AutoSize = true;
			this.lblDataSizeB.Location = new global::System.Drawing.Point(20, 70);
			this.lblDataSizeB.Name = "lblDataSizeB";
			this.lblDataSizeB.Size = new global::System.Drawing.Size(64, 12);
			this.lblDataSizeB.TabIndex = 19;
			this.lblDataSizeB.Text = "画像サイズ :";
			this.cmbDataSizeB.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbDataSizeB.FormattingEnabled = true;
			this.cmbDataSizeB.Location = new global::System.Drawing.Point(136, 67);
			this.cmbDataSizeB.Name = "cmbDataSizeB";
			this.cmbDataSizeB.Size = new global::System.Drawing.Size(140, 20);
			this.cmbDataSizeB.TabIndex = 18;
			this.nudSpriteFrameLimit.Location = new global::System.Drawing.Point(192, 44);
			global::System.Windows.Forms.NumericUpDown nudSpriteFrameLimit = this.nudSpriteFrameLimit;
			int[] array6 = new int[4];
			array6[0] = 255;
			nudSpriteFrameLimit.Maximum = new decimal(array6);
			global::System.Windows.Forms.NumericUpDown nudSpriteFrameLimit2 = this.nudSpriteFrameLimit;
			int[] array7 = new int[4];
			array7[0] = 1;
			nudSpriteFrameLimit2.Minimum = new decimal(array7);
			this.nudSpriteFrameLimit.Name = "nudSpriteFrameLimit";
			this.nudSpriteFrameLimit.Size = new global::System.Drawing.Size(84, 19);
			this.nudSpriteFrameLimit.TabIndex = 17;
			global::System.Windows.Forms.NumericUpDown nudSpriteFrameLimit3 = this.nudSpriteFrameLimit;
			int[] array8 = new int[4];
			array8[0] = 1;
			nudSpriteFrameLimit3.Value = new decimal(array8);
			this.lblCreateNewSpriteSheetAddress.AutoSize = true;
			this.lblCreateNewSpriteSheetAddress.Location = new global::System.Drawing.Point(20, 26);
			this.lblCreateNewSpriteSheetAddress.Name = "lblCreateNewSpriteSheetAddress";
			this.lblCreateNewSpriteSheetAddress.Size = new global::System.Drawing.Size(155, 12);
			this.lblCreateNewSpriteSheetAddress.TabIndex = 16;
			this.lblCreateNewSpriteSheetAddress.Text = "画像テーブルの生成先アドレス :";
			this.txtCreateNewSpriteSheetAddress.Location = new global::System.Drawing.Point(192, 22);
			this.txtCreateNewSpriteSheetAddress.Name = "txtCreateNewSpriteSheetAddress";
			this.txtCreateNewSpriteSheetAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtCreateNewSpriteSheetAddress.TabIndex = 2;
			this.btnCreateNewSpriteTable.Location = new global::System.Drawing.Point(22, 90);
			this.btnCreateNewSpriteTable.Name = "btnCreateNewSpriteTable";
			this.btnCreateNewSpriteTable.Size = new global::System.Drawing.Size(254, 23);
			this.btnCreateNewSpriteTable.TabIndex = 13;
			this.btnCreateNewSpriteTable.Text = "新しい画像テーブルを生成";
			this.btnCreateNewSpriteTable.UseVisualStyleBackColor = true;
			this.lblSpriteFrameLimit.AutoSize = true;
			this.lblSpriteFrameLimit.Location = new global::System.Drawing.Point(20, 48);
			this.lblSpriteFrameLimit.Name = "lblSpriteFrameLimit";
			this.lblSpriteFrameLimit.Size = new global::System.Drawing.Size(138, 12);
			this.lblSpriteFrameLimit.TabIndex = 0;
			this.lblSpriteFrameLimit.Text = "画像テーブルのエントリー数 :";
			this.grpFont.Controls.Add(this.lblFontId);
			this.grpFont.Controls.Add(this.cmbFontId);
			this.grpFont.Location = new global::System.Drawing.Point(238, 52);
			this.grpFont.Name = "grpFont";
			this.grpFont.Size = new global::System.Drawing.Size(171, 54);
			this.grpFont.TabIndex = 9;
			this.grpFont.TabStop = false;
			this.grpFont.Text = "フォント";
			this.lblFontId.AutoSize = true;
			this.lblFontId.Location = new global::System.Drawing.Point(10, 25);
			this.lblFontId.Name = "lblFontId";
			this.lblFontId.Size = new global::System.Drawing.Size(55, 12);
			this.lblFontId.TabIndex = 2;
			this.lblFontId.Text = "フォントID :";
			this.cmbFontId.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbFontId.FormattingEnabled = true;
			this.cmbFontId.Items.AddRange(new object[]
			{
				"00 - 男性", "01 - 女性", "02 - ポケモン", "03 - その他", "04", "05", "06", "07", "08", "09",
				"0A", "0B", "0C", "0D", "0E", "0F"
			});
			this.cmbFontId.Location = new global::System.Drawing.Point(70, 20);
			this.cmbFontId.Name = "cmbFontId";
			this.cmbFontId.Size = new global::System.Drawing.Size(86, 20);
			this.cmbFontId.TabIndex = 1;
			this.grpPaletteIdList.Controls.Add(this.picPaletteIdPreview);
			this.grpPaletteIdList.Controls.Add(this.grpCreateNewPaletteId);
			this.grpPaletteIdList.Controls.Add(this.txtPaletteIdAddress);
			this.grpPaletteIdList.Controls.Add(this.cmbPaletteId);
			this.grpPaletteIdList.Controls.Add(this.lblPaletteId);
			this.grpPaletteIdList.Location = new global::System.Drawing.Point(420, 358);
			this.grpPaletteIdList.Name = "grpPaletteIdList";
			this.grpPaletteIdList.Size = new global::System.Drawing.Size(376, 140);
			this.grpPaletteIdList.TabIndex = 10;
			this.grpPaletteIdList.TabStop = false;
			this.grpPaletteIdList.Text = "パレットIDリスト";
			this.picPaletteIdPreview.Location = new global::System.Drawing.Point(276, 21);
			this.picPaletteIdPreview.Name = "picPaletteIdPreview";
			this.picPaletteIdPreview.Size = new global::System.Drawing.Size(64, 16);
			this.picPaletteIdPreview.TabIndex = 7;
			this.picPaletteIdPreview.TabStop = false;
			this.grpCreateNewPaletteId.Controls.Add(this.lblCreatePaletteId);
			this.grpCreateNewPaletteId.Controls.Add(this.lblCreatePaletteAddress);
			this.grpCreateNewPaletteId.Controls.Add(this.txtCreatePaletteAddress);
			this.grpCreateNewPaletteId.Controls.Add(this.btnCreateNewPalette);
			this.grpCreateNewPaletteId.Controls.Add(this.txtCreatePaletteId);
			this.grpCreateNewPaletteId.Location = new global::System.Drawing.Point(14, 48);
			this.grpCreateNewPaletteId.Name = "grpCreateNewPaletteId";
			this.grpCreateNewPaletteId.Size = new global::System.Drawing.Size(284, 78);
			this.grpCreateNewPaletteId.TabIndex = 6;
			this.grpCreateNewPaletteId.TabStop = false;
			this.grpCreateNewPaletteId.Text = "パレットIDを追加";
			this.lblCreatePaletteId.AutoSize = true;
			this.lblCreatePaletteId.Location = new global::System.Drawing.Point(14, 26);
			this.lblCreatePaletteId.Name = "lblCreatePaletteId";
			this.lblCreatePaletteId.Size = new global::System.Drawing.Size(56, 12);
			this.lblCreatePaletteId.TabIndex = 10;
			this.lblCreatePaletteId.Text = "パレットID :";
			this.lblCreatePaletteAddress.AutoSize = true;
			this.lblCreatePaletteAddress.Location = new global::System.Drawing.Point(14, 50);
			this.lblCreatePaletteAddress.Name = "lblCreatePaletteAddress";
			this.lblCreatePaletteAddress.Size = new global::System.Drawing.Size(47, 12);
			this.lblCreatePaletteAddress.TabIndex = 10;
			this.lblCreatePaletteAddress.Text = "アドレス :";
			this.txtCreatePaletteAddress.Location = new global::System.Drawing.Point(76, 46);
			this.txtCreatePaletteAddress.Name = "txtCreatePaletteAddress";
			this.txtCreatePaletteAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtCreatePaletteAddress.TabIndex = 5;
			this.btnCreateNewPalette.Location = new global::System.Drawing.Point(169, 44);
			this.btnCreateNewPalette.Name = "btnCreateNewPalette";
			this.btnCreateNewPalette.Size = new global::System.Drawing.Size(84, 23);
			this.btnCreateNewPalette.TabIndex = 9;
			this.btnCreateNewPalette.Text = "追加";
			this.btnCreateNewPalette.UseVisualStyleBackColor = true;
			this.txtCreatePaletteId.Location = new global::System.Drawing.Point(76, 22);
			this.txtCreatePaletteId.Name = "txtCreatePaletteId";
			this.txtCreatePaletteId.Size = new global::System.Drawing.Size(84, 19);
			this.txtCreatePaletteId.TabIndex = 5;
			this.txtPaletteIdAddress.Location = new global::System.Drawing.Point(183, 20);
			this.txtPaletteIdAddress.Name = "txtPaletteIdAddress";
			this.txtPaletteIdAddress.ReadOnly = true;
			this.txtPaletteIdAddress.Size = new global::System.Drawing.Size(84, 19);
			this.txtPaletteIdAddress.TabIndex = 5;
			this.cmbPaletteId.FormattingEnabled = true;
			this.cmbPaletteId.Location = new global::System.Drawing.Point(90, 19);
			this.cmbPaletteId.Name = "cmbPaletteId";
			this.cmbPaletteId.Size = new global::System.Drawing.Size(84, 20);
			this.cmbPaletteId.TabIndex = 4;
			this.lblPaletteId.AutoSize = true;
			this.lblPaletteId.Location = new global::System.Drawing.Point(20, 23);
			this.lblPaletteId.Name = "lblPaletteId";
			this.lblPaletteId.Size = new global::System.Drawing.Size(56, 12);
			this.lblPaletteId.TabIndex = 3;
			this.lblPaletteId.Text = "パレットID :";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(814, 513);
			base.Controls.Add(this.grpCreateNewSpriteTable);
			base.Controls.Add(this.btnSave);
			base.Controls.Add(this.grpPaletteIdList);
			base.Controls.Add(this.grpFont);
			base.Controls.Add(this.grpSpritePreview);
			base.Controls.Add(this.nudDataMaxCount);
			base.Controls.Add(this.lblDataNum);
			base.Controls.Add(this.grpData);
			base.Controls.Add(this.lstOverWorldDataList);
			base.Controls.Add(this.txtFontTableAddress);
			base.Controls.Add(this.txtPaletteTableAddress);
			base.Controls.Add(this.txtDataTableAddress);
			base.Controls.Add(this.lblFontTableAddress);
			base.Controls.Add(this.lblPaletteTableAddress);
			base.Controls.Add(this.lblDataTableAddress);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "OverWorldEditor";
			this.Text = "歩行グラフィック";
			this.grpData.ResumeLayout(false);
			this.grpData.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudUnUsedValue).EndInit();
			this.grpDataUnknownValue.ResumeLayout(false);
			this.grpDataUnknownValue.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataPaletteSlot).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataLength).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudDataMaxCount).EndInit();
			this.grpSpritePreview.ResumeLayout(false);
			this.grpSpritePreview.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpriteFramePage).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picSpriteFramePreview).EndInit();
			this.grpCreateNewSpriteTable.ResumeLayout(false);
			this.grpCreateNewSpriteTable.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.nudSpriteFrameLimit).EndInit();
			this.grpFont.ResumeLayout(false);
			this.grpFont.PerformLayout();
			this.grpPaletteIdList.ResumeLayout(false);
			this.grpPaletteIdList.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPaletteIdPreview).EndInit();
			this.grpCreateNewPaletteId.ResumeLayout(false);
			this.grpCreateNewPaletteId.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000425 RID: 1061
				private ListBox _lstOverWorldDataList;
		private Button _btnSave;
		private Button _btnSpriteSheetExport;
		private ComboBox _cmbPaletteId;
		private Button _btnReload;
		private Button _btnCreateNewSpriteTable;
		private Button _btnSpriteFrameRight;
		private Button _btnSpriteFrameLeft;
		private Button _btnCreateNewPalette;
		private Button _btnSpriteSheetImport;
		private Button _btnCreateNewData;
		private ComboBox _cmbFontId;
        private global::System.ComponentModel.IContainer components;
	}
}
