namespace BochiBochiEditor
{
	// Token: 0x02000028 RID: 40
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TrainerDataEditor : global::System.Windows.Forms.Form
	{
		// Token: 0x06000BC7 RID: 3015 RVA: 0x00058338 File Offset: 0x00056538
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000BC8 RID: 3016 RVA: 0x00058388 File Offset: 0x00056588
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BochiBochiEditor.TrainerDataEditor));
			this.lstTrainerIdName = new global::System.Windows.Forms.ListBox();
			this.grpTrainerData = new global::System.Windows.Forms.GroupBox();
			this.cmbTrainerDataType = new global::System.Windows.Forms.ComboBox();
			this.lblTrainerDataType = new global::System.Windows.Forms.Label();
			this.lblTrainerClass = new global::System.Windows.Forms.Label();
			this.cmbTrainerClass = new global::System.Windows.Forms.ComboBox();
			this.grpTrainerItem = new global::System.Windows.Forms.GroupBox();
			this.cmbTrainerItem4 = new global::System.Windows.Forms.ComboBox();
			this.cmbTrainerItem3 = new global::System.Windows.Forms.ComboBox();
			this.cmbTrainerItem2 = new global::System.Windows.Forms.ComboBox();
			this.cmbTrainerItem1 = new global::System.Windows.Forms.ComboBox();
			this.picTrainerItem4 = new global::System.Windows.Forms.PictureBox();
			this.picTrainerItem3 = new global::System.Windows.Forms.PictureBox();
			this.picTrainerItem2 = new global::System.Windows.Forms.PictureBox();
			this.picTrainerItem1 = new global::System.Windows.Forms.PictureBox();
			this.nudTrainerUnknownValue = new global::System.Windows.Forms.NumericUpDown();
			this.lblTrainerUnknownValue = new global::System.Windows.Forms.Label();
			this.lblPokemonDataNum = new global::System.Windows.Forms.Label();
			this.nudPokemonDataNum = new global::System.Windows.Forms.NumericUpDown();
			this.txtPokemonDataAddress = new global::System.Windows.Forms.TextBox();
			this.lblPokemonDataAddress = new global::System.Windows.Forms.Label();
			this.btnChangeTrainerName = new global::System.Windows.Forms.Button();
			this.lblTrainerAi = new global::System.Windows.Forms.Label();
			this.chkDoubleBattle = new global::System.Windows.Forms.CheckBox();
			this.lblIntroMusic = new global::System.Windows.Forms.Label();
			this.nudTrainerAi = new global::System.Windows.Forms.NumericUpDown();
			this.nudIntroMusic = new global::System.Windows.Forms.NumericUpDown();
			this.lblTrainerName = new global::System.Windows.Forms.Label();
			this.txtTrainerName = new global::System.Windows.Forms.TextBox();
			this.nudTrainerSprite = new global::System.Windows.Forms.NumericUpDown();
			this.picTrainerSprite = new global::System.Windows.Forms.PictureBox();
			this.grpPokemonData = new global::System.Windows.Forms.GroupBox();
			this.btnChangePokemonData = new global::System.Windows.Forms.Button();
			this.picPokemonItem = new global::System.Windows.Forms.PictureBox();
			this.lblPokemonUnknownValue2 = new global::System.Windows.Forms.Label();
			this.lblPokemonUnknownValue1 = new global::System.Windows.Forms.Label();
			this.lblPokemonIv = new global::System.Windows.Forms.Label();
			this.nudPokemonUnknownValue2 = new global::System.Windows.Forms.NumericUpDown();
			this.lblPokemonLevel = new global::System.Windows.Forms.Label();
			this.nudPokemonUnknownValue1 = new global::System.Windows.Forms.NumericUpDown();
			this.nudPokemonIv = new global::System.Windows.Forms.NumericUpDown();
			this.nudPokemonLevel = new global::System.Windows.Forms.NumericUpDown();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.cmbMove4 = new global::System.Windows.Forms.ComboBox();
			this.cmbMove3 = new global::System.Windows.Forms.ComboBox();
			this.cmbMove2 = new global::System.Windows.Forms.ComboBox();
			this.cmbMove1 = new global::System.Windows.Forms.ComboBox();
			this.cmbPokemonItem = new global::System.Windows.Forms.ComboBox();
			this.cmbPokemonCode = new global::System.Windows.Forms.ComboBox();
			this.picPokemonIcon = new global::System.Windows.Forms.PictureBox();
			this.lstPokemonDataSlot = new global::System.Windows.Forms.ListBox();
			this.btnCreatePokemonData = new global::System.Windows.Forms.Button();
			this.btnSave = new global::System.Windows.Forms.Button();
			this.grpTrainerData.SuspendLayout();
			this.grpTrainerItem.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerUnknownValue).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonDataNum).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerAi).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIntroMusic).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerSprite).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerSprite).BeginInit();
			this.grpPokemonData.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonItem).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonUnknownValue2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonUnknownValue1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonIv).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonLevel).BeginInit();
			this.GroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonIcon).BeginInit();
			base.SuspendLayout();
			this.lstTrainerIdName.FormattingEnabled = true;
			this.lstTrainerIdName.ItemHeight = 12;
			this.lstTrainerIdName.Location = new global::System.Drawing.Point(14, 51);
			this.lstTrainerIdName.Name = "lstTrainerIdName";
			this.lstTrainerIdName.Size = new global::System.Drawing.Size(167, 424);
			this.lstTrainerIdName.TabIndex = 2;
			this.grpTrainerData.Controls.Add(this.cmbTrainerDataType);
			this.grpTrainerData.Controls.Add(this.lblTrainerDataType);
			this.grpTrainerData.Controls.Add(this.lblTrainerClass);
			this.grpTrainerData.Controls.Add(this.cmbTrainerClass);
			this.grpTrainerData.Controls.Add(this.grpTrainerItem);
			this.grpTrainerData.Controls.Add(this.nudTrainerUnknownValue);
			this.grpTrainerData.Controls.Add(this.lblTrainerUnknownValue);
			this.grpTrainerData.Controls.Add(this.lblPokemonDataNum);
			this.grpTrainerData.Controls.Add(this.nudPokemonDataNum);
			this.grpTrainerData.Controls.Add(this.txtPokemonDataAddress);
			this.grpTrainerData.Controls.Add(this.lblPokemonDataAddress);
			this.grpTrainerData.Controls.Add(this.btnChangeTrainerName);
			this.grpTrainerData.Controls.Add(this.lblTrainerAi);
			this.grpTrainerData.Controls.Add(this.chkDoubleBattle);
			this.grpTrainerData.Controls.Add(this.lblIntroMusic);
			this.grpTrainerData.Controls.Add(this.nudTrainerAi);
			this.grpTrainerData.Controls.Add(this.nudIntroMusic);
			this.grpTrainerData.Controls.Add(this.lblTrainerName);
			this.grpTrainerData.Controls.Add(this.txtTrainerName);
			this.grpTrainerData.Controls.Add(this.nudTrainerSprite);
			this.grpTrainerData.Controls.Add(this.picTrainerSprite);
			this.grpTrainerData.Location = new global::System.Drawing.Point(194, 14);
			this.grpTrainerData.Name = "grpTrainerData";
			this.grpTrainerData.Size = new global::System.Drawing.Size(504, 250);
			this.grpTrainerData.TabIndex = 3;
			this.grpTrainerData.TabStop = false;
			this.grpTrainerData.Text = "トレーナーデータ";
			this.cmbTrainerDataType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbTrainerDataType.Enabled = false;
			this.cmbTrainerDataType.FormattingEnabled = true;
			this.cmbTrainerDataType.Items.AddRange(new object[] { "00 - 普通", "01 - 技指定可", "02 - アイテム指定可", "03 - 両方指定可" });
			this.cmbTrainerDataType.Location = new global::System.Drawing.Point(170, 140);
			this.cmbTrainerDataType.Name = "cmbTrainerDataType";
			this.cmbTrainerDataType.Size = new global::System.Drawing.Size(128, 20);
			this.cmbTrainerDataType.TabIndex = 20;
			this.lblTrainerDataType.AutoSize = true;
			this.lblTrainerDataType.Location = new global::System.Drawing.Point(90, 146);
			this.lblTrainerDataType.Name = "lblTrainerDataType";
			this.lblTrainerDataType.Size = new global::System.Drawing.Size(65, 12);
			this.lblTrainerDataType.TabIndex = 19;
			this.lblTrainerDataType.Text = "データタイプ :";
			this.lblTrainerClass.AutoSize = true;
			this.lblTrainerClass.Location = new global::System.Drawing.Point(90, 50);
			this.lblTrainerClass.Name = "lblTrainerClass";
			this.lblTrainerClass.Size = new global::System.Drawing.Size(56, 12);
			this.lblTrainerClass.TabIndex = 18;
			this.lblTrainerClass.Text = "肩書き名 :";
			this.cmbTrainerClass.FormattingEnabled = true;
			this.cmbTrainerClass.Location = new global::System.Drawing.Point(170, 46);
			this.cmbTrainerClass.Name = "cmbTrainerClass";
			this.cmbTrainerClass.Size = new global::System.Drawing.Size(128, 20);
			this.cmbTrainerClass.TabIndex = 17;
			this.grpTrainerItem.Controls.Add(this.cmbTrainerItem4);
			this.grpTrainerItem.Controls.Add(this.cmbTrainerItem3);
			this.grpTrainerItem.Controls.Add(this.cmbTrainerItem2);
			this.grpTrainerItem.Controls.Add(this.cmbTrainerItem1);
			this.grpTrainerItem.Controls.Add(this.picTrainerItem4);
			this.grpTrainerItem.Controls.Add(this.picTrainerItem3);
			this.grpTrainerItem.Controls.Add(this.picTrainerItem2);
			this.grpTrainerItem.Controls.Add(this.picTrainerItem1);
			this.grpTrainerItem.Location = new global::System.Drawing.Point(306, 72);
			this.grpTrainerItem.Name = "grpTrainerItem";
			this.grpTrainerItem.Size = new global::System.Drawing.Size(184, 164);
			this.grpTrainerItem.TabIndex = 16;
			this.grpTrainerItem.TabStop = false;
			this.grpTrainerItem.Text = "トレーナー所持アイテム";
			this.cmbTrainerItem4.FormattingEnabled = true;
			this.cmbTrainerItem4.Location = new global::System.Drawing.Point(46, 130);
			this.cmbTrainerItem4.Name = "cmbTrainerItem4";
			this.cmbTrainerItem4.Size = new global::System.Drawing.Size(126, 20);
			this.cmbTrainerItem4.TabIndex = 1;
			this.cmbTrainerItem3.FormattingEnabled = true;
			this.cmbTrainerItem3.Location = new global::System.Drawing.Point(46, 95);
			this.cmbTrainerItem3.Name = "cmbTrainerItem3";
			this.cmbTrainerItem3.Size = new global::System.Drawing.Size(126, 20);
			this.cmbTrainerItem3.TabIndex = 1;
			this.cmbTrainerItem2.FormattingEnabled = true;
			this.cmbTrainerItem2.Location = new global::System.Drawing.Point(46, 60);
			this.cmbTrainerItem2.Name = "cmbTrainerItem2";
			this.cmbTrainerItem2.Size = new global::System.Drawing.Size(126, 20);
			this.cmbTrainerItem2.TabIndex = 1;
			this.cmbTrainerItem1.FormattingEnabled = true;
			this.cmbTrainerItem1.Location = new global::System.Drawing.Point(46, 25);
			this.cmbTrainerItem1.Name = "cmbTrainerItem1";
			this.cmbTrainerItem1.Size = new global::System.Drawing.Size(126, 20);
			this.cmbTrainerItem1.TabIndex = 1;
			this.picTrainerItem4.Location = new global::System.Drawing.Point(12, 128);
			this.picTrainerItem4.Name = "picTrainerItem4";
			this.picTrainerItem4.Size = new global::System.Drawing.Size(24, 24);
			this.picTrainerItem4.TabIndex = 0;
			this.picTrainerItem4.TabStop = false;
			this.picTrainerItem3.Location = new global::System.Drawing.Point(12, 93);
			this.picTrainerItem3.Name = "picTrainerItem3";
			this.picTrainerItem3.Size = new global::System.Drawing.Size(24, 24);
			this.picTrainerItem3.TabIndex = 0;
			this.picTrainerItem3.TabStop = false;
			this.picTrainerItem2.Location = new global::System.Drawing.Point(12, 58);
			this.picTrainerItem2.Name = "picTrainerItem2";
			this.picTrainerItem2.Size = new global::System.Drawing.Size(24, 24);
			this.picTrainerItem2.TabIndex = 0;
			this.picTrainerItem2.TabStop = false;
			this.picTrainerItem1.Location = new global::System.Drawing.Point(12, 23);
			this.picTrainerItem1.Name = "picTrainerItem1";
			this.picTrainerItem1.Size = new global::System.Drawing.Size(24, 24);
			this.picTrainerItem1.TabIndex = 0;
			this.picTrainerItem1.TabStop = false;
			this.nudTrainerUnknownValue.Location = new global::System.Drawing.Point(170, 216);
			global::System.Windows.Forms.NumericUpDown nudTrainerUnknownValue = this.nudTrainerUnknownValue;
			int[] array = new int[4];
			array[0] = 65535;
			nudTrainerUnknownValue.Maximum = new decimal(array);
			this.nudTrainerUnknownValue.Name = "nudTrainerUnknownValue";
			this.nudTrainerUnknownValue.Size = new global::System.Drawing.Size(80, 19);
			this.nudTrainerUnknownValue.TabIndex = 15;
			this.lblTrainerUnknownValue.AutoSize = true;
			this.lblTrainerUnknownValue.Location = new global::System.Drawing.Point(90, 220);
			this.lblTrainerUnknownValue.Name = "lblTrainerUnknownValue";
			this.lblTrainerUnknownValue.Size = new global::System.Drawing.Size(47, 12);
			this.lblTrainerUnknownValue.TabIndex = 14;
			this.lblTrainerUnknownValue.Text = "不明値 :";
			this.lblPokemonDataNum.AutoSize = true;
			this.lblPokemonDataNum.Location = new global::System.Drawing.Point(90, 195);
			this.lblPokemonDataNum.Name = "lblPokemonDataNum";
			this.lblPokemonDataNum.Size = new global::System.Drawing.Size(56, 12);
			this.lblPokemonDataNum.TabIndex = 13;
			this.lblPokemonDataNum.Text = "手持ち数 :";
			this.nudPokemonDataNum.Enabled = false;
			this.nudPokemonDataNum.Location = new global::System.Drawing.Point(170, 191);
			global::System.Windows.Forms.NumericUpDown nudPokemonDataNum = this.nudPokemonDataNum;
			int[] array2 = new int[4];
			array2[0] = 255;
			nudPokemonDataNum.Maximum = new decimal(array2);
			this.nudPokemonDataNum.Name = "nudPokemonDataNum";
			this.nudPokemonDataNum.Size = new global::System.Drawing.Size(44, 19);
			this.nudPokemonDataNum.TabIndex = 12;
			this.txtPokemonDataAddress.Location = new global::System.Drawing.Point(170, 166);
			this.txtPokemonDataAddress.Name = "txtPokemonDataAddress";
			this.txtPokemonDataAddress.ReadOnly = true;
			this.txtPokemonDataAddress.Size = new global::System.Drawing.Size(80, 19);
			this.txtPokemonDataAddress.TabIndex = 11;
			this.lblPokemonDataAddress.AutoSize = true;
			this.lblPokemonDataAddress.Location = new global::System.Drawing.Point(90, 170);
			this.lblPokemonDataAddress.Name = "lblPokemonDataAddress";
			this.lblPokemonDataAddress.Size = new global::System.Drawing.Size(72, 12);
			this.lblPokemonDataAddress.TabIndex = 10;
			this.lblPokemonDataAddress.Text = "手持ちデータ :";
			this.btnChangeTrainerName.Location = new global::System.Drawing.Point(306, 19);
			this.btnChangeTrainerName.Name = "btnChangeTrainerName";
			this.btnChangeTrainerName.Size = new global::System.Drawing.Size(114, 23);
			this.btnChangeTrainerName.TabIndex = 9;
			this.btnChangeTrainerName.Text = "名前を変更";
			this.btnChangeTrainerName.UseVisualStyleBackColor = true;
			this.lblTrainerAi.AutoSize = true;
			this.lblTrainerAi.Location = new global::System.Drawing.Point(90, 100);
			this.lblTrainerAi.Name = "lblTrainerAi";
			this.lblTrainerAi.Size = new global::System.Drawing.Size(69, 12);
			this.lblTrainerAi.TabIndex = 8;
			this.lblTrainerAi.Text = "トレーナーAI :";
			this.chkDoubleBattle.AutoSize = true;
			this.chkDoubleBattle.Location = new global::System.Drawing.Point(90, 122);
			this.chkDoubleBattle.Name = "chkDoubleBattle";
			this.chkDoubleBattle.Size = new global::System.Drawing.Size(80, 16);
			this.chkDoubleBattle.TabIndex = 7;
			this.chkDoubleBattle.Text = "ダブルバトル";
			this.chkDoubleBattle.UseVisualStyleBackColor = true;
			this.lblIntroMusic.AutoSize = true;
			this.lblIntroMusic.Location = new global::System.Drawing.Point(90, 76);
			this.lblIntroMusic.Name = "lblIntroMusic";
			this.lblIntroMusic.Size = new global::System.Drawing.Size(72, 12);
			this.lblIntroMusic.TabIndex = 6;
			this.lblIntroMusic.Text = "戦闘前BGM :";
			this.nudTrainerAi.Location = new global::System.Drawing.Point(170, 97);
			global::System.Windows.Forms.NumericUpDown nudTrainerAi = this.nudTrainerAi;
			int[] array3 = new int[4];
			array3[0] = 255;
			nudTrainerAi.Maximum = new decimal(array3);
			this.nudTrainerAi.Name = "nudTrainerAi";
			this.nudTrainerAi.Size = new global::System.Drawing.Size(44, 19);
			this.nudTrainerAi.TabIndex = 5;
			this.nudIntroMusic.Location = new global::System.Drawing.Point(170, 72);
			global::System.Windows.Forms.NumericUpDown nudIntroMusic = this.nudIntroMusic;
			int[] array4 = new int[4];
			array4[0] = 255;
			nudIntroMusic.Maximum = new decimal(array4);
			this.nudIntroMusic.Name = "nudIntroMusic";
			this.nudIntroMusic.Size = new global::System.Drawing.Size(44, 19);
			this.nudIntroMusic.TabIndex = 4;
			this.lblTrainerName.AutoSize = true;
			this.lblTrainerName.Location = new global::System.Drawing.Point(90, 26);
			this.lblTrainerName.Name = "lblTrainerName";
			this.lblTrainerName.Size = new global::System.Drawing.Size(70, 12);
			this.lblTrainerName.TabIndex = 3;
			this.lblTrainerName.Text = "トレーナー名 :";
			this.txtTrainerName.Location = new global::System.Drawing.Point(170, 21);
			this.txtTrainerName.Name = "txtTrainerName";
			this.txtTrainerName.Size = new global::System.Drawing.Size(128, 19);
			this.txtTrainerName.TabIndex = 2;
			this.nudTrainerSprite.Location = new global::System.Drawing.Point(14, 96);
			global::System.Windows.Forms.NumericUpDown nudTrainerSprite = this.nudTrainerSprite;
			int[] array5 = new int[4];
			array5[0] = 255;
			nudTrainerSprite.Maximum = new decimal(array5);
			this.nudTrainerSprite.Name = "nudTrainerSprite";
			this.nudTrainerSprite.Size = new global::System.Drawing.Size(64, 19);
			this.nudTrainerSprite.TabIndex = 1;
			this.picTrainerSprite.Location = new global::System.Drawing.Point(14, 24);
			this.picTrainerSprite.Name = "picTrainerSprite";
			this.picTrainerSprite.Size = new global::System.Drawing.Size(64, 64);
			this.picTrainerSprite.TabIndex = 0;
			this.picTrainerSprite.TabStop = false;
			this.grpPokemonData.Controls.Add(this.btnChangePokemonData);
			this.grpPokemonData.Controls.Add(this.picPokemonItem);
			this.grpPokemonData.Controls.Add(this.lblPokemonUnknownValue2);
			this.grpPokemonData.Controls.Add(this.lblPokemonUnknownValue1);
			this.grpPokemonData.Controls.Add(this.lblPokemonIv);
			this.grpPokemonData.Controls.Add(this.nudPokemonUnknownValue2);
			this.grpPokemonData.Controls.Add(this.lblPokemonLevel);
			this.grpPokemonData.Controls.Add(this.nudPokemonUnknownValue1);
			this.grpPokemonData.Controls.Add(this.nudPokemonIv);
			this.grpPokemonData.Controls.Add(this.nudPokemonLevel);
			this.grpPokemonData.Controls.Add(this.GroupBox2);
			this.grpPokemonData.Controls.Add(this.cmbPokemonItem);
			this.grpPokemonData.Controls.Add(this.cmbPokemonCode);
			this.grpPokemonData.Controls.Add(this.picPokemonIcon);
			this.grpPokemonData.Controls.Add(this.lstPokemonDataSlot);
			this.grpPokemonData.Controls.Add(this.btnCreatePokemonData);
			this.grpPokemonData.Location = new global::System.Drawing.Point(194, 274);
			this.grpPokemonData.Name = "grpPokemonData";
			this.grpPokemonData.Size = new global::System.Drawing.Size(504, 202);
			this.grpPokemonData.TabIndex = 4;
			this.grpPokemonData.TabStop = false;
			this.grpPokemonData.Text = "ポケモンデータ";
			this.btnChangePokemonData.Location = new global::System.Drawing.Point(14, 56);
			this.btnChangePokemonData.Name = "btnChangePokemonData";
			this.btnChangePokemonData.Size = new global::System.Drawing.Size(120, 23);
			this.btnChangePokemonData.TabIndex = 10;
			this.btnChangePokemonData.Text = "変更を反映（個体別）";
			this.btnChangePokemonData.UseVisualStyleBackColor = true;
			this.picPokemonItem.Location = new global::System.Drawing.Point(145, 63);
			this.picPokemonItem.Name = "picPokemonItem";
			this.picPokemonItem.Size = new global::System.Drawing.Size(24, 24);
			this.picPokemonItem.TabIndex = 9;
			this.picPokemonItem.TabStop = false;
			this.lblPokemonUnknownValue2.AutoSize = true;
			this.lblPokemonUnknownValue2.Location = new global::System.Drawing.Point(181, 168);
			this.lblPokemonUnknownValue2.Name = "lblPokemonUnknownValue2";
			this.lblPokemonUnknownValue2.Size = new global::System.Drawing.Size(53, 12);
			this.lblPokemonUnknownValue2.TabIndex = 8;
			this.lblPokemonUnknownValue2.Text = "不明値2 :";
			this.lblPokemonUnknownValue1.AutoSize = true;
			this.lblPokemonUnknownValue1.Location = new global::System.Drawing.Point(181, 144);
			this.lblPokemonUnknownValue1.Name = "lblPokemonUnknownValue1";
			this.lblPokemonUnknownValue1.Size = new global::System.Drawing.Size(53, 12);
			this.lblPokemonUnknownValue1.TabIndex = 8;
			this.lblPokemonUnknownValue1.Text = "不明値1 :";
			this.lblPokemonIv.AutoSize = true;
			this.lblPokemonIv.Location = new global::System.Drawing.Point(181, 120);
			this.lblPokemonIv.Name = "lblPokemonIv";
			this.lblPokemonIv.Size = new global::System.Drawing.Size(47, 12);
			this.lblPokemonIv.TabIndex = 8;
			this.lblPokemonIv.Text = "個体値 :";
			this.nudPokemonUnknownValue2.Location = new global::System.Drawing.Point(247, 164);
			global::System.Windows.Forms.NumericUpDown nudPokemonUnknownValue = this.nudPokemonUnknownValue2;
			int[] array6 = new int[4];
			array6[0] = 255;
			nudPokemonUnknownValue.Maximum = new decimal(array6);
			this.nudPokemonUnknownValue2.Name = "nudPokemonUnknownValue2";
			this.nudPokemonUnknownValue2.Size = new global::System.Drawing.Size(60, 19);
			this.nudPokemonUnknownValue2.TabIndex = 6;
			this.lblPokemonLevel.AutoSize = true;
			this.lblPokemonLevel.Location = new global::System.Drawing.Point(181, 96);
			this.lblPokemonLevel.Name = "lblPokemonLevel";
			this.lblPokemonLevel.Size = new global::System.Drawing.Size(40, 12);
			this.lblPokemonLevel.TabIndex = 7;
			this.lblPokemonLevel.Text = "レベル :";
			this.nudPokemonUnknownValue1.Location = new global::System.Drawing.Point(247, 140);
			global::System.Windows.Forms.NumericUpDown nudPokemonUnknownValue2 = this.nudPokemonUnknownValue1;
			int[] array7 = new int[4];
			array7[0] = 255;
			nudPokemonUnknownValue2.Maximum = new decimal(array7);
			this.nudPokemonUnknownValue1.Name = "nudPokemonUnknownValue1";
			this.nudPokemonUnknownValue1.Size = new global::System.Drawing.Size(60, 19);
			this.nudPokemonUnknownValue1.TabIndex = 6;
			this.nudPokemonIv.Location = new global::System.Drawing.Point(247, 116);
			global::System.Windows.Forms.NumericUpDown nudPokemonIv = this.nudPokemonIv;
			int[] array8 = new int[4];
			array8[0] = 255;
			nudPokemonIv.Maximum = new decimal(array8);
			this.nudPokemonIv.Name = "nudPokemonIv";
			this.nudPokemonIv.Size = new global::System.Drawing.Size(60, 19);
			this.nudPokemonIv.TabIndex = 6;
			this.nudPokemonLevel.Location = new global::System.Drawing.Point(247, 92);
			global::System.Windows.Forms.NumericUpDown nudPokemonLevel = this.nudPokemonLevel;
			int[] array9 = new int[4];
			array9[0] = 255;
			nudPokemonLevel.Maximum = new decimal(array9);
			this.nudPokemonLevel.Name = "nudPokemonLevel";
			this.nudPokemonLevel.Size = new global::System.Drawing.Size(60, 19);
			this.nudPokemonLevel.TabIndex = 6;
			this.GroupBox2.Controls.Add(this.cmbMove4);
			this.GroupBox2.Controls.Add(this.cmbMove3);
			this.GroupBox2.Controls.Add(this.cmbMove2);
			this.GroupBox2.Controls.Add(this.cmbMove1);
			this.GroupBox2.Location = new global::System.Drawing.Point(320, 36);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(170, 148);
			this.GroupBox2.TabIndex = 5;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "技構成";
			this.cmbMove4.FormattingEnabled = true;
			this.cmbMove4.Location = new global::System.Drawing.Point(12, 114);
			this.cmbMove4.Name = "cmbMove4";
			this.cmbMove4.Size = new global::System.Drawing.Size(144, 20);
			this.cmbMove4.TabIndex = 4;
			this.cmbMove3.FormattingEnabled = true;
			this.cmbMove3.Location = new global::System.Drawing.Point(12, 84);
			this.cmbMove3.Name = "cmbMove3";
			this.cmbMove3.Size = new global::System.Drawing.Size(144, 20);
			this.cmbMove3.TabIndex = 4;
			this.cmbMove2.FormattingEnabled = true;
			this.cmbMove2.Location = new global::System.Drawing.Point(12, 54);
			this.cmbMove2.Name = "cmbMove2";
			this.cmbMove2.Size = new global::System.Drawing.Size(144, 20);
			this.cmbMove2.TabIndex = 4;
			this.cmbMove1.FormattingEnabled = true;
			this.cmbMove1.Location = new global::System.Drawing.Point(12, 24);
			this.cmbMove1.Name = "cmbMove1";
			this.cmbMove1.Size = new global::System.Drawing.Size(144, 20);
			this.cmbMove1.TabIndex = 4;
			this.cmbPokemonItem.FormattingEnabled = true;
			this.cmbPokemonItem.Location = new global::System.Drawing.Point(181, 65);
			this.cmbPokemonItem.Name = "cmbPokemonItem";
			this.cmbPokemonItem.Size = new global::System.Drawing.Size(126, 20);
			this.cmbPokemonItem.TabIndex = 3;
			this.cmbPokemonCode.FormattingEnabled = true;
			this.cmbPokemonCode.Location = new global::System.Drawing.Point(181, 38);
			this.cmbPokemonCode.Name = "cmbPokemonCode";
			this.cmbPokemonCode.Size = new global::System.Drawing.Size(126, 20);
			this.cmbPokemonCode.TabIndex = 3;
			this.picPokemonIcon.Location = new global::System.Drawing.Point(141, 26);
			this.picPokemonIcon.Name = "picPokemonIcon";
			this.picPokemonIcon.Size = new global::System.Drawing.Size(32, 32);
			this.picPokemonIcon.TabIndex = 2;
			this.picPokemonIcon.TabStop = false;
			this.lstPokemonDataSlot.FormattingEnabled = true;
			this.lstPokemonDataSlot.ItemHeight = 12;
			this.lstPokemonDataSlot.Location = new global::System.Drawing.Point(14, 90);
			this.lstPokemonDataSlot.Name = "lstPokemonDataSlot";
			this.lstPokemonDataSlot.Size = new global::System.Drawing.Size(120, 100);
			this.lstPokemonDataSlot.TabIndex = 1;
			this.btnCreatePokemonData.Location = new global::System.Drawing.Point(14, 24);
			this.btnCreatePokemonData.Name = "btnCreatePokemonData";
			this.btnCreatePokemonData.Size = new global::System.Drawing.Size(120, 23);
			this.btnCreatePokemonData.TabIndex = 0;
			this.btnCreatePokemonData.Text = "手持ちデータを生成";
			this.btnCreatePokemonData.UseVisualStyleBackColor = true;
			this.btnSave.Location = new global::System.Drawing.Point(14, 18);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new global::System.Drawing.Size(166, 23);
			this.btnSave.TabIndex = 5;
			this.btnSave.Text = "変更を保存";
			this.btnSave.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(714, 493);
			base.Controls.Add(this.btnSave);
			base.Controls.Add(this.grpPokemonData);
			base.Controls.Add(this.grpTrainerData);
			base.Controls.Add(this.lstTrainerIdName);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "TrainerDataEditor";
			this.Text = "トレーナーデータ";
			this.grpTrainerData.ResumeLayout(false);
			this.grpTrainerData.PerformLayout();
			this.grpTrainerItem.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerItem1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerUnknownValue).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonDataNum).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerAi).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudIntroMusic).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudTrainerSprite).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.picTrainerSprite).EndInit();
			this.grpPokemonData.ResumeLayout(false);
			this.grpPokemonData.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonItem).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonUnknownValue2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonUnknownValue1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonIv).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.nudPokemonLevel).EndInit();
			this.GroupBox2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.picPokemonIcon).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x0400067A RID: 1658
				private ListBox _lstTrainerIdName;
		private NumericUpDown _nudTrainerUnknownValue;
		private Button _btnChangeTrainerName;
		private CheckBox _chkDoubleBattle;
		private NumericUpDown _nudTrainerAi;
		private NumericUpDown _nudIntroMusic;
		private NumericUpDown _nudTrainerSprite;
		private ComboBox _cmbTrainerItem1;
		private ComboBox _cmbTrainerItem4;
		private ComboBox _cmbTrainerItem3;
		private ComboBox _cmbTrainerItem2;
		private ComboBox _cmbTrainerClass;
		private ComboBox _cmbTrainerDataType;
		private ListBox _lstPokemonDataSlot;
		private Button _btnCreatePokemonData;
		private Button _btnSave;
		private ComboBox _cmbPokemonCode;
		private ComboBox _cmbMove1;
		private ComboBox _cmbMove4;
		private ComboBox _cmbMove3;
		private ComboBox _cmbMove2;
		private NumericUpDown _nudPokemonUnknownValue1;
		private NumericUpDown _nudPokemonIv;
		private NumericUpDown _nudPokemonLevel;
		private ComboBox _cmbPokemonItem;
		private NumericUpDown _nudPokemonUnknownValue2;
		private Button _btnChangePokemonData;
        private global::System.ComponentModel.IContainer components;
	}
}
